<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>5 研究間異質性 | Doing Meta-Analysis in R</title>
<meta name="author" content="Mathias Harrer">
<meta name="author" content="Pim Cuijpers">
<meta name="author" content="Toshi A. Furukawa">
<meta name="author" content="David D. Ebert">
<meta name="description" content="B...">
<meta name="generator" content="bookdown 0.36 with bs4_book()">
<meta property="og:title" content="5 研究間異質性 | Doing Meta-Analysis in R">
<meta property="og:type" content="book">
<meta property="og:description" content="B...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="5 研究間異質性 | Doing Meta-Analysis in R">
<meta name="twitter:site" content="@MathiasHarrer">
<meta name="twitter:description" content="B...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/Fira_Sans-0.4.7/font.css" rel="stylesheet">
<link href="libs/Roboto_Mono-0.4.7/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.5.1/transition.js"></script><script src="libs/bs3compat-0.5.1/tabs.js"></script><script src="libs/bs3compat-0.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css">
<style>

    :root {
      --background-color: #FFFEFA;
      --text-color: #000;
      --highlight-color: #277DB0;
      --border-color: #999896;
      --grey-color: #6C6C6C;
      --line-color: #eee;
      --bg-box: #f5f5f5;
      --box-border-color: #eeeeee;
      --code-bg: #f8f8f8;
      --code-chunk-bg: linear-gradient(160deg,#f8f8f8 0, #f1f1f1 100%);
      --code-text-color: #212529;
      --hr-border-top: 1px solid rgba(0,0,0,0.1);
      --table-text-color: #000;
      --toc-active: #eee;
      --form-color: #4D4C4B;
      --form-background-color: #FFFEFA;
      --form-border: 1px solid #999896;
      --aa-cursor-background-color: #B2D7FF;
    }


    [data-theme="dark"] {
      --background-color: #2b2b2b;
      --text-color: #ffffff;
      --highlight-color: #34a8ed;
      --border-color: yellow;
      --grey-color: #cfcfcf;
      --line-color: #575757;
      --bg-box: #474747;
      --box-border-color: #474747;
      --code-bg: #474747;
      --code-chunk-bg: linear-gradient(160deg,#CDCDCD 0,#f1f1f1 100%);
      --code-text-color: #ffffff;
      --hr-border-top: 1px solid #575757;
      --table-text-color: #ffffff;
      --toc-active: #474747;
      --form-color: #cfcfcf;
      --form-background-color: #474747;
      --form-border: 1px solid #575757;
      --aa-cursor-background-color: #2b2b2b;
    }

    .algolia-autocomplete .aa-dropdown-menu .aa-suggestion {
      color: var(--form-color);
      border-bottom: 1px var(--form-border) solid;
      background-color: var(--form-background-color);
    }

    .algolia-autocomplete .aa-dropdown-menu .aa-suggestion.aa-cursor {
      background-color: var(--aa-cursor-background-color);
    }

    strong {
      font-family: "Helvetica Neue",
        Arial,
        "Hiragino Kaku Gothic ProN",
        "Hiragino Sans",
        Meiryo,
        sans-serif;
      font-weight: bolder;
    }

    .form-control {
      color: var(--form-color);
      background-color: var(--form-background-color);
      border: var(--form-border);
    }

    .form-control:focus {
      color: var(--text-color);
      background-color: var(--form-background-color);
      border: var(--form-border);
    }


    nav[data-toggle="toc"] .nav a.nav-link.active, nav[data-toggle="toc"] .nav .nav-link.active > li > a {
        background-color: var(--toc-active);
    }

    .btn-circle.btn-md {
      width: 50px;
      height: 50px;
      padding: 7px 10px;
      border-radius: 25px;
      font-size: 10px;
      text-align: center;
    }


    .lightable-classic td {
      color: var(--text-color);
    }


    .table {
      color: var(--table-text-color);
    }

    hr {
      border-top: var(--hr-border-top);
    }

    code {
      background-color: var(--code-bg);
      color: var(--code-text-color);
    }

    pre {
      background-image: var(--code-chunk-bg);
    }

    body {
      background-color: var(--background-color);
      color: var(--text-color);
    }

    a {
      color: var(--highlight-color);
    }

    .header-section-number {
      color: var(--grey-color);
    }

    small.text-muted {
      color: var(--grey-color) !important;
    }


    .firstcharacter {
      color: var(--highlight-color);
    }

    p.caption {
      color: var(--grey-color);
    }

    .figure {
      border-top: 2px solid var(--line-color);
      border-bottom: 2px solid var(--line-color);
    }


    .inline-figure {
      border: 0;
      box-shadow: none;
    }

    .boxinfo {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boxinfo:before {
        content: '\f0eb';
        font-family: FontAwesome;
        left:20px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .boxempty {
      padding: 1em 1em 1em 1.1em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boxempty:before {
        content: '\f0eb';
        font-family: FontAwesome;
        left:0px;
        position:absolute;
        font-size: 30px;
        color: transparent;
     }

    .boximportant {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boximportant:before {
        content: '\f06a';
        font-family: FontAwesome;
        left:13px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .boxreport {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boxreport:before {
        content: '\f570';
        font-family: FontAwesome;
        left:15px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .boxdmetar {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .csl-entry {
      margin-bottom: 20px;
      padding-left: 1.5em;
      text-indent:-1.5em;
    }

    .boxdmetar:before {
        content: '\f4f7';
        font-family: FontAwesome;
        left:10px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .boxquestion {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boxquestion:before {
        content: '\f059';
        font-family: FontAwesome;
        left:12px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .mode-switch {
      font-size: 0.9rem;
    }

    img {
      max-width: 100%;
      height: auto;
      border-radius: .25rem;
    }


    .firstcharacter {
      color: var(--highlight-color);
      float: left;
      font-size: 40px;
      line-height: 50px;
      padding-bottom: 2px;
      padding-right: 8px;
      padding-left: 2px;
    }


    .btn-circle.btn-sm {
        width: 30px;
        height: 30px;
        padding: 6px 0px;
        border-radius: 15px;
        font-size: 20px;
        text-align: center;
    }
    .btn-circle.btn-md {
        width: 50px;
        height: 50px;
        padding: 7px 10px;
        border-radius: 25px;
        font-size: 20px;
        text-align: center;
    }
    .btn-circle.btn-xl {
        width: 60px;
        height: 60px;
        padding: 7px 7px;
        border-radius: 35px;
        font-size: 30px;
        text-align: center;
    }

    #critical-btn.btn-secondary {
      background-color: var(--grey-color);
      border-color: var(--grey-color);
    }

    .sticky-item {
        position: fixed;
        bottom: 30px;
        right: 30px;
    }



    </style>
<link rel="shortcut icon" href="favicon.ico">
<script type="text/x-mathjax-config">
    const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
    for (let popover of popovers){
      const div = document.createElement('div');
      div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
      div.innerHTML = popover.getAttribute('data-content');

      // Will this work with TeX on its own line?
      var has_math = div.querySelector("span.math");
      if (has_math) {
        document.body.appendChild(div);
      	MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
      	MathJax.Hub.Queue(function(){
          popover.setAttribute('data-content', div.innerHTML);
      	})
      }
    }
    </script><link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script><script type="text/javascript">
      // Add switch element
      document.addEventListener('DOMContentLoaded', function(event){
        let darkSwitch = document.createElement('div');
        darkSwitch.innerHTML = "<div class='sticky-item'><button type='button' id='critical-btn' class='btn btn-dark btn-circle btn-xl'>🌓</button></div>"
        document.body.appendChild(darkSwitch);
      })

    $(document).ready(function() {

        $("#critical-btn").click(function () {

            if ($(this).hasClass('btn-dark')){
                $('#critical-btn').removeClass('btn-dark').addClass('btn-secondary');
                $(this).addClass('btn-secondary').removeClass('btn-dark');
            }

            else if ($(this).hasClass('btn-secondary')){
                $('#critical-btn').removeClass('btn-secondary').addClass('btn-dark');
                $(this).addClass('btn-dark').removeClass('btn-secondary');
            }

        })
    })
    </script><script type="text/javascript">
      // Wait for document to load
      document.addEventListener("DOMContentLoaded", function(event) {
        document.documentElement.setAttribute("data-theme", "light");

        // Get our button switcher
        var themeSwitcher = document.getElementById("critical-btn");

        // When our button gets clicked
        themeSwitcher.onclick = function() {
          // Get the current selected theme, on the first run
          // it should be `light`
          var currentTheme = document.documentElement.getAttribute("data-theme");

          // Switch between `dark` and `light`
          var switchToTheme = currentTheme === "dark" ? "light" : "dark"

          // Set our currenet theme to the new one
          document.documentElement.setAttribute("data-theme", switchToTheme);

          // Save current selection
          localStorage.setItem('themeMode', switchToTheme);

        }
      });

      // keep selection across pages
      document.addEventListener('DOMContentLoaded', function(event){
        const currentTheme = localStorage.getItem('themeMode')
        if (currentTheme === 'dark'){
        document.documentElement.setAttribute("data-theme", 'dark');
          if ($("#critical-btn").hasClass('btn-dark')) {
            $('#critical-btn').removeClass('btn-dark').addClass('btn-secondary');
            $('#critical-btn').addClass('btn-secondary').removeClass('btn-dark');
          }
        } else {
        document.documentElement.setAttribute("data-theme", 'light');
          if ($("#critical-btn").hasClass('btn-secondary')) {
            $('#critical-btn').removeClass('btn-secondary').addClass('btn-dark');
            $('#critical-btn').addClass('btn-dark').removeClass('btn-secondary');
          }
      }})
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="A Hands-on Guide">Doing Meta-Analysis in R</a>:
        <small class="text-muted">A Hands-on Guide</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">ようこそ！</a></li>
<li><a class="" href="preface.html">序章</a></li>
<li><a class="" href="about-the-authors.html">著者について</a></li>
<li class="book-part">はじめに</li>
<li><a class="" href="intro.html"><span class="header-section-number">1</span> はじめに</a></li>
<li><a class="" href="discovering-R.html"><span class="header-section-number">2</span> R の発見</a></li>
<li class="book-part">Rでメタ分析</li>
<li><a class="" href="effects.html"><span class="header-section-number">3</span> 効果量</a></li>
<li><a class="" href="pooling-es.html"><span class="header-section-number">4</span> 効果量のプール</a></li>
<li><a class="active" href="heterogeneity.html"><span class="header-section-number">5</span> 研究間異質性</a></li>
<li><a class="" href="forest.html"><span class="header-section-number">6</span> フォレストプロット</a></li>
<li><a class="" href="subgroup.html"><span class="header-section-number">7</span> サブグループ解析</a></li>
<li><a class="" href="metareg.html"><span class="header-section-number">8</span> メタ回帰</a></li>
<li><a class="" href="pub-bias.html"><span class="header-section-number">9</span> 出版バイアス</a></li>
<li class="book-part">高度な分析</li>
<li><a class="" href="multilevel-ma.html"><span class="header-section-number">10</span> 「マルチレベル」メタ分析</a></li>
<li><a class="" href="sem.html"><span class="header-section-number">11</span> 構造方程式モデリングメタ分析</a></li>
<li><a class="" href="netwma.html"><span class="header-section-number">12</span> ネットワークメタ分析</a></li>
<li><a class="" href="bayesian-ma.html"><span class="header-section-number">13</span> ベイズメタ分析</a></li>
<li class="book-part">各種ツール</li>
<li><a class="" href="power.html"><span class="header-section-number">14</span> 検出力分析</a></li>
<li><a class="" href="risk-of-bias-plots.html"><span class="header-section-number">15</span> バイアスリスクのプロット</a></li>
<li><a class="" href="reporting-reproducibility.html"><span class="header-section-number">16</span> 報告と再現性</a></li>
<li><a class="" href="es-calc.html"><span class="header-section-number">17</span> 効果量の計算と換算</a></li>
<li class="book-part">付録</li>
<li><a class="" href="qanda.html"><span class="header-section-number">A</span> Q&amp;A</a></li>
<li><a class="" href="formula.html"><span class="header-section-number">B</span> 効果量の計算式</a></li>
<li><a class="" href="symbollist.html"><span class="header-section-number">C</span> シンボルマーク一覧</a></li>
<li><a class="" href="attr.html"><span class="header-section-number">D</span> R およびパッケージ情報</a></li>
<li><a class="" href="corrections.html"><span class="header-section-number">E</span> 訂正・備考</a></li>
<li><a class="" href="%E6%9C%AC%E6%9B%B8%E3%81%AE%E5%BC%95%E7%94%A8.html">本書の引用</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="heterogeneity" class="section level1" number="5">
<h1>
<span class="header-section-number">5</span> 研究間異質性<a class="anchor" aria-label="anchor" href="#heterogeneity"><i class="fas fa-link"></i></a>
</h1>
<hr>
<div class="inline-figure"><img src="_figs/heterogeneity.jpg"></div>
<p><br></p>
<p><span class="firstcharacter">B</span>
メタ分析で効果量をプールする方法については、すでに説明してきた。今まで見てきたように、固定効果モデルもランダム化モデルも、多くの異なる研究の効果を1つの数値に統合することが目的である。しかし、これは、りんごとオレンジを比較していない場合にのみ意味がある。例えば、メタ分析で計算した全体的な効果は小さいが、非常に高い効果量を持つ外れ値がいくつか残っているということがあり得る。このような情報は集計された効果からは失われ、すべての研究が小さな効果量をもたらしたのか、それとも例外があったのかはわからない。</p>
<p>
</p>
<p>メタ分析において、真の効果量がどの程度異なるかを<strong>研究間異質性</strong> (between-study heterogeneity) と呼ぶ。この概念については、前章でランダム効果モデルとの関連ですでに簡単に触れた。ランダム効果モデルは、研究間の異質性によって研究の真の効果量が異なることを想定している。そのため、この真の効果の分散を定量化する推定値 <span class="math inline">\(\tau^2\)</span> を含む。これにより、真の効果量分布の平均値として定義されるプール効果を計算することが可能である。</p>
<p>ランダム効果モデルは、たとえ異質な研究であっても、常にプール効果量を計算することが可能である。しかし、このプール効果が意味のある方法で<strong>解釈</strong>できるかどうかはわからない。プール効果だけでは、メタ分析におけるデータをうまく表現できないシナリオがたくさんある。</p>
<p>異質性が非常に高く、(例えば、ある治療法の) 真の効果の大きさが正から負までの範囲である場合を想像してみよう。このようなメタ分析のプール効果がプラスであったとしても、真の<strong>マイナス</strong>効果を持つ研究がいくつかあったということを伝えることができない。その治療法がいくつかの研究で悪影響を及ぼしたという事実は失われてしまう。</p>
<p>異質性が高いということは、研究が、真の効果が異なる2つ以上の<strong>サブグループ</strong>に分けられるという事実によって引き起こされることもある。このような情報は研究者にとって非常に貴重であり、効果が低いまたは高い特定の条件を見つけることができるかもしれない。しかし、プール効果を単独で見ると、このような詳細は見逃される可能性がある。極端な場合、異質性が非常に高いと、研究に共通点がなく、プール効果を解釈することが全く意味をなさなくなる可能性すらある。</p>
<p>したがって、メタ分析では、常に分析した研究のばらつきを考慮しなければならない。優れたメタ分析では、全体的な効果を報告するだけでなく、この推定値がどの程度信頼できるかを明記する必要がある。そのために不可欠なのが、研究間の異質性を定量化し、分析することである。</p>
<p>この章では、異質性を測定するさまざまな方法と、その解釈の仕方を詳しく見ていく。また、データ中の異質性に寄与している研究を検出することができるいくつかのツールについても説明する。最後に、「現実の」メタ分析で異質性が大きい場合の対処について説明する。</p>
<p><br></p>
<div id="het-measures" class="section level2" number="5.1">
<h2>
<span class="header-section-number">5.1</span> 異質性の尺度<a class="anchor" aria-label="anchor" href="#het-measures"><i class="fas fa-link"></i></a>
</h2>
<hr>
<p>異質性の尺度の議論を始める前に、まず異質性の意味は一つではないことを明らかにしておく必要がある。例えば、Rücker ら <span class="citation">(<a href="references.html#ref-rucker2008undue">2008</a>)</span> は、<strong>ベースライン</strong>または<strong>デザイン関連</strong>の異質性と、<strong>統計的</strong>異質性を区別している。</p>
<ul>
<li><p><strong>ベースライン</strong>または<strong>デザイン関連</strong>異質性は、研究の母集団または研究設計が研究間で異なる場合に生じる。この種の異質性については、「りんごとオレンジ」問題 (Chapter <a href="intro.html#pitfalls">1.3</a>) や、研究課題の定義方法 (Chapter <a href="intro.html#research-question">1.4.1</a>) について説明したときにも取り上げた。デザインに関連する異質性は、どのような種類の集団やデザインがメタ分析に適格であるかを決定する適切な PICO を設定することによって、<strong>a priori</strong> に低減させることが可能である。</p></li>
<li><p>一方、統計的異質性は、メタ分析に含まれる効果量推定値の広がりや精度によって影響を受ける、定量化可能な特性である。ベースライン異質性は、統計的異質性 (例えば、含まれる集団間で効果が異なる場合) につながる可能性があるが、必ずしもそうである必要はない。また、メタ分析では、含まれる研究自体が事実上同一であっても、高い統計的異質性を示すことがある。このガイド (および他のほとんどのメタ分析のテキスト) では、「研究間の異質性」という用語は、<strong>統計的</strong>な異質性のみを指す。</p></li>
</ul>
<p></p>
<p><br></p>
<div id="cochran-q" class="section level3" number="5.1.1">
<h3>
<span class="header-section-number">5.1.1</span> Cochran’s <span class="math inline">\(Q\)</span><a class="anchor" aria-label="anchor" href="#cochran-q"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p>ランダム効果モデルに基づくと、観察された効果が研究ごとに異なる原因となる変動要因は 2 つあることが分かっている。サンプリングエラー <span class="math inline">\(\epsilon_k\)</span> と、研究間の異質性による誤差 <span class="math inline">\(\zeta_k\)</span> である (Chapter <a href="pooling-es.html#rem">4.1.2</a>)。研究間異質性を定量化したいときに困難なこととして、変動のうち、どの程度がサンプリングエラーに起因し、どの程度が真の効果量の違いに起因するのかを識別することである。</p>
<p>伝統的にメタ分析では、研究のサンプル誤差と実際の研究間の異質性を区別するために、<strong>Cochran’s</strong> <span class="math inline">\(Q\)</span> <span class="citation">(<a href="references.html#ref-cochran1954some">Cochran 1954</a>)</span> を使用している。Cochran’s <span class="math inline">\(Q\)</span> は、<strong>加重二乗和</strong> (weighted sum of squares, <em>WSS</em>)として定義されている。これは、各研究の観察効果 <span class="math inline">\(\hat\theta_k\)</span> の要約効果 <span class="math inline">\(\hat\theta\)</span> からの偏差を、研究の分散の逆数 <span class="math inline">\(w_k\)</span> で重み付けしたものである。</p>
<p><span class="math display" id="eq:het1">\[\begin{equation}
Q = \sum^K_{k=1}w_k(\hat\theta_k-\hat\theta)^2
\tag{5.1}
\end{equation}\]</span></p>
<p></p>
<p>この式を詳しく見てみよう。まず、プール効果量に適用されるのと同じ逆分散加重が使われていることがわかる。この式の平均値 <span class="math inline">\(\hat\theta\)</span> は、固定効果モデルによるプール効果である。個々の効果が要約効果から逸脱する量である<strong>残差</strong>は、二乗され (値が常に正になるように)、重み付けされ、そして合計される。その結果の値が Cochran’s <span class="math inline">\(Q\)</span> である。</p>
<p><span class="math inline">\(w_k\)</span> による重み付けのため、<span class="math inline">\(Q\)</span> の値は、<span class="math inline">\(\hat\theta_k\)</span> が <span class="math inline">\(\hat\theta\)</span> からどれだけ乖離しているかだけでなく、研究の精度にも依存する。効果量の標準誤差が非常に小さい (つまり精度が非常に高い) 場合、要約効果からの乖離が小さくても高い重みが与えられ、<span class="math inline">\(Q\)</span> の値が高くなる。</p>
<p><span class="math inline">\(Q\)</span> の値は、データに<strong>過剰な変動</strong>があるかどうか、つまり、サンプル誤差だけから予想されるよりも多くの変動があるかどうかを確認するために使用することが可能である。もしそうであれば、残りの変動は研究間の異質性に起因すると考えることが可能である。このことをちょっとしたシミュレーションで説明しよう。</p>
<p></p>
<p>このシミュレーションでは、<span class="math inline">\(Q\)</span> が2つの異なるシナリオの下でどのように振る舞うかを検証したいと思われる: 研究間の異質性がない場合と、異質性がある場合である。まず、異質性がない場合から始めよう。これは、<span class="math inline">\(\zeta_k=0\)</span> 、残差 <span class="math inline">\(\hat\theta_k-\hat\theta\)</span> はサンプリング誤差 <span class="math inline">\(\epsilon_k\)</span> の積のみであることを意味する。ある平均効果量 <span class="math inline">\(\hat\theta\)</span> からの偏差をシミュレートするために、 <code>rnorm</code> 関数を使用することが可能である (正規分布に従うと仮定した)。それらは <span class="math inline">\(\hat\theta\)</span> を中心としているので、これらの「残差」の平均はゼロ ( <span class="math inline">\(\mu\)</span> = 0) であると期待可能である。この例では、母集団の標準偏差が <span class="math inline">\(\sigma=\)</span> 1 で、<strong>標準</strong>正規分布になると仮定しよう。</p>
<p>正規分布は通常 <span class="math inline">\(\mathcal{N}\)</span> で示され、残差は <span class="math inline">\(\mu=\)</span> 0 と <span class="math inline">\(\sigma=\)</span> 1 の正規分布から得られることを次のように記号化することが可能である。</p>
<p><span class="math display" id="eq:het2">\[\begin{equation}
\hat\theta_k-\hat\theta \sim \mathcal{N}(0,1)
\tag{5.2}
\end{equation}\]</span></p>
<p>これを <em>R</em> で試してみよう。<span class="math inline">\(K\)</span> = 40 効果量の残差 <span class="math inline">\(\hat\theta_k-\hat\theta\)</span> を <code>rnorm</code> を使って描画してみる。</p>
<div class="sourceCode" id="cb172"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span> <span class="co"># 結果を再現するために必要</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">40</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] -0.56048 -0.23018  1.55871  0.07051  0.12929
##  [6]  1.71506  0.46092 -1.26506 -0.68685 -0.44566
##  [...]
</code></pre>
<p>標準正規分布が <code>rnorm</code> のデフォルトなので、より単純なコード <code>rnorm(40)</code> を使うこともできる。</p>
<p>さて、この <span class="math inline">\(n=\)</span> 40 回サンプルを描くという作業を何度も何度も繰り返すというシミュレーションをしてみよう。これは <code>replicate</code> 関数を使って実現可能である。この関数では、<code>rnorm</code> の呼び出しを1万回繰り返すように指示した。その結果得られた値を <code>error_fixed</code> というオブジェクトに保存する。</p>
<div class="sourceCode" id="cb174"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">error_fixed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10000</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">40</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>サンプリングエラー <span class="math inline">\(\epsilon_k\)</span> に加えて、<strong>研究間の異質性</strong> (<span class="math inline">\(\zeta_k\)</span> 誤差) が存在すると仮定する2番目のシナリオを続ける。これは、真の効果量の分散を表す <code>rnorm</code> の 2 回目の呼び出しを追加することでシミュレートすることが可能である。この例では、真の効果量が標準正規分布に従うと仮定する。</p>
<p>このコードを使って、<span class="math inline">\(K\)</span> = 40 件の研究に、かなりの研究間異質性を持たせて 1 万回のメタ分析の残差をシミュレートすることが可能である。</p>
<div class="sourceCode" id="cb175"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">error_random</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">10000</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">40</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">40</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>異質性<strong>あり</strong>と<strong>なし</strong>のメタ分析について、<span class="math inline">\(\hat\theta_k-\hat\theta\)</span> の残差をシミュレーションしたので、<span class="math inline">\(Q\)</span> の値についても同じことをしてみよう。 このシミュレーションでは、分散、したがって各研究の重み <span class="math inline">\(w_k\)</span> が<strong>1</strong>であると仮定することによって <span class="math inline">\(Q\)</span> の式を少し単純化し、結果として <span class="math inline">\(w_k\)</span> が式から脱落するようにすることが可能である。つまり、先ほどの <code>rnorm</code> の呼び出しを使って、結果を二乗して合計し、この処理を1万回繰り返せばよいことになる。</p>
<p>以下はそのコードである。</p>
<div class="sourceCode" id="cb176"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">Q_fixed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="fl">10000</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">40</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">Q_random</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="fl">10000</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">40</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">40</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p><span class="math inline">\(Q\)</span> の重要な特性は、<span class="math inline">\(\chi^2\)</span> の分布に (おおよそ) 従うと仮定されていることである。<span class="math inline">\(\chi^2\)</span> 分布は、加重二乗和のように、正の値のみを取ることが可能である。これは、その <strong>自由度</strong>、つまり d.f. によって定義される。<span class="math inline">\(\chi^2\)</span> 分布は、小さな d.f. では右に裾が広がっているが、自由度が大きくなると正規分布に近づいていく。同時に、自由度は<strong>期待値</strong>、つまりそれぞれの <span class="math inline">\(\chi^2\)</span> 分布の平均値でもある。</p>
<p><span class="math inline">\(Q\)</span> が <span class="math inline">\(K-1\)</span> の自由度を持つ <span class="math inline">\(\chi^2\)</span> 分布にほぼ従うと仮定する (<span class="math inline">\(K\)</span> はメタ分析における研究数)。<strong>もし</strong>、効果量の差がサンプリングエラーによって<strong>のみ</strong>起きたものである場合。これは、<span class="math inline">\(K-1\)</span> の自由度を持つ <span class="math inline">\(\chi^2\)</span> 分布の平均が、サンプリング・エラーだけによって期待できる <span class="math inline">\(Q\)</span> の値を教えてくれることになる。</p>
<p>この説明は非常に抽象的なので、より具体的にするために、シミュレーションした値の分布を見てみよう。以下のコードでは、効果量「残差」と <span class="math inline">\(Q\)</span> の値のヒストグラムをプロットするために、 <code>hist</code> 関数を使用している。また、各プロットに理想化された分布を示す線を追加している。</p>
<p>このような分布は、正規分布の場合は <code>dnorm</code> 関数で、<span class="math inline">\(\chi^2\)</span> の場合は <code>dchisq</code> 関数で生成することが可能である。</p>
<div class="sourceCode" id="cb177"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 残差 (theta_k - theta) のヒストグラム</span></span>
<span><span class="co"># - error_fixed と error_random 両方の</span></span>
<span><span class="co">#   シミュレーション値のヒストグラムを作成</span></span>
<span><span class="co"># - `lines` を使い、青色で正規分布を追加</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">error_fixed</span>, </span>
<span>     xlab <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">hat</a></span><span class="op">(</span><span class="va">theta</span><span class="op">[</span><span class="va">k</span><span class="op">]</span><span class="op">)</span><span class="op">~</span><span class="op">-</span><span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">hat</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span><span class="op">)</span>, prob <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>     breaks <span class="op">=</span> <span class="fl">100</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">.45</span><span class="op">)</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>,<span class="fl">4</span><span class="op">)</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"No Heterogeneity"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">0.01</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">0.01</span><span class="op">)</span><span class="op">)</span>, </span>
<span>      col <span class="op">=</span> <span class="st">"blue"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">error_random</span>, </span>
<span>     xlab <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">hat</a></span><span class="op">(</span><span class="va">theta</span><span class="op">[</span><span class="va">k</span><span class="op">]</span><span class="op">)</span><span class="op">~</span><span class="op">-</span><span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">hat</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span><span class="op">)</span>, prob <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>     breaks <span class="op">=</span> <span class="fl">100</span>,ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">.45</span><span class="op">)</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>,<span class="fl">4</span><span class="op">)</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"Heterogeneity"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">0.01</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">0.01</span><span class="op">)</span><span class="op">)</span>, </span>
<span>      col <span class="op">=</span> <span class="st">"blue"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># Q-values のヒストグラム</span></span>
<span><span class="co"># - Q_fixed と Q_random 両方の</span></span>
<span><span class="co">#   シミュレーション値のヒストグラムを作成</span></span>
<span><span class="co"># - `lines` を使い、青色でカイ二乗分布を追加</span></span>
<span></span>
<span><span class="co"># まず、自由度 (k-1)　を計算</span></span>
<span><span class="co"># 注意: k=40 件の研究を毎回のシミュレーションで使用</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fl">40</span><span class="op">-</span><span class="fl">1</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">Q_fixed</span>, xlab <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="fu">italic</span><span class="op">(</span><span class="st">"Q"</span><span class="op">)</span><span class="op">)</span>, prob <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>     breaks <span class="op">=</span> <span class="fl">100</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">.06</span><span class="op">)</span>,xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">160</span><span class="op">)</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"No Heterogeneity"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">100</span>, <span class="fl">0.01</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">dchisq</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">100</span>, <span class="fl">0.01</span><span class="op">)</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span>, </span>
<span>      col <span class="op">=</span> <span class="st">"blue"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">Q_random</span>,  xlab <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="fu">italic</span><span class="op">(</span><span class="st">"Q"</span><span class="op">)</span><span class="op">)</span>, prob <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>     breaks <span class="op">=</span> <span class="fl">100</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">.06</span><span class="op">)</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">160</span><span class="op">)</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"Heterogeneity"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">100</span>, <span class="fl">0.01</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">dchisq</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">100</span>, <span class="fl">0.01</span><span class="op">)</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span>, </span>
<span>      col <span class="op">=</span> <span class="st">"blue"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<p>以下は、<em>R</em> で描いたプロットである。</p>
<p><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-127-1.png" width="50%"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-127-2.png" width="50%"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-127-3.png" width="50%"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-127-4.png" width="50%"></p>
<p>プロット生成に使用したコードがわかりにくいと思われるだろうが、心配はいらない。このシミュレーションのためだけに使用したものであり、実際のメタ分析の一部として作成されるプロットではない。</p>
<p>4 つのヒストグラムにあるものを見ていこう。最初の行は、効果量「残差」の分布で、異質性のあるものとないものがある。異質性のないデータは、私たちがプロットに含めた標準正規分布の線に忠実に沿っていることがわかる。これは、データがこの正確な分布を仮定して <code>rnorm</code> によって生成されたので、非常に論理的である。しかし、異質性を追加したデータは、標準正規分布に従いない。データの分散はより大きくなり、より重い尾を持つ分布になる。</p>
<p></p>
<p>さて、これが2行目の <span class="math inline">\(Q\)</span> の値の分布とどう関係しているのかを探ってみよう。異質性がない場合、<span class="math inline">\(Q\)</span> 値は、特徴的な右に歪んだ <span class="math inline">\(\chi^2\)</span> 分布に従っている。プロットでは、実線は自由度 39 の <span class="math inline">\(\chi^2\)</span> 分布の形状を示している (各シミュレーションで使われたのは、d.f. = <span class="math inline">\(K-1\)</span> および <span class="math inline">\(K\)</span> = 40 であるため)。シミュレーションされたデータはこの曲線にかなりよく従っていることがわかる。これは大きな驚きではない。私たちは、異質性がないとき、<span class="math inline">\(Q\)</span> が <span class="math inline">\(K-1\)</span> の自由度を持つ <span class="math inline">\(\chi^2\)</span> 分布に従うことを知っている。このシミュレーションデータもまさにこのケースである。バラツキはサンプル誤差によってのみ存在したのである。</p>
<p>異質性のある例では、分布は全く異なるように見える。シミュレーションされたデータは、期待された分布に全く従っていないように見える。値は目に見えて右にシフトしており、分布の平均は約 2 倍高くなっている。研究間にかなりの異質性がある場合、<span class="math inline">\(Q\)</span> 値は、異質性がないという仮定で期待される <span class="math inline">\(K-1\)</span> の値よりもかなり高くなると結論づけることが可能である。これは、研究間の異質性の存在をシミュレートするために、データに余分な変動を加えたので、驚くことではない。</p>
<p></p>
<p>これはやや長い説明であったが、それでも、<span class="math inline">\(Q\)</span> の統計的特性をどのように利用できるかをより理解するのに役立っただろう。 Cochran’s <span class="math inline">\(Q\)</span> は、メタ分析における変動が、異質性がないという帰無仮説の下で期待する量を著しく超えているかどうかを<strong>検定</strong>するのに利用可能である。</p>
<p>この<strong>異質性の検定</strong>はメタ分析でよく使われるもので、Chapter <a href="pooling-es.html#pooling-es">4</a> に戻ると、<strong>{meta}</strong> もデフォルトで提供してくれていることがわかる。これはよく <strong>Cochran’s</strong> <span class="math inline">\(Q\)</span> <strong>test</strong> と呼ばれるが、実はこれは誤記である。Cochran自身は <span class="math inline">\(Q\)</span> をこのように使うことを意図してはいないかった <span class="citation">(<a href="references.html#ref-hoaglin2016misunderstandings">Hoaglin 2016</a>)</span>。</p>
<p>
</p>
<p>Cochran’s <span class="math inline">\(Q\)</span> は、非常に重要な統計量である。これは、Higgins and Thompsonの <span class="math inline">\(I^2\)</span> 統計量や <span class="math inline">\(H^2\)</span> など、異質性を定量化する他の一般的な方法がこれに基づいていることが主な理由である。これらの尺度については、次のセクションで説明した。Cochran’s <span class="math inline">\(Q\)</span> は、<span class="math inline">\(\tau^2\)</span> を計算する異質性分散推定でも使われている。最も有名なのは DerSimonian-Laird 推定量である<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;DerSimonian-Laird 法は、&lt;span class="math inline"&gt;\(\hat\tau^2 = \dfrac{Q-(K-1)}{\sum_{k=1}^{K}w_k-\frac{\sum_{k=1}^Kw^2_k}{\sum_{k=1}^Kw_k}}\)&lt;/span&gt; を使用して異質性分散を計算する。&lt;span class="math inline"&gt;\(Q&amp;lt;(K-1)\)&lt;/span&gt; のとき、&lt;span class="math inline"&gt;\(\hat\tau^2 := 0\)&lt;/span&gt;。Chapter &lt;a href="pooling-es.html#rem"&gt;4.1.2&lt;/a&gt; と Chapter &lt;a href="pooling-es.html#tau-estimators"&gt;4.1.2.1&lt;/a&gt; も参照&lt;/p&gt;'><sup>27</sup></a>。</p>
<div class="boximportant">
<p>
<strong><span class="math inline"><span class="math inline">\(Q\)</span></span> の課題と <span class="math inline"><span class="math inline">\(Q\)</span></span>-検定</strong>
</p>
<p>
<span class="math inline"><span class="math inline">\(Q\)</span></span>
はメタアナリシスでよく使われ報告されているが、欠点がいくつかある。例えば
Hoaglin <span class="citation"><span class="citation">(<a href="references.html#ref-hoaglin2016misunderstandings">2016</a>)</span></span>
は、<span class="math inline"><span class="math inline">\(Q\)</span></span> が自由度 <span class="math inline"><span class="math inline">\(K-1\)</span></span> の <span class="math inline"><span class="math inline">\(\chi^2\)</span></span>
分布に従うという仮定はメタ分析における <span class="math inline"><span class="math inline">\(Q\)</span></span>
の実際の振る舞いを反映しておらず、したがって DerSimonian-Laird
法などにはバイアスがあるかもしれないと論じている。
</p>
<p>
より現実的な問題として、<span class="math inline"><span class="math inline">\(Q\)</span></span>
は研究の数 <span class="math inline"><span class="math inline">\(K\)</span></span> と精度
(すなわち研究のサンプルサイズ)
が増加したときの両方で増加する。したがって、<span class="math inline"><span class="math inline">\(Q\)</span></span>
とそれが有意であるかどうかは、メタアナリシスの規模、ひいてはその統計的検出力に大きく依存することになる。
</p>
<p>
このことから、異質性を評価する際には、<span class="math inline"><span class="math inline">\(Q\)</span></span>-検定の有意性だけに頼るべきではないことがわかる。メタアナリシスでは、<span class="math inline"><span class="math inline">\(Q\)</span></span>-検定の有意性に基づいて固定効果モデルかランダム効果モデルのどちらを適用するかを決めることがある。ここで述べた理由から、このアプローチは全く推奨されない。
</p>
</div>
<p><br></p>
</div>
<div id="i-squared" class="section level3" number="5.1.2">
<h3>
<span class="header-section-number">5.1.2</span> Higgins &amp; Thompson’s <span class="math inline">\(I^2\)</span> 統計量<a class="anchor" aria-label="anchor" href="#i-squared"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p></p>
<p><span class="math inline">\(I^2\)</span> 統計量 <span class="citation">(<a href="references.html#ref-higgins2002quantifying">J. P. Higgins and Thompson 2002</a>)</span> は、研究間の異質性を定量化する別の方法で、Cochran’s <span class="math inline">\(Q\)</span> に直接基づいている。これは、サンプリングエラーによって引き起こされない効果量の変動の割合と定義されている。<span class="math inline">\(I^2\)</span> は、異質性がないという帰無仮説のもと、自由度 <span class="math inline">\(K-1\)</span> を持つ <span class="math inline">\(\chi^2\)</span> 分布に従っているという前提に基づいて作成されている。これは、異質性がない場合 (すなわち、 <span class="math inline">\(K-1\)</span>) のとき、<span class="math inline">\(Q\)</span> <strong>観察</strong>値が <strong>期待された</strong> <span class="math inline">\(Q\)</span> 値をどの程度超えているかをパーセントで定量化するものである。</p>
<p><span class="math inline">\(I^2\)</span> の計算式は次のようになる。</p>
<p><span class="math display" id="eq:het3">\[\begin{equation}
I^2 = \frac{Q-(K-1)}{Q}
\tag{5.3}
\end{equation}\]</span></p>
<p>ここで、<span class="math inline">\(K\)</span> は研究の総数である。 <span class="math inline">\(I^2\)</span> の値は 0% より低くすることはできないので、<span class="math inline">\(Q\)</span> が <span class="math inline">\(K-1\)</span> より小さい場合は、負の値ではなく、単に <span class="math inline">\(0\)</span> とする<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;span class="math inline"&gt;\(I^2\)&lt;/span&gt; は上記の式で計算されるが、&lt;strong&gt;必ずしもすべてのソフトウェアが&lt;/strong&gt;この定義に従っているわけではないことに注意。例えば、&lt;strong&gt;{metafor}&lt;/strong&gt; は、between-study heterogeneity 分散 &lt;span class="math inline"&gt;\(\tau^2\)&lt;/span&gt; から以下のように推定 (&lt;a href="https://www.metafor-project.org/doku.php/tips:i2_multilevel_multivariate"&gt;ここ&lt;/a&gt;を参考) している。&lt;span class="math display"&gt;\[I^2 = \frac{\hat{\tau}^2}{\hat{\tau}^2 + \tilde{v}};\]&lt;/span&gt; ここで &lt;span class="math display"&gt;\[\tilde{v} = \frac{(K-1) \sum w_k}{(\sum w_k)^2 - \sum w_k^2}\]&lt;/span&gt; は、「平均」または「典型的」サンプリング分散で、サンプルのすべての研究 &lt;span class="math inline"&gt;\(k\)&lt;/span&gt; の重み &lt;span class="math inline"&gt;\(w_k\)&lt;/span&gt; から計算される (Chapter &lt;a href="pooling-es.html#fem"&gt;4.1.1&lt;/a&gt; 参照)。最初の式と比較すると、この &lt;span class="math inline"&gt;\(I^2\)&lt;/span&gt; は、&lt;strong&gt;&lt;span class="math inline"&gt;\(I^2\)&lt;/span&gt; は異質性の相対的な測定&lt;/strong&gt;であることを容易にする。「典型的」 within-study 分散 &lt;span class="math inline"&gt;\(\tilde{v}\)&lt;/span&gt; に依存するが、これはメタ分析ごとに値が異なる。Chapter &lt;a href="heterogeneity.html#het-measure-which"&gt;5.2&lt;/a&gt; で詳しく扱っている。また、これは、同じデータを使ってプールしても、異なる &lt;span class="math inline"&gt;\(I^2\)&lt;/span&gt; が返されることがある理由を説明できることがあることに注意。&lt;/p&gt;'><sup>28</sup></a>。</p>
<p><span class="math inline">\(I^2\)</span> がどのように計算されるかを説明するために、先ほどの <span class="math inline">\(Q\)</span> のシミュレーション値を使用しよう。まず、異質性がないと仮定した <code>Q_fixed</code> の 10 番目のシミュレーション値を選ぶ。そして、上の式を使って、<span class="math inline">\(I^2\)</span> を計算する。</p>
<div class="sourceCode" id="cb178"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 10 回目の Q のシミュレーションを表示</span></span>
<span><span class="va">Q_fixed</span><span class="op">[</span><span class="fl">10</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] 35.85787</code></pre>
<div class="sourceCode" id="cb180"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># k を定義</span></span>
<span><span class="va">k</span> <span class="op">&lt;-</span> <span class="fl">40</span></span>
<span></span>
<span><span class="co"># I^2 を計算</span></span>
<span><span class="op">(</span><span class="va">Q_fixed</span><span class="op">[</span><span class="fl">10</span><span class="op">]</span> <span class="op">-</span> <span class="op">(</span><span class="va">k</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="va">Q_fixed</span><span class="op">[</span><span class="fl">10</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] -0.08762746</code></pre>
<p>結果がマイナスなので、ゼロに切り上げると、<span class="math inline">\(I^2\)</span> = 0% となる。この値は、効果量のばらつきの 0% が研究間の異質性に起因していることを示している。これは、シミュレーションに使用した設定と一致している。</p>
<p>今度は、<code>Q_random</code> の 10 番目のシミュレート値で同じことをしよう。</p>
<div class="sourceCode" id="cb182"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="op">(</span><span class="va">Q_random</span><span class="op">[</span><span class="fl">10</span><span class="op">]</span> <span class="op">-</span> <span class="op">(</span><span class="va">k</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="va">Q_random</span><span class="op">[</span><span class="fl">10</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] 0.5692061</code></pre>
<p>このシミュレーションの <span class="math inline">\(I^2\)</span> 値は約 50% で、変動の約半分が研究間異質性に起因していることがわかる。この例の変動は、サンプル誤差と研究間異質性のシミュレーションに等しく基づいているので、これも私たちの予想に沿ったものである。</p>
<p>メタ分析における研究間異質性を報告するために <span class="math inline">\(I^2\)</span> 統計量を使用することは一般的であり、<span class="math inline">\(I^2\)</span> は <strong>{meta}</strong> から得られる出力にデフォルトで含まれている。この統計量の人気は、この統計量をどう解釈するかの「経験則」が存在することと関連しているだろう <span class="citation">(<a href="references.html#ref-higgins2002quantifying">J. P. Higgins and Thompson 2002</a>)</span>。</p>
<ul>
<li><p><span class="math inline">\(I^2\)</span> = 25%: 低い異質性</p></li>
<li><p><span class="math inline">\(I^2\)</span> = 50%: 中程度の異質性</p></li>
<li><p><span class="math inline">\(I^2\)</span> = 75%: 実質的な異質性を有する。</p></li>
</ul>
<p><br></p>
</div>
<div id="h2-統計量" class="section level3" number="5.1.3">
<h3>
<span class="header-section-number">5.1.3</span> <span class="math inline">\(H^2\)</span> 統計量<a class="anchor" aria-label="anchor" href="#h2-%E7%B5%B1%E8%A8%88%E9%87%8F"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p><span class="math inline">\(H^2\)</span> 統計量 <span class="citation">(<a href="references.html#ref-higgins2002quantifying">J. P. Higgins and Thompson 2002</a>)</span> も Cochran’s <span class="math inline">\(Q\)</span> から派生したもので、<span class="math inline">\(I^2\)</span> に似ている。これは、<span class="math inline">\(Q\)</span> で測定される観測された変動と、サンプル誤差による期待分散の比を記述するものである。</p>
<p><span class="math display" id="eq:het4">\[\begin{equation}
H^2 = \frac{Q}{K-1}
\tag{5.4}
\end{equation}\]</span></p>
<p><span class="math inline">\(Q\)</span> が <span class="math inline">\(K-1\)</span> より小さい場合、その値を人為的に修正する必要がないため、<span class="math inline">\(H^2\)</span> の計算は <span class="math inline">\(I^2\)</span> の計算よりわずかにエレガントである。研究間の異質性がない場合、<span class="math inline">\(H^2\)</span> は 1 (またはそれ以下) に相当する。1 より大きい値は、研究間の異質性があることを示す。</p>
<p><span class="math inline">\(I^2\)</span> と比較すると、発表されたメタ分析でこの統計量が報告されることは、はるかに少ない。しかし、<span class="math inline">\(H^2\)</span> は <strong>{meta}</strong> のメタ分析関数の出力にデフォルトで含まれている。</p>
<p><br></p>
</div>
<div id="tau" class="section level3" number="5.1.4">
<h3>
<span class="header-section-number">5.1.4</span> 異質性分散 <span class="math inline">\(\tau^2\)</span> と標準偏差 <span class="math inline">\(\tau\)</span><a class="anchor" aria-label="anchor" href="#tau"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p>異質性分散 <span class="math inline">\(\tau^2\)</span> については、すでに Chapter <a href="pooling-es.html#rem">4.1.2</a> で詳しく説明してきた。そこで述べたように、<span class="math inline">\(\tau^2\)</span> は、私たちのデータの基礎となる真の効果量の<strong>分散</strong>を定量化するものである。<span class="math inline">\(\tau^2\)</span> の平方根をとると、<span class="math inline">\(\tau\)</span> が得られ、これは真の効果の大きさの<strong>標準偏差</strong>である。</p>
<p><span class="math inline">\(\tau\)</span> の大きな特徴は、効果量と同じ尺度で表現されていることである。これは、たとえば、一次調査におけるサンプルの年齢の平均と標準偏差を解釈するのと同じように、これを解釈できることを意味した。<span class="math inline">\(\tau\)</span> の値は、真の効果量の<strong>範囲</strong>について何かを教えてくれる。</p>
<p>例えば、<span class="math inline">\(\tau\)</span> に 1.96 を掛け、プール効果量にこの値を加減することで、真の効果量の95%信頼区間を計算することが可能である。Chapter <a href="pooling-es.html#pre-calculated-es">4.2.1</a> で計算した <code>m.gen</code> メタ分析を使って、これを試してみることが可能である。</p>
<p>このメタ分析におけるプール効果と <span class="math inline">\(\tau\)</span> 推定値がどのようなものであったか、もう一度見てみよう。</p>
<div class="sourceCode" id="cb184"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 効果プール</span></span>
<span><span class="va">m.gen</span><span class="op">$</span><span class="va">TE.random</span></span></code></pre></div>
<pre><code>## [1] 0.5771158</code></pre>
<div class="sourceCode" id="cb186"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># tau 推定</span></span>
<span><span class="va">m.gen</span><span class="op">$</span><span class="va">tau</span></span></code></pre></div>
<pre><code>## [1] 0.2863311</code></pre>
<p><span class="math inline">\(g=\)</span> 0.58、<span class="math inline">\(\tau=\)</span> 0.29であることがわかる。このデータに基づいて、95%真の効果量の信頼区間の下限と上限を計算することが可能である。0.58 <span class="math inline">\(-\)</span> 1.96 <span class="math inline">\(\times\)</span> 0.29 = 0.01 と 0.58 <span class="math inline">\(+\)</span> 1.96 <span class="math inline">\(\times\)</span> 0.29 = 1.15。</p>

<div class="boxinfo">
<p><strong>「不確かさの不確かさは？」: <span class="math inline">\(\tau^2\)</span> の信頼区間の計算</strong></p>
<p>研究間異質性分散推定値の不確実性 (すなわち、<span class="math inline">\(\tau^2\)</span> 付近の信頼区間) を定量化する方法は、現在も検討されている分野である。いくつかのアプローチが考えられるが、その妥当性は <span class="math inline">\(\tau^2\)</span> 推定量の種類に依存する (Chapter <a href="pooling-es.html#tau-estimators">4.1.2.1</a>)。</p>
<p><strong>{meta}</strong> パッケージは Veronikki <span class="citation">(<a href="references.html#ref-veroniki2016methods">2016</a>)</span>の推奨に従い、ほとんどの推定量に対して <span class="math inline">\(Q\)</span><strong>-Profile</strong> 法 <span class="citation">(<a href="references.html#ref-viechtbauer2007confidence">Viechtbauer 2007b</a>)</span> を使用する。</p>
<p><span class="math inline">\(Q\)</span>-Profile 法は、<span class="math inline">\(Q\)</span> の改良版である<strong>一般化</strong> <span class="math inline">\(Q\)</span><strong>-統計量</strong> <span class="math inline">\(Q_{\text{gen}}\)</span>を用いた手法である．標準版の<span class="math inline">\(Q\)</span>が固定効果モデルに基づくプール効果を用いるのに対し，<span class="math inline">\(Q_{\text{gen}}\)</span> はランダム効果モデルに基づいている。ランダム効果モデルによる全体効果である <span class="math inline">\(\hat\mu\)</span> とランダム効果モデルに基づく重みを用いて偏差を計算する。</p>
<p><span class="math display" id="eq:het5">\[\begin{equation}
Q_{\text{gen}} = \sum_{k=1}^{K} w^*_k (\hat\theta_k-\hat\mu)^2
\tag{5.5}
\end{equation}\]</span></p>
<p>ここで、<span class="math inline">\(w^*_k\)</span> はランダム効果重み ( Chapter <a href="pooling-es.html#tau-estimators">4.1.2.1</a> を参照) である。</p>
<p><span class="math display" id="eq:het6">\[\begin{equation}
w^*_k = \frac{1}{s^2_k+\tau^2}
\tag{5.6}
\end{equation}\]</span></p>
<p>また、<span class="math inline">\(Q_{\text{gen}}\)</span> は自由度 <span class="math inline">\(K-1\)</span> の <span class="math inline">\(\chi^2\)</span> 分布に従うことが示されている。一般化　<span class="math inline">\(Q\)</span>　統計量は <span class="math inline">\(\tau^2)\)</span> の値が大きいか小さいかで異なる値の <span class="math inline">\(Q_{\text{gen}}\)</span> を返す関数 <span class="math inline">\(Q_{\text{gen}}(\tau^2)\)</span> と考えることができる。この関数の結果は、<span class="math inline">\(\chi^2\)</span> 分布となる。</p>
<p>この <span class="math inline">\(\chi^2\)</span> 分布は明確に予測できるパターンに従っているので、例えば 95% カバーする信頼区間を簡単に求めることができる。その自由度 <span class="math inline">\(K-1\)</span> に基づいて、2.5 と97.5 パーセンタイルの <span class="math inline">\(\chi^2\)</span> の値を求めればよい。 <em>R</em> では、これは<strong>分位数関数</strong> <code>qchisq</code> を使用して簡単に行うことができる。例えば <code>qchisq(0.975, df=5)</code> とする。</p>
<p><span class="math inline">\(Q\)</span>-Profile 法は、この関係を利用して、<span class="math inline">\(\tau^2\)</span> 付近の信頼区間を繰り返し計算する手法である(いわゆる「プロファイリング」)。この方法では、<span class="math inline">\(Q_{\text{gen}}(\widetilde{\tau}^2)\)</span> の値を増加させながら、<span class="math inline">\(\chi^2\)</span> 分布に基づく信頼区間の下限と上限の期待値に到達するまで繰り返し計算する。</p>
<p><span class="math inline">\(Q\)</span>-Profile 法は、<strong>{meta}</strong> 関数の中で <code>method.tau.ci = "QP"</code> という引数で指定することができる。これはデフォルトの設定であり、この引数を手動で追加する必要はない。唯一の例外は、DerSimonian-Laird 推定法 (<code>method.tau = "DL"</code>) を使用した場合である。この場合，自動的に Jackson <span class="citation">(<a href="references.html#ref-jackson2013confidence">2013</a>)</span> による別の手法が使用される (手動で <code>method.tau.ci = "J"</code> と指定することで可能)。</p>
<p>通常、<strong>{meta}</strong> のデフォルトの動作から外れる必要はないが、メタアナリシスにおいて、どの方法で <span class="math inline">\(\tau^2\)</span> の信頼区間を計算したかを報告することは、他の人にとって有益な場合がある。</p>
</div>
<p><br></p>
</div>
</div>
<div id="het-measure-which" class="section level2" number="5.2">
<h2>
<span class="header-section-number">5.2</span> どの方法を使うべきか？<a class="anchor" aria-label="anchor" href="#het-measure-which"><i class="fas fa-link"></i></a>
</h2>
<hr>
<p>メタアナリシスで異質性を評価・報告する場合、統計的検出力の影響をあまり受けず、かつ頑健な指標が必要です。コクランの <span class="math inline">\(Q\)</span> は、研究の数が増えれば増えるほど、また精度 (すなわち研究のサンプルサイズ) が上がれば上がる。</p>
<p>つまり、<span class="math inline">\(Q\)</span> とそれが有意であるかどうかは、メタアナリシスの規模、その統計的検出力に大きく依存することになる。したがって、研究間の異質性を評価する際には、<span class="math inline">\(Q\)</span>、特に <span class="math inline">\(Q\)</span>-検定だけに頼るべきではない。</p>
<p>一方、<span class="math inline">\(I^2\)</span> は、分析対象の研究数の変化に対して敏感ではない。解釈も比較的簡単で、多くの研究者がその意味を理解している。一般的に、メタアナリシス報告書に異質性の指標として <span class="math inline">\(I^2\)</span> を含めることは悪い考えではない。特に、この統計量の信頼区間を示すことで、他の人が推定値の正確さを評価することができるようになる。</p>
<p>
</p>
<p>しかし、文献上ではよく使われているが、<span class="math inline">\(I^2\)</span> も異質性を測る完璧な指標ではない。異質性の絶対的な尺度ではなく、その値はやはり含まれる研究の精度に大きく依存する <span class="citation">(<a href="references.html#ref-borenstein2017basics">Borenstein et al. 2017</a>; <a href="references.html#ref-rucker2008undue">Rücker et al. 2008</a>)</span>。上で述べたように、<span class="math inline">\(I^2\)</span> は単純にサンプリングエラー <span class="math inline">\(\epsilon\)</span> によって引き起こされない変動の割合である。研究がどんどん大きくなれば、サンプリングエラーはゼロになる傾向があり、同時に <span class="math inline">\(I^2\)</span> は100%になる傾向がある。ただし、これは単に研究のサンプルサイズが大きくなったからである。</p>
<p>したがって、<span class="math inline">\(I^2\)</span> に<strong>だけ</strong>頼るのは良い選択肢とは言えない。<span class="math inline">\(H^2\)</span> は <span class="math inline">\(I^2\)</span> と似たような挙動をするので、この統計量にも同じ注意点がある。</p>
<p>一方、<span class="math inline">\(\tau^2\)</span> と <span class="math inline">\(\tau\)</span> の値は、研究数とその精度に依存しない。研究数や研究規模が大きくなっても系統的に増加することはない。しかし、<span class="math inline">\(\tau^2\)</span> が実用上どの程度の意味を持つのか、解釈しにくいことがある。例えば、ある研究で真の効果量の分散が <span class="math inline">\(\tau^2=\)</span> 0.08 であることが分かったとする。この分散が意味のあるものなのか、そうでないものなのかを判断するのは、自分自身にとっても、他の人にとっても、難しい場合がある。</p>
<p></p>
<p><strong>予測区間</strong> (Prediction intervals, PIs) は、この限界を克服する良い方法である <span class="citation">(<a href="references.html#ref-inthout2016plea">IntHout et al. 2016</a>)</span>。予測区間は、現在の証拠に基づき、将来の研究の効果がどの範囲に収まると予想できるかを示している。</p>
<p>予測区間が完全に介入に有利な「正」側にあるとする。これは、効果はさまざまであっても、我々が調査した文脈全体では、介入は将来有益であると期待されることを意味する。予測区間にゼロが含まれる場合、これについてはあまり確信が持てないが、広い予測区間はかなり一般的であることに注意する必要がある。</p>
<p>全体効果の予測区間 <span class="math inline">\(\hat\mu\)</span> を計算するために、推定された研究間異質性分散 <span class="math inline">\(\hat\tau^2\)</span> とプール効果の標準誤差 <span class="math inline">\(SE_{\hat\mu}\)</span> の両方を使用する。標準誤差の二乗と <span class="math inline">\(\hat\tau^2\)</span> の値を合計し、その平方根をとる。これによって、予測区間の標準偏差 <span class="math inline">\(SD_{\text{PI}}\)</span> が得られる。予測範囲は自由度<span class="math inline">\(K-1\)</span>の<span class="math inline">\(t\)</span>分布を仮定しているので、<span class="math inline">\(SD_{\text{PI}}\)</span> に <span class="math inline">\(t_{K-1}\)</span> の97.5値を掛け、その結果を <span class="math inline">\(\hat\mu\)</span> に加算・減算することになる。これは、プールされた効果の95%予測区間を与える。</p>
<p>95%予測区間の計算式は次のようになる。</p>
<p><span class="math display" id="eq:het7">\[\begin{align}
\hat\mu &amp;\pm t_{K-1, 0.975}\sqrt{SE_{\hat\mu}^2+\hat\tau^2} \notag \\
\hat\mu &amp;\pm t_{K-1, 0.975}SD_{\text{PI}} \tag{5.7}
\end{align}\]</span></p>
<p><strong>{meta}</strong> の関数はすべて、プール効果に対する予測区間を提供することができるが、デフォルトではない。メタ分析を実行する際には、予測区間が出力されるように <code>prediction = TRUE</code> という引数を追加する必要がある。</p>
<p>まとめると、メタ分析の異質性を特徴付ける際に、一つの指標だけに頼らないことが望ましいということである。少なくとも、常に <span class="math inline">\(I^2\)</span> (信頼区間付き) と予測区間を報告し、それに従って結果を解釈することが推奨される。</p>
<p><br></p>
</div>
<div id="het-R" class="section level2" number="5.3">
<h2>
<span class="header-section-number">5.3</span> <em>R</em> での異質性評価<a class="anchor" aria-label="anchor" href="#het-R"><i class="fas fa-link"></i></a>
</h2>
<hr>
<p>異質性指標について学んだことを、実際にどのように使うことができるかを見てみよう。例として、これまで使ってきた <code>m.gen</code> メタ分析オブジェクトの異質性をもう少し詳しく調べてみよう (このオブジェクトは Chapter <a href="pooling-es.html#pre-calculated-es">4.2.1</a> で生成した)。</p>
<p><code>metagen</code> オブジェクトのデフォルトの出力には予測区間が含まれていないため、まずこれを更新する必要がある。単純に <code>update.meta</code> 関数を使用し、<code>prediction</code> の区間を追加で出力するように指示する。</p>
<div class="sourceCode" id="cb188"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m.gen</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/meta/man/update.meta.html">update.meta</a></span><span class="op">(</span><span class="va">m.gen</span>, prediction <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<p>これで、結果を再確認することができる。</p>
<div class="sourceCode" id="cb189"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m.gen</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Review:     Third Wave Psychotherapies
## 
## [...]
## 
## Number of studies combined: k = 18
## 
##                         SMD            95%-CI    t  p-value
## Random effects model 0.5771 [ 0.3782; 0.7760] 6.12 &lt; 0.0001
## Prediction interval         [-0.0572; 1.2115]              
## 
## Quantifying heterogeneity:
##  tau^2 = 0.0820 [0.0295; 0.3533]; tau = 0.2863 [0.1717; 0.5944];
##  I^2 = 62.6% [37.9%; 77.5%]; H = 1.64 [1.27; 2.11]
## 
## Test of heterogeneity:
##      Q d.f. p-value
##  45.50   17  0.0002
## 
## Details on meta-analytical method:
## - Inverse variance method
## - Restricted maximum-likelihood estimator for tau^2
## - Q-profile method for confidence interval of tau^2 and tau
## - Hartung-Knapp adjustment for random effects model (df = 17)
## - Prediction interval based on t-distribution (df = 16)</code></pre>
<p>この出力では、前に定義したすべての異質性測定の結果が表示される。まず、<code>Quantifying heterogeneity</code> のセクションから始めよう。ここで、<span class="math inline">\(\tau^2=\)</span> 0.08であることがわかる。<span class="math inline">\(\tau^2\)</span> (0.03 - 0.35)の信頼区間はゼロを含まず、私たちのデータに何らかの研究間異質性が存在することを示している。 <span class="math inline">\(\tau\)</span> の値は 0.29 である。これは、真の効果量が、効果量の尺度 (ここでは、Hedges’ <span class="math inline">\(g\)</span>) で表される、<span class="math inline">\(SD=\)</span> 0.29 の推定標準偏差を有することを意味する。</p>
<p>2 行目を見ると、<span class="math inline">\(I^2=\)</span> 63%、<span class="math inline">\(H\)</span> (<span class="math inline">\(H^2\)</span> の平方根) は 1.64 であることがわかる。これは、データにおける変動の半分以上が、真の効果量の差から生じていると推定されることを意味している。Higgins and Thompson の「経験則」を用いると、この異質性の量は中程度から大きいと特徴づけることが可能である。</p>
<p>プール効果の直下に、予測区間が表示されている。これは、<span class="math inline">\(g=\)</span> -0.06 から 1.21 までの範囲である。これは、現在のエビデンスに基づいて、将来のいくつかの研究が負の治療効果を発見する可能性があることを意味する。しかし、この区間はかなり広く、非常に高い効果も可能であることを意味する。</p>
<p></p>
<p>最後に、<span class="math inline">\(Q\)</span> と <code>Test of heterogeneity</code> も提示されている。 <span class="math inline">\(Q\)</span> = 45.5 であることがわかる。これは、この分析の <span class="math inline">\(K-1=\)</span> 17 の自由度に基づいて期待されるものよりずっと多いものである。その結果、異質性検定は有意である (<span class="math inline">\(p&lt;\)</span> 0.001)。しかし、前に述べたように、<span class="math inline">\(Q\)</span> の欠陥が知られている以上、 この検定だけに基づいて評価を行うべきではない。</p>
<div class="boxreport">
<p>
<strong>メタアナリシスにおける異質性量の報告</strong>
</p>
<p>
この例における異質性の量をどのように報告する文章を例示する。
</p>
<blockquote>
<p>
<em>“The between-study heterogeneity variance was estimated at <span class="math inline"><span class="math inline">\(\hat\tau^2\)</span></span> = 0.08 (95%CI: 0.03-0.35),
with an <span class="math inline"><span class="math inline">\(I^2\)</span></span> value of 63% (95%CI:
38-78%). The prediction interval ranged from <span class="math inline"><span class="math inline">\(g\)</span></span> = -0.06 to 1.21, indicating that
negative intervention effects cannot be ruled out for future
studies.”</em>
</p>
</blockquote>
</div>
<p>では、これらの結果から何がわかるのだろうか。全体として、ここで示している指標は、中程度からかなりの異質性がデータに存在することを教えてくれる。このメタ分析における効果は完全な異質という訳ではないが、研究間の真の効果量には明らかに何らかの差がある。</p>
<p>したがって、この異質性の原因を探るのは良いアイデアだろう。効果量が大きく、実際には「当てはまらない」研究が 1 つまたは 2 つある可能性がある。これは、この分析における異質性を増大させ、さらに悪いことには、真の効果の<strong>過大評価</strong>につながった可能性がある。</p>
<p>一方、プールされた効果は、サンプルサイズが非常に大きい 1 つの研究が予想外に小さい効果量を報告したことに大きく影響されている可能性もある。これは、プール効果が治療の真の効果を<strong>過小評価</strong>していることを意味する可能性がある。</p>
<p>これらの懸念に対処するため、次に、プールした結果の頑健性を評価するための手続きを説明する。<strong>外れ値分析</strong>と<strong>影響度分析</strong>である。</p>
<p></p>

<div class="boxinfo">
<p><strong><span class="math inline">\(I^2\)</span> &gt; 50% “Guideline”</strong></p>
<p>研究間の異質性について、具体的にいつさらなる解析が必要かを決める鉄則はない。実際に使われることもあるアプローチは、<span class="math inline">\(I^2\)</span> が 50% より大きいときに外れ値や影響力のあるケースをチェックすることである。この閾値に達すると、少なくとも中程度の異質性があり、変動の (半分以上が) 真の効果量の差に起因していると仮定することができる。</p>
<p>この「経験則」は、やや恣意的なものであり、これまで述べてきた <span class="math inline">\(I^2\)</span> の問題を考えると、決して完全なものではない。しかし、メタ分析でプールされた効果のよりロバストなバージョンを得ようとするときに、<strong>a priori</strong> に一貫した方法で指定することができるので、実用的な観点から役に立つ。</p>
避けなければならないのは、結果が気に入ったからと言って、厳密な根拠もなく、外れ値や影響力のあるケースを削除することである。そのような結果は、たとえ意識的に「好ましい」方向に結果を曲げようとしなかったとしても、「研究者の意図」 (Chapter <a href="intro.html#pitfalls">1.3</a> 参照) によって大きバイアスになってしまう。
</div>
<p><br></p>
</div>
<div id="outliers" class="section level2" number="5.4">
<h2>
<span class="header-section-number">5.4</span> 外れ値と影響力のある事例<a class="anchor" aria-label="anchor" href="#outliers"><i class="fas fa-link"></i></a>
</h2>
<hr>
<p>
</p>
<p>前述したように、研究間の異質性は、効果量が極端に大きい 1 つまたは複数の研究によって引き起こされることがあり、それは全く「適合」しない。これはプールされた効果の推定値を歪める可能性があるため、そのような<strong>外れ値</strong>を分析から取り除いた後にプールされた効果を再検査することは良い考えである。</p>
<p>一方、私たちは、私たちが見つけたプール効果推定値が頑健であるかどうか、つまり、一つの研究に大きく依存しないかどうかも知りたいと思われる。したがって、私たちの分析の効果を一方向に大きく押し上げるような研究があるかどうかも知りたいのである。このような研究は、<strong>影響力のあるケース</strong>と呼ばれており、この章の後半でこのトピックに時間を割くことにしよう。</p>
<p><br></p>
<div id="basic-outlier" class="section level3" number="5.4.1">
<h3>
<span class="header-section-number">5.4.1</span> 基本的な外れ値除去<a class="anchor" aria-label="anchor" href="#basic-outlier"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p>ある研究の効果を「外れ値」と定義するには、いくつかの方法がある <span class="citation">(<a href="references.html#ref-viechtbauer2010outlier">Viechtbauer and Cheung 2010</a>)</span>。簡単で、やや「強引な」アプローチは、研究の信頼区間がプール効果の信頼区間と重ならない場合、その研究を外れ値とみなすことである。外れ値の効果量は、全体の効果量と著しく異なるほど<strong>極端</strong>である。このような外れ値を検出するために、すべての研究を検索することが可能である。</p>
<ul>
<li><p>95% 信頼区間の<strong>上限</strong>がプール効果信頼区間の<strong>下限</strong>より<strong>低い</strong>もの (すなわち、極端に<strong>小さい</strong>効果)。</p></li>
<li><p>95% 信頼区間の<strong>下限</strong>がプール効果信頼区間の<strong>上限</strong>より<strong>高い</strong>もの (すなわち、極めて<strong>大きい</strong>効果)。</p></li>
</ul>
<p>この方法の背景にある考え方は非常に単純である。サンプル誤差が大きい研究は、プール効果からかなり乖離することが予想される。しかし、そのような研究の信頼区間も大きくなるので、信頼区間がプールされた効果の信頼区間と重なる可能性が高くなる。</p>
<p>しかし、ある研究が<strong>低い</strong>標準誤差を持ち、<strong>それでも</strong> (予想外に) プール効果から大きく逸脱している場合、信頼区間が重ならず、その研究は外れ値として分類される可能性が高い。</p>
<p></p>
<p><strong>{dmetar}</strong> パッケージには <code>find.outliers</code> という関数があり、この単純な外れ値除去アルゴリズムが実装されている。これは、<strong>{meta}</strong> オブジェクトから外れ値のある研究を検索し、これらを削除して、結果を再計算する。</p>
<div class="boxdmetar">
<p>
<strong>“find.outliers” 関数</strong>
</p>
<p>
<code>find.outliers</code> 関数は、<strong>{dmetar}</strong>
パッケージに含まれている。<strong>{dmetar}</strong>
がインストールされ、コンピュータに読み込まれると、この関数を使用できるようになる。もし、<strong>{dmetar}</strong>
をインストールして<strong>いない</strong>場合は、以下の手順でインストールできる。
</p>
<ol style="list-style-type: decimal">
<li>
関数のソースコードにアクセスする <a href="https://raw.githubusercontent.com/MathiasHarrer/dmetar/master/R/power.analysis.subgroup.R">オンライン</a>.
</li>
<li>
ソースコード全体をコンソール (R Studio の左下ペイン)
にコピー＆ペーストし、Enterキーを押して、 <em>R</em>
に関数を「学習」させる。
</li>
<li>
<strong>{meta}</strong> と <strong>{metafor}</strong>
パッケージがインストールされ、ロードされていることを確認する。
</li>
</ol>
</div>
<p><code>find.outliers</code> 関数は、<strong>{meta}</strong> メタ分析関数によって生成されたオブジェクトを入力として必要とするだけである。それでは、<code>m.gen</code> オブジェクトに対してどのような結果が得られるか見てみよう。</p>
<div class="sourceCode" id="cb191"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="http://dmetar.protectlab.org/reference/find.outliers.html">find.outliers</a></span><span class="op">(</span><span class="va">m.gen</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Identified outliers (random-effects model) 
## ------------------------------------------ 
## "DanitzOrsillo", "Shapiro et al." 
##  
## Results with outliers removed 
## ----------------------------- 
## Number of studies combined: k = 16
## 
##                         SMD           95%-CI    t  p-value
## Random effects model 0.4528 [0.3257; 0.5800] 7.59 &lt; 0.0001
## Prediction interval         [0.1693; 0.7363]              
## 
## Quantifying heterogeneity:
##  tau^2 = 0.0139 [0.0000; 0.1032]; tau = 0.1180 [0.0000; 0.3213];
##  I^2 = 24.8% [0.0%; 58.7%]; H = 1.15 [1.00; 1.56]
## 
## Test of heterogeneity:
##      Q d.f. p-value
##  19.95   15  0.1739
## 
## [...]</code></pre>
<p></p>
<p><code>find.outliers</code> 関数が、“DanitzOrsillo” と “Shapiro et al.” という2つの外れ値を検出したことがわかる。また、この関数は、検出された研究を除外しながら、自動的に分析を再実行してきた。各研究のランダム効果重みを表示す列、<code>%W(random)</code> では、外れ値の研究の重みが0に設定され、分析から除外されていることがわかる。</p>
<p></p>
<p>出力に基づき、2つの研究が除外されると、<span class="math inline">\(I^2\)</span> 異質性がかなり縮小し、<span class="math inline">\(I^2=\)</span> 63% から 25% になることがわかる。 <span class="math inline">\(\tau^2\)</span> の信頼区間はゼロを含み、<span class="math inline">\(Q\)</span> -異質性の検定は有意ではなくなる。その結果、私たちの推定値の予測区間も狭くなっている。今、それは正の値だけを含み、将来の研究にわたるプールされた効果の頑健性をより確実なものにしている。</p>
<p><br></p>
</div>
<div id="influence-analysis" class="section level3" number="5.4.2">
<h3>
<span class="header-section-number">5.4.2</span> 影響力分析<a class="anchor" aria-label="anchor" href="#influence-analysis"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p></p>
<p>ここまでで、メタ分析における外れ値の検出と除去の基本的な方法を学んできた。しかし、プール効果の頑健性について懸念を引き起こすのは、極端な効果量だけではない。効果量が特に大きくなくても小さくても、全体の結果に非常に大きな影響力を及ぼす研究もある。</p>
<p>例えば、メタ分析で全体的な効果を発見しても、その有意性は1つの大きな研究に依存している可能性がある。これは、影響力のある研究を取り除くと、プールされた効果が統計的に有意でなくなることを意味している。このような情報は、私たちの結果がいかに頑健であるかを一般に伝えるために非常に重要である。</p>
<p>外れ値の研究と影響力のある研究とは、重複している部分もあるが、若干意味が異なる。外れ値は効果の大きさによって定義されるが、必ずしもメタ分析の結果に大きな影響を与える必要はない。外れ値を削除しても、平均効果量やデータの異質性が大きく変化しないことは十分にあり得る。</p>
<p>一方、影響力のある事例とは、効果の高低にかかわらず、定義上、プール効果や異質性に大きな影響を与える研究のことを指す。もちろん、効果量が極端に大きい研究が影響力のあるケースになりえないということではない。実際、前章の例で説明したように、外れ値も影響力があることが多い。しかし、必ずしもそうなる訳ではない。</p>
<p></p>
<p>影響力のある研究を特定するテクニックはいくつかあり、前回説明した基本的な外れ値除去よりも少し高度なものである。これらは <strong>leave-one-out</strong> 法に基づいている。このアプローチでは、メタ分析の結果を <span class="math inline">\(K\)</span> 回再計算し、毎回一つの研究を<strong>除外</strong> (leave out) する。</p>
<p>このデータに基づいて、さまざまな<strong>影響力診断</strong> (Influence Diagnosis) を計算することができる。影響力診断は、メタ分析の全体推定値に最も影響を与える研究を検出し、この大きな影響力がプール効果を歪めていないかどうかを評価することが可能である <span class="citation">(<a href="references.html#ref-viechtbauer2010outlier">Viechtbauer and Cheung 2010</a>)</span>。</p>
<p></p>
<p><strong>{dmetar}</strong> パッケージには <code>InfluenceAnalysis</code> という関数が含まれており、1つの関数でこれらの様々な影響力診断を計算することが可能である。この関数は、<strong>{meta}</strong> 関数で作成されたあらゆるタイプのメタ分析オブジェクトに使用することが可能である。</p>
<div class="boxdmetar">
<p>
<strong>“InfluenceAnalysis” 関数</strong>
</p>
<p>
<code>InfluenceAnalysis</code> 関数は、<strong>{dmetar}</strong>
パッケージに含まれている。<strong>{dmetar}</strong>
がインストールされ、コンピュータに読み込まれると、この関数を使用できるようになる。もし、<strong>{dmetar}</strong>
をインストールして<strong>いない</strong>場合は、以下の手順でインストールできる。
</p>
<ol style="list-style-type: decimal">
<li>
関数のソースコードにアクセスする <a href="https://raw.githubusercontent.com/MathiasHarrer/dmetar/master/R/power.analysis.subgroup.R">オンライン</a>.
</li>
<li>
ソースコード全体をコンソール (R Studio の左下ペイン)
にコピー＆ペーストし、Enterキーを押して、 <em>R</em>
に関数を「学習」させる。
</li>
<li>
<strong>{meta}</strong>、<strong>{metafor}</strong>、<strong>{ggplot2}</strong>、<strong>{gridExtra}</strong>
パッケージがインストールされ、ロードされていることを確認する。
</li>
</ol>
</div>
<p><code>InfluenceAnalysis</code> 関数の使用方法は比較的簡単である。影響度分析を行いたいメタ分析オブジェクトの名前を指定するだけである。ここでは、再び <code>m.gen</code> オブジェクトを使用しよう。</p>
<p><code>InfluenceAnalysis</code> はデフォルトで固定効果モデルを使用するので、<code>random = TRUE</code> を設定して、ランダム効果モデルが使用されるようにする必要がある。この関数は他の引数も取ることができ、主に関数が生成するプロットの種類を制御する。引数については、関数のドキュメントで詳しく説明されている。</p>
<p>関数の結果を <code>m.gen.inf</code> というオブジェクトに保存する。</p>
<div class="sourceCode" id="cb193"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m.gen.inf</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://dmetar.protectlab.org/reference/InfluenceAnalysis.html">InfluenceAnalysis</a></span><span class="op">(</span><span class="va">m.gen</span>, random <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<p><code>InfluenceAnalysis</code> 関数は、<strong>Baujat</strong>プロット、Viechtbauer and Cheung <span class="citation">(<a href="references.html#ref-viechtbauer2010outlier">2010</a>)</span> による<strong>影響力診断</strong>、効果量と <span class="math inline">\(I^2\)</span> 値でソートされた leave-one out メタ分析結果という4つの影響診断プロットを作成する。これらのプロットはそれぞれ <code>plot</code> 関数で個別に開くことが可能である。それでは、順を追って見ていこう。</p>
<p><br></p>
<div id="baujat" class="section level4" number="5.4.2.1">
<h4>
<span class="header-section-number">5.4.2.1</span> Baujat プロット<a class="anchor" aria-label="anchor" href="#baujat"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p>Baujat プロットは <code>plot</code> 関数を用いて、第2引数に <code>"baujat"</code> を指定することで表示できる。</p>
<div class="sourceCode" id="cb194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">m.gen.inf</span>, <span class="st">"baujat"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="images/baujat_col_sep.png" width="70%" style="display: block; margin: auto;"></div>
<p>Baujat plots <span class="citation">(<a href="references.html#ref-baujat2002graphical">Baujat et al. 2002</a>)</span> は、メタ分析における異質性に過度に寄与している研究を検出するための診断プロットである。<strong>横</strong>軸に全体の<strong>異質性</strong> (Cochran’s <span class="math inline">\(Q\)</span> で測定) に対する各研究の寄与を、<strong>縦</strong>軸に<strong>プール効果量</strong>に対するその<strong>影響</strong>を示している。</p>
<p>この「影響力」の値は、leave-one-out 法により決定され、その研究がメタ分析に含まれる場合と含まれない場合の全体効果の標準化された差を表している。</p>
<p>プロットの右側にある研究は、私たちのメタ分析における全体的な異質性に大きく寄与しているので、潜在的に関連するケースと見なすことが可能である。プロットの右上にある研究は、推定された異質性とプールされた効果の両方に大きな影響を与えるので、特に影響力があると思われる。</p>
<p>プロットの右側にある2つの研究は、以前すでに検出したものである (“DanitzOrsillo” と “Shapiro et al.”)。この二つの研究は全体の結果に大きな影響を与えないが (サンプルサイズが小さいためと思われる)、メタ分析で見られる異質性に大きな影響を及ぼしている。</p>
<p><br></p>
</div>
<div id="inf-diags" class="section level4" number="5.4.2.2">
<h4>
<span class="header-section-number">5.4.2.2</span> 影響力診断<a class="anchor" aria-label="anchor" href="#inf-diags"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p>次のプロットは、各研究のいくつかの影響力診断 (Influence Diagnostics) を含んでいる。これらは、このコードを使ってプロットすることが可能である。</p>
<div class="sourceCode" id="cb195"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">m.gen.inf</span>, <span class="st">"influence"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="images/influence_col_sep.png" width="70%" style="display: block; margin: auto;"></div>
<p>このプロットは、各研究について、さまざまな影響力の値を表示していることがわかる。これらの尺度は、どの研究がメタ分析モデルにうまく適合して、どの研究が適合しないかを特徴づけるために使用される。診断の意味を理解するために、左から右、上から下へと簡単に見ていこう。</p>
<p><br></p>
<div id="外部標準化残差" class="section level5" number="5.4.2.2.1">
<h5>
<span class="header-section-number">5.4.2.2.1</span> 外部標準化残差<a class="anchor" aria-label="anchor" href="#%E5%A4%96%E9%83%A8%E6%A8%99%E6%BA%96%E5%8C%96%E6%AE%8B%E5%B7%AE"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p></p>
<p>最初のプロットは、各研究の外部標準化残差を表示している。名前にあるように、残差は、観察された各効果量 <span class="math inline">\(\hat\theta_k\)</span> のプール効果量からの偏差を表している。残差は標準化されており、偏差を計算するために、研究を含まないプールされた効果の「外部」推定値を使用する。</p>
<p>「外部」プール効果 <span class="math inline">\(\hat\mu_{\setminus k}\)</span> は、leave-one-out 法の原則に従って、研究 <span class="math inline">\(k\)</span> を除いた全体効果を計算することによって得られる。そして、得られた残差は、(1) 外部効果の<strong>分散</strong> (すなわち、<span class="math inline">\(\hat\mu_{\setminus k}\)</span> の標準誤差の2乗)、(2) 外部プール効果の推定値 <span class="math inline">\(\tau^2\)</span>、および (3) <span class="math inline">\(k\)</span> の分散によって標準化される。</p>
<p><span class="math display" id="eq:het8">\[\begin{equation}
t_{k} = \frac{\hat\theta_{k}-\hat\mu_{\setminus k}}{\sqrt{\mathrm{Var}(\hat\mu_{\setminus k})+\hat\tau^2_{\setminus k}+s^2_k}}
\tag{5.8}
\end{equation}\]</span></p>
<p></p>
<p>研究 <span class="math inline">\(k\)</span> がメタ分析にうまく適合すると仮定すると、分母の3つの項は、効果量が平均効果量からどれくらい異なるかを決定する変動源を捕捉した。これらの変動要因は、<span class="math inline">\(k\)</span> のサンプルエラー、真の効果量の分散、およびプール効果量の推定値の不正確さである。</p>
<p>もし研究が全体の母集団に<strong>合わない</strong>ならば、残差は3つの分散項だけから予想されるよりも<strong>大きくなる</strong>と仮定可能である。これは、<span class="math inline">\(t_k\)</span> の値を高くし、その研究が「適合しない」影響力のあるケースであることを示している。</p>
<p><br></p>
</div>
<div id="mathrmdffits-値" class="section level5" number="5.4.2.2.2">
<h5>
<span class="header-section-number">5.4.2.2.2</span> <span class="math inline">\(\mathrm{DFFITS}\)</span> 値<a class="anchor" aria-label="anchor" href="#mathrmdffits-%E5%80%A4"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p><span class="math inline">\(\mathrm{DFFITS}\)</span> 量の計算は、外部標準化残差の計算と同様である。したがって、DFFITSと <span class="math inline">\(t_k\)</span> の値のパターンは、多くの場合、研究間で比較可能である。これが計算式である。</p>
<p><span class="math display">\[\begin{equation}
\mathrm{DFFITS}_k =  \dfrac{\hat\mu-\hat\mu_{\setminus k}}{\sqrt{\dfrac{w_k^{(*)}}{\sum^{K}_{k=1}w_k^{(*)}}(s^2_k+\hat\tau^2_{\setminus k})}}
\end{equation}\]</span></p>
<p>計算には、研究 <span class="math inline">\(k\)</span> ( Chapter <a href="pooling-es.html#fem">4.1.1</a> ) の (ランダム効果) 重みである <span class="math inline">\(w_k^{(*)}\)</span> も必要で、これを重みの合計で割って研究の重みをパーセントで表現することになる。</p>
<p>一般に、<span class="math inline">\(\mathrm{DFFITS}\)</span> の値は、ある研究 ( <span class="math inline">\(k\)</span> ) を削除したときに、プールされた効果がどの程度変化するかを示し、標準偏差で表される。ここでも、値が高いほど、平均効果への影響が大きいので、その研究が影響力のあるケースである可能性を示している。</p>
<p><br></p>
</div>
<div id="cook-距離" class="section level5" number="5.4.2.2.3">
<h5>
<span class="header-section-number">5.4.2.2.3</span> Cook 距離<a class="anchor" aria-label="anchor" href="#cook-%E8%B7%9D%E9%9B%A2"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p></p>
<p>ある研究の Cook 距離 <span class="math inline">\(D_k\)</span> は、<span class="math inline">\(\mathrm{DFFITS}\)</span> の値と非常によく似た式で計算できる。最大の違いは、<span class="math inline">\(D_k\)</span> の場合、<span class="math inline">\(k\)</span> の有無によるプール効果の差は<strong>2乗</strong>になることである。</p>
<p>この結果、<span class="math inline">\(D_k\)</span> は正の値のみをとることになる。しかし、研究間のパターンは、<span class="math inline">\(\mathrm{DFFITS}\)</span> の値と似ていることが多い。以下は式である。</p>
<p><span class="math display" id="eq:het9">\[\begin{equation}
D_k =  \frac{(\hat\mu-\hat\mu_{\setminus k})^2}{\sqrt{s^2_k+\hat\tau^2}}.
\tag{5.9}
\end{equation}\]</span></p>
<p><br></p>
</div>
<div id="共分散比" class="section level5" number="5.4.2.2.4">
<h5>
<span class="header-section-number">5.4.2.2.4</span> 共分散比<a class="anchor" aria-label="anchor" href="#%E5%85%B1%E5%88%86%E6%95%A3%E6%AF%94"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p>研究 <span class="math inline">\(k\)</span> の共分散比は、<span class="math inline">\(k\)</span> のないプール効果の分散 (すなわち、その二乗標準誤差) を初期平均効果の分散で割ることによって算出することが可能である。</p>
<p><span class="math display" id="eq:het10">\[\begin{equation}
\mathrm{CovRatio}_k = \frac{\mathrm{Var}(\hat\mu_{\setminus k})}{\mathrm{Var}(\hat\mu)}
\tag{5.10}
\end{equation}\]</span></p>
<p><span class="math inline">\(\mathrm{CovRatio}_k\)</span> が 1 以下の値は、研究 <span class="math inline">\(k\)</span> を削除することで、プール効果量 <span class="math inline">\(\hat\mu\)</span> のより正確な推定値が得られることを示す。</p>
<p><br></p>
</div>
<div id="leave-one-out-tau2-値と-q-値" class="section level5" number="5.4.2.2.5">
<h5>
<span class="header-section-number">5.4.2.2.5</span> Leave-One-Out <span class="math inline">\(\tau^2\)</span> 値と <span class="math inline">\(Q\)</span> 値<a class="anchor" aria-label="anchor" href="#leave-one-out-tau2-%E5%80%A4%E3%81%A8-q-%E5%80%A4"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p></p>
<p>この行の値は非常に簡単に解釈可能である。これらは単に、<span class="math inline">\(\tau^2\)</span> と Cochran’s <span class="math inline">\(Q\)</span>、研究 <span class="math inline">\(k\)</span> を削除した場合に測定される推定異質性を表示しているだけである。 <span class="math inline">\(Q\)</span> 値と <span class="math inline">\(\tau^2\)</span> 値、特に後者の値が低いほど異質性が低いことを意味するので、望ましい。</p>
<p><br></p>
</div>
<div id="ハット値と研究の重み" class="section level5" number="5.4.2.2.6">
<h5>
<span class="header-section-number">5.4.2.2.6</span> ハット値と研究の重み<a class="anchor" aria-label="anchor" href="#%E3%83%8F%E3%83%83%E3%83%88%E5%80%A4%E3%81%A8%E7%A0%94%E7%A9%B6%E3%81%AE%E9%87%8D%E3%81%BF"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p>最後の行には、各研究の重みとハット値が表示されている。研究重みの計算と意味については、すでに Chapter <a href="pooling-es.html#fem">4.1.1</a> で詳しく説明したので、この指標についてはこれ以上説明する必要はないだろう。一方、ハット値とは、研究の重みと等価な別の指標に過ぎない。したがって、影響力分析では、ハット値と重みのパターンは同一になる。</p>
<p>これらの指標はすべて、極端な場合、その研究が影響力のあるケースであることを示し、プールした結果の頑健性に悪影響を及ぼす可能性のある値を示している。しかし、このポイントに到達するタイミングはあまり明確ではない。<span class="math inline">\(\mathrm{DFFITS}\)</span>、Cook 距離または標準化残差値が高<strong>すぎる</strong>という厳密なルールはない。研究を削除することが適切かどうかを判断するために、研究課題の文脈で影響度分析の結果を評価することが常に必要である。</p>
<p>しかし、私たちの判断の指針となる「経験則」がいくつかある。<code>InfluenceAnalysis</code> 関数は、以下の条件のいずれかを満たす場合、その研究を影響力のあるケースとみなす<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;これらの条件は、&lt;strong&gt;{metafor}&lt;/strong&gt; の[&lt;code&gt;influence.rma.uni&lt;/code&gt;] (&lt;a href="https://www.rdocumentation.org/packages/metafor/versions/2.4-0/topics/influence.rma.uni" class="uri"&gt;https://www.rdocumentation.org/packages/metafor/versions/2.4-0/topics/influence.rma.uni&lt;/a&gt;) 関数が使用している「親指のルール」から派生している。&lt;code&gt;InfluenceAnalysis&lt;/code&gt; はこの関数を「隠れて」適用する&lt;/p&gt;'><sup>29</sup></a>:</p>
<p><span class="math display" id="eq:het11">\[\begin{equation}
\mathrm{DFFITS}_k &gt; 3\sqrt{\frac{1}{k-1}}
\tag{5.11}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:het12">\[\begin{equation}
D_k &gt; 0.45
\tag{5.12}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:het13">\[\begin{equation}
\mathrm{hat_k} &gt; 3\frac{1}{k}.
\tag{5.13}
\end{equation}\]</span></p>
<p>影響力があると判断された研究は、 <code>InfluenceAnalysis</code> 機能で生成されたプロットで赤色で表示される。</p>
<p>この例では、“DanitzOrsillo” 研究である “Dan” の場合のみ、こうなる。しかし、この研究だけが影響力があると定義されたが、実際にはほとんどのプロットで<strong>2</strong>個のスパイクが存在した。また、“Sha” (Shapiro et al.) の値も非常に極端なので、影響力のあるケースとして定義することが可能である。</p>
<p>そこで、“DanitzOrsillo” と”Shapiro et al.” の研究が影響力を持つ可能性があることがわかる。これは、Baujat プロットに基づき、統計的外れ値だけを見たときに、同じ研究を選択したため、興味深い発見である。</p>
<p>このことは、この2つの研究がプールされた効果推定値を歪め、最初のメタ分析で見出された研究間異質性の一部を引き起こしている可能性をさらに裏付けるものである。</p>
<p><br></p>
</div>
</div>
<div id="loo-ma" class="section level4" number="5.4.2.3">
<h4>
<span class="header-section-number">5.4.2.3</span> Leave-One-Out メタ分析結果<a class="anchor" aria-label="anchor" href="#loo-ma"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p>
</p>
<p>最後に、leave-one-out 法を用いて実施されたすべてのメタ分析の全体効果および <span class="math inline">\(I^2\)</span> 異質性をプロットすることも可能である。1つはプール効果量、もう1つは leave-one-out メタ分析の <span class="math inline">\(I^2\)</span> 値でソートされた2つの<strong>フォレストプロット</strong> ( Chapter <a href="forest.html#forest-R">6.2</a> でもっと詳しく知ることになるプロットのタイプ) を表示すことが可能である。プロットを作成するコードは次のようなものである。</p>
<div class="sourceCode" id="cb196"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">m.gen.inf</span>, <span class="st">"es"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">m.gen.inf</span>, <span class="st">"i2"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="images/forestesi2_col_sep.png" width="100%" style="display: block; margin: auto;"></div>
<p>これらの2つのフォレストプロットでは、毎回1つの研究を省略して再計算されたプール効果を見ることが可能である。両方のプロットで、中央に破線のある陰影のある領域がある。これは、元のプール効果量の95%信頼区間と推定されたプール効果そのものを表している。</p>
<p>最初のプロットは、効果量 (低から高) 順に並べたものである。ここでは、異なる研究を削除したときに、全体の効果推定値がどのように変化するかを見ている。“DanitzOrsillo”と “Shapiro et al.” の2つの研究は、非常に高い効果量を持っているので、それらを取り除くと、全体の効果量が最も小さくなることがわかる。</p>
<p>2番目のプロットは、<span class="math inline">\(I^2\)</span> で測定された異質性 (低から高) 順に並んでいる。このプロットは、“DanitzOrsillo” と “Shapiro et al.” の研究を除外すると、<span class="math inline">\(I^2\)</span> 異質性が最も低くなることを示している。これは、この2つの研究がメタ分析で見られた研究間の異質性の主な「犯人」であるという私たちの発見を裏付けるものである。</p>
<p>全体として、この例の外れ値解析と影響力解析の結果は同じ方向を向いている。影響力のある外れ値であると思われる研究が2つある。この2つの研究は、効果量の推定値だけでなく、その精度も歪めてしまうだろう。したがって、この2つの研究を除外した感度分析の結果も実施し、報告する必要がある。</p>
<p><br></p>
</div>
</div>
<div id="gosh" class="section level3" number="5.4.3">
<h3>
<span class="header-section-number">5.4.3</span> GOSH プロット解析<a class="anchor" aria-label="anchor" href="#gosh"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p>前章では、leave-one-out 法に基づく影響度分析を用いて、メタ分析の頑健性を探ってみた。データ中の異質性のパターンを探るもう一つの方法は、いわゆる <strong>Graphic Display of Heterogeneity</strong> (GOSH) プロットである <span class="citation">(<a href="references.html#ref-olkin2012gosh">Olkin, Dahabreh, and Trikalinos 2012</a>)</span>。これらのプロットでは、含まれる研究の<strong>すべての可能なサブセット</strong>に、同じメタ分析モデルを当てはめる。leave-one-out 法とは対照的に、<span class="math inline">\(K\)</span> モデルだけでなく、<span class="math inline">\(2^{k-1}\)</span> 対の可能なすべての研究の組み合わせに対してモデルを当てはめる。</p>
<p>これは、研究の総数が多い場合、GOSH プロットの作成にかなりの計算量がかかることを意味した。そのため、ここで取り上げる <em>R</em> の実装は、最大100万件のランダム化されたモデルしか適合させない。</p>
<p>モデルが計算されると、X軸にプール効果量、Y軸に研究間の異質性を表示し、プロットすることが可能である。これにより、例えば、効果量や異質性の量が異なるクラスターなど、特定のパターンを探すことが可能である。</p>
<p>GOSH プロットにいくつかの異なるクラスタがある場合、データ中に複数の効果量の「集団」が存在する可能性を示し、サブグループ解析を正当化する。一方、サンプル中の効果量が均質である場合、GOSHプロットは、ほぼ対称的で均質な分布を示す。</p>
<p></p>
<p>GOSH プロットを生成するには、<strong>{metafor}</strong> パッケージの <code>gosh</code> 関数を使用することが可能である。まだパッケージをインストールしていない場合は、今すぐインストールし、ライブラリからロードしてみよう。</p>
<div class="sourceCode" id="cb197"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.metafor-project.org">metafor</a></span><span class="op">)</span></span></code></pre></div>
<p>メタ分析オブジェクト <code>m.gen</code> に対して、GOSH プロットを生成してみよう。そのためには、まず、<strong>{meta}</strong> パッケージによって作成されたこのオブジェクトを、<strong>{metafor}</strong> メタ分析オブジェクトに「変換 」する必要がある。</p>
<p><strong>{metafor}</strong> でメタ分析を行うために使用する関数は <code>rma</code> と呼ばれる。<strong>{meta}</strong> オブジェクトを <code>rma</code> メタ分析に変換するのはそれほど複雑なことではない。効果量 ( <code>TE</code> )、標準誤差 (<code>seTE</code>)、試験間異質性推定量 (<code>method.tau</code>) を <code>m.gen</code> に格納してこの関数に提供するだけである。引数 <code>test = "knha"</code> を指定することで、Knapp-Hartung 調整を使用するように指定することが可能である。</p>
<p>新しく生成された <strong>{metafor}</strong> ベースのメタ分析を <code>m.rma</code> という名前で保存する。</p>
<div class="sourceCode" id="cb198"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m.rma</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">m.gen</span><span class="op">$</span><span class="va">TE</span>,</span>
<span>             sei <span class="op">=</span> <span class="va">m.gen</span><span class="op">$</span><span class="va">seTE</span>,</span>
<span>             method <span class="op">=</span> <span class="va">m.gen</span><span class="op">$</span><span class="va">method.tau</span>,</span>
<span>             test <span class="op">=</span> <span class="st">"knha"</span><span class="op">)</span></span></code></pre></div>
<p><strong>{meta}</strong> で固定効果モデルを使用した場合、 <code>method.tau</code> を <code>rma</code> の呼び出しに単純にコピーすることはできないことに注意してみよう。代わりに、 <code>rma</code> の <code>method</code> 引数を <code>"FE"</code> に設定する必要がある。</p>
<p>そして、 <code>m.rma</code> オブジェクトを使用して、GOSH プロットを生成することが可能である。解析の研究数にもよるが、これにはある程度の時間、最大で数時間かかることがある。その結果を <code>res.gosh</code> として保存する。</p>
<div class="sourceCode" id="cb199"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">res.gosh</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/gosh.html">gosh</a></span><span class="op">(</span><span class="va">m.rma</span><span class="op">)</span></span></code></pre></div>
<p>そして、 <code>res.gosh</code> オブジェクトを <code>plot</code> 関数に代入することでプロットを表示すことが可能である。追加の <code>alpha</code> 引数は、グラフ内のドットがどの程度透明であるかを制御する。グラフにはたくさんのデータポイントがあるので、値が「積み重なる」場所を明確にするために小さなアルファ値を使用することは理にかなっている。</p>
<div class="sourceCode" id="cb200"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res.gosh</span>, alpha <span class="op">=</span> <span class="fl">0.01</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="images/gosh0_sep.png" width="50%" style="display: block; margin: auto;"></div>
<p>データには興味深いパターンが見られる。ほとんどの値が比較的高い効果と高い異質性を持つクラスターに集中している一方で、<span class="math inline">\(I^2\)</span> の値の分布は大きく右肩下がりの二峰性になっている。推定された異質性がかなり低く、プール効果量も小さい研究の組み合わせがあるようで、結果として「彗星のような」尾を持つ形状になっている。</p>
<p>
</p>
<p>効果量 <span class="math inline">\(-\)</span> 異質性のパターンを見て、本当に重要な質問は、どの研究がこの形状を引き起こすのか、ということである。この質問に答えるために、 <code>gosh.diagnostics</code> 関数を使用することが可能である。</p>
<p>この機能は、3つのクラスタリングまたは<strong>教師なし機械学習</strong>アルゴリズムを用いて、GOSH プロットデータからクラスタを検出する。特定されたクラスタに基づいて、この関数は自動的にどの研究が各クラスタに最も貢献しているかを決定する。例えば、異質性の高いクラスターに1つまたは複数の研究が過剰に存在することが分かった場合、これらの研究は単独または組み合わせで、高い異質性の<strong>原因</strong>である可能性があることを示す。</p>
<div class="boxdmetar">
<p>
<strong>“gosh.diagnostics” 関数</strong>
</p>
<p>
<code>gosh.diagnostics</code> 関数は、<strong>{dmetar}</strong>
パッケージに含まれている。<strong>{dmetar}</strong>
がインストールされ、コンピュータに読み込まれると、この関数を使用できるようになる。もし、<strong>{dmetar}</strong>
をインストールして<strong>いない</strong>場合は、以下の手順でインストールできる。
</p>
<ol style="list-style-type: decimal">
<li>
関数のソースコードにアクセスする <a href="https://raw.githubusercontent.com/MathiasHarrer/dmetar/master/R/power.analysis.subgroup.R">オンライン</a>.
</li>
<li>
ソースコード全体をコンソール (R Studio の左下ペイン)
にコピー＆ペーストし、Enterキーを押して、 <em>R</em>
に関数を「学習」させる。
</li>
<li>
<strong>{gridExtra}</strong>, <strong>{ggplot2}</strong>,
<strong>{fpc}</strong>, <strong>{mclust}</strong>
パッケージがインストールされ、ロードされていることを確認する。
</li>
</ol>
</div>
<p>
</p>
<p><code>gosh.diagnostics</code> 関数は、<span class="math inline">\(k\)</span>-平均アルゴリズム <span class="citation">(<a href="references.html#ref-hartigan1979algorithm">Hartigan and Wong 1979</a>)</span>、<strong>密度到達性・接続性クラスタリング</strong> (density reachability and connectivity clustering)、あるいは DBSCAN <span class="citation">(<a href="references.html#ref-schubert2017dbscan">Schubert et al. 2017</a>)</span> および <strong>ガウス混合モデル</strong> (gaussian mixture models) <span class="citation">(<a href="references.html#ref-fraley2002model">Fraley and Raftery 2002</a>)</span> という3種類のクラスタアルゴリズムを使用してデータのパターンを検出している。</p>
<p>これらのアルゴリズムのパラメータのいくつかを調整することが可能である。<code>km.params</code>、 <code>db.params</code>、<code>gmm.params</code> の引数に、各アルゴリズムの挙動を制御する仕様を記述したリスト要素を追加することができる。この例では、<span class="math inline">\(k\)</span>-means と DBSCAN アルゴリズムの細部を少し調整する。 <span class="math inline">\(k\)</span> -平均アルゴリズムは、データ中の2つのクラスタ (「中心」) を探索するよう指定する。<code>db.params</code> では、DBSCAN が使用する <code>eps</code>、つまり <span class="math inline">\(\epsilon\)</span> の値を変更する。また、各クラスタに必要な最小限のポイント数を決定する <code>MinPts</code> 値も指定する。</p>
<p>アルゴリズムのパラメータについては、<code>gosh.diagnostics</code> のドキュメントで詳しく説明されている。どのようなパラメータ指定が最適なのか明確なルールはないので、各アルゴリズムの詳細を何度か試してみて、それが結果にどのような影響を与えるかを確認するとよいだろう。</p>
<p><code>gosh.diagnostics</code> を呼び出すコードは次のようになる。(訳注: 数分かかることがある。)</p>
<div class="sourceCode" id="cb201"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">res.gosh.diag</span> <span class="op">&lt;-</span> <span class="fu"><a href="http://dmetar.protectlab.org/reference/gosh.diagnostics.html">gosh.diagnostics</a></span><span class="op">(</span><span class="va">res.gosh</span>, </span>
<span>                                  km.params <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>centers <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>,</span>
<span>                                  db.params <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>eps <span class="op">=</span> <span class="fl">0.08</span>, </span>
<span>                                                   MinPts <span class="op">=</span> <span class="fl">50</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">res.gosh.diag</span></span></code></pre></div>
<pre><code>## GOSH Diagnostics 
## ================================ 
## 
##  - Number of K-means clusters detected: 2
##  - Number of DBSCAN clusters detected: 4
##  - Number of GMM clusters detected: 7
## 
##  Identification of potential outliers 
##  --------------------------------- 
## 
##  - K-means: Study 3, Study 16
##  - DBSCAN: Study 3, Study 4, Study 16
##  - Gaussian Mixture Model: Study 3, Study 4, Study 11, Study 16</code></pre>
<p>出力には、各アルゴリズムが検出したクラスタの数が表示される。各アプローチは異なる数学的戦略でデータを分割しているので、クラスタ数が同じでないのは当然である。</p>
<p><code>Identification of potential outliers</code> では、この手順により、クラスタの構成に大きな影響を与える3つの研究 (研究3、研究4、研究16) を特定できたことがわかる。</p>
<p>また、 <code>gosh.diagnostics</code> オブジェクトをプロットして、結果をもう少し詳しく調べることも可能である。</p>
<div class="sourceCode" id="cb203"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">res.gosh.diag</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="images/gosh1_col_sep.png" width="100%" style="display: block; margin: auto;"></div>
<div class="inline-figure"><img src="images/gosh2_col_sep.png" width="80%" style="display: block; margin: auto;"></div>
<p></p>
<p>これは、いくつかのプロットを生成した。最初の3つのプロットは、各アルゴリズムによって見つかったクラスタリングソリューションと、各クラスタ内の各研究に関連するクラスタインバランスの量を表している。この情報に基づいて、Cook 距離が各研究について計算され、これは、ある研究が検出されたクラスタに大きな影響を与えるかどうか (したがって、影響力のあるケースであるかもしれない) を判断するために使用される。</p>
<p>他のプロットも GOSH プロットであるが、選択された研究が含まれる解析を表す陰影のついたポイントが表示された。例えば、研究 3 が含まれるほぼすべての結果は、高い異質性の値と高い効果量を持つクラスタに属していることがわかる。研究 4 が含まれる結果は、異質性にばらつきがあるが、一般的に平均効果がやや<strong>小さい</strong>ことがわかる。研究16の結果は、研究 3 の結果と似ているが、もう少し分散している。</p>
<p><code>gosh.diagnostics</code> 関数が特定した3つの研究を削除して、メタ分析を再実行するとどうなるかを見てみよう。</p>
<div class="sourceCode" id="cb204"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/meta/man/update.meta.html">update.meta</a></span><span class="op">(</span><span class="va">m.gen</span>, exclude <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">16</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Review:     Third Wave Psychotherapies
##                           SMD            95%-CI %W(random) exclude
## Call et al.            0.7091 [ 0.1979; 1.2203]        4.6        
## Cavanagh et al.        0.3549 [-0.0300; 0.7397]        8.1        
## DanitzOrsillo          1.7912 [ 1.1139; 2.4685]        0.0       *
## de Vibe et al.         0.1825 [-0.0484; 0.4133]        0.0       *
## Frazier et al.         0.4219 [ 0.1380; 0.7057]       14.8        
## Frogeli et al.         0.6300 [ 0.2458; 1.0142]        8.1        
## Gallego et al.         0.7249 [ 0.2846; 1.1652]        6.2        
## Hazlett-Stevens &amp; Oren 0.5287 [ 0.1162; 0.9412]        7.0        
## Hintz et al.           0.2840 [-0.0453; 0.6133]       11.0        
## Kang et al.            1.2751 [ 0.6142; 1.9360]        2.7        
## Kuhlmann et al.        0.1036 [-0.2781; 0.4853]        8.2        
## Lever Taylor et al.    0.3884 [-0.0639; 0.8407]        5.8        
## Phang et al.           0.5407 [ 0.0619; 1.0196]        5.2        
## Rasanen et al.         0.4262 [-0.0794; 0.9317]        4.7        
## Ratanasiripong         0.5154 [-0.1731; 1.2039]        2.5        
## Shapiro et al.         1.4797 [ 0.8618; 2.0977]        0.0       *
## Song &amp; Lindquist       0.6126 [ 0.1683; 1.0569]        6.1        
## Warnecke et al.        0.6000 [ 0.1120; 1.0880]        5.0        
## 
## Number of studies combined: k = 15
## 
##                         SMD           95%-CI    t  p-value
## Random effects model 0.4819 [0.3595; 0.6043] 8.44 &lt; 0.0001
## Prediction interval         [0.3586; 0.6053]              
## 
## Quantifying heterogeneity:
##  tau^2 &lt; 0.0001 [0.0000; 0.0955]; tau = 0.0012 [0.0000; 0.3091];
##  I^2 = 4.6% [0.0%; 55.7%]; H = 1.02 [1.00; 1.50]
## 
## Test of heterogeneity:
##      Q d.f. p-value
##  14.67   14  0.4011
## [...]</code></pre>
<p></p>
<p>3 番と 16 番の研究が “DanitzOrsillo” と “Shapiro et al.” であることがわかる。この2つの研究は、以前の分析でも影響力があることが分かっている。研究番号 4 は “de Vibe” によるものである。この研究は、特に極端な効果量ではないが、観察された効果量が平均より小さいにもかかわらず、信頼区間が狭いことから、<strong>高い重み</strong>を持つことがわかる。このことは、この研究が影響力を持つ理由を説明できるだろう。</p>
<p>この3つの研究を取り除くと、推定される異質性に大きな影響を与えることがわかる。<span class="math inline">\(\tau^2\)</span> の値はほぼゼロになり、<span class="math inline">\(I^2\)</span> の値も非常に低く、効果量の変動の 4.6% のみが真の効果量の差によるものであることを示している。プール効果 <span class="math inline">\(g\)</span> = 0.48 は、最初の推定値 <span class="math inline">\(g=\)</span> 0.58 よりは小さいが、それでも同じ桁の範囲内である。</p>
<p>全体として、最初に計算した平均的な効果は、外れ値や影響力のある研究によって、<strong>あまり</strong>大きくバイアスされてはいないことを示している。</p>

<div class="boxreport">
<p><strong>影響力解析の結果を報告</strong></p>
<p>“DanitzOrsillo”, “de Vibe et al.”, “Shapiro et al.” がメタアナリシスで影響力のある研究だと判断されたとする。この場合、これらの研究を除外した感度解析の結果も報告するべきである。</p>
<p>影響力のある研究を削除した場合の変化を読者にわかりやすくするために、元の結果と感度分析の結果の両方を表示した表を作成することができる。この表には、少なくともプール効果、その信頼区間、<span class="math inline">\(p\)</span> 値、そして予測区間や <span class="math inline">\(I^2\)</span> 統計量 (およびその信頼区間) のような異質性のいくつかの尺度を含める必要がある。</p>
<p>また、どの研究が影響力のあるケースとして削除されたかを明記し、新しい結果がどのデータに基づいているのかを他の人が理解できるようにすることも重要である。以下は、以前行った <code>m.gen</code> メタアナリシスにおいて作成した表の一例である。</p>
<p><font size="2"></font></p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="45%">
<col width="7%">
<col width="11%">
<col width="8%">
<col width="13%">
<col width="7%">
<col width="7%">
</colgroup>
<thead><tr class="header">
<th>Analysis</th>
<th><span class="math inline">\(g\)</span></th>
<th>95%CI</th>
<th><span class="math inline">\(p\)</span></th>
<th>95%PI</th>
<th><span class="math inline">\(I^2\)</span></th>
<th>95%CI</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Main Analysis</td>
<td>0.58</td>
<td>0.38-0.78</td>
<td>&lt;0.001</td>
<td>-0.06-1.22</td>
<td>63%</td>
<td>39-78</td>
</tr>
<tr class="even">
<td>Infl. Cases Removed<sup>1</sup>
</td>
<td>0.48</td>
<td>0.36-0.60</td>
<td>&lt;0.001</td>
<td>0.36-0.61</td>
<td>5%</td>
<td>0-56</td>
</tr>
</tbody>
</table></div>
<p><sup>1</sup>Removed as outliers: DanitzOrsillo, de Vibe, Shapiro.</p>
<p></p>
<p>このような表は、他の感度解析の結果をさらに行に追加することができ、非常に便利である。例えば、バイアスリスクの低い研究 (Chapter <a href="intro.html#data-extraction">1.4.5</a>) のみを考慮した分析を行った場合、その結果を3行目に報告することができる。</p>
</div>
<p><span class="math display">\[\tag*{$\blacksquare$}\]</span></p>
<p><br></p>
</div>
</div>
<div id="演習問題-4" class="section level2" number="5.5">
<h2>
<span class="header-section-number">5.5</span> 演習問題<a class="anchor" aria-label="anchor" href="#%E6%BC%94%E7%BF%92%E5%95%8F%E9%A1%8C-4"><i class="fas fa-link"></i></a>
</h2>
<div class="boxquestion">
<p>
<strong>知識を試そう！</strong>
</p>
<ol style="list-style-type: decimal">
<li>
なぜメタ分析の研究間異質性を調べることが重要なのか。
</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>
異質性の2つのタイプを挙げられるか？メタ分析の計算にはどちらが関係するか？
</li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li>
Cochran’s <span class="math inline"><span class="math inline">\(Q\)</span></span>
の<strong>有意性</strong>が、研究間異質性の十分な指標とならないのはなぜか。
</li>
</ol>
<ol start="4" style="list-style-type: decimal">
<li>
メタ分析で異質性の大きさを表現するために予測区間を使うメリットは何か。
</li>
</ol>
<ol start="5" style="list-style-type: decimal">
<li>
統計的外れ値と影響力のある研究の違いは何か？
</li>
</ol>
<ol start="6" style="list-style-type: decimal">
<li>
GOSH のプロットは何に使えるのか。
</li>
</ol>
<p>
<strong>問題の解答は、本書の巻末 <a href="https://bookdown.org/baba_yoshihiko/Doing_Meta_Analysis_in_R/qanda.html#qanda5">Appendix
A</a> にある。</strong>
</p>
</div>
<p><br></p>
</div>
<div id="要約-1" class="section level2" number="5.6">
<h2>
<span class="header-section-number">5.6</span> 要約<a class="anchor" aria-label="anchor" href="#%E8%A6%81%E7%B4%84-1"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li><p>メタ分析では、プール効果量だけでなく、この平均的な効果量の根拠となったデータの<strong>異質性</strong>にも注意を払わなければならない。全体的な効果では、いくつかの研究における真の効果が私たちの点推定値と大きく異なる可能性があることを把握できないのである。</p></li>
<li><p>Cochran’s <span class="math inline">\(Q\)</span> は、データのばらつきを定量化するためによく使われる。<span class="math inline">\(Q\)</span> は <span class="math inline">\(\chi^2\)</span> 分布に従うことが分かっているので、この尺度を使うと、サンプル誤差だけに基づいて予想されるよりも多くの変動が存在するかどうかを検出することが可能である。この<strong>過剰な変動</strong>は、研究の効果量における真の差異を表している。</p></li>
<li><p><span class="math inline">\(Q\)</span> の統計的検定は、しかし、手元にあるデータの種類に大きく依存した。異質性の量を評価するために、<span class="math inline">\(Q\)</span> だけに頼るべきではない。<span class="math inline">\(I^2\)</span>、<span class="math inline">\(\tau\)</span> や予測区間など、追加で使用することができる他の尺度がある。</p></li>
<li><p>メタ分析における平均的な効果は、データに外れ値がある場合、偏りが生じることがある。外れ値は、メタ分析の結果に必ずしも大きな影響を与えるとは限りない。しかし、そのような場合は、「影響力のあるケース (influential cases) 」と呼ばれる。</p></li>
<li><p>外れ値や影響力のある症例を特定する方法はいろいろある。もし、そのような研究が検出された場合は、それらを除外してメタ分析を再計算し、私たちの結果の解釈が変わるかどうかを確認することが望ましい。</p></li>
</ul>
</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="pooling-es.html"><span class="header-section-number">4</span> 効果量のプール</a></div>
<div class="next"><a href="forest.html"><span class="header-section-number">6</span> フォレストプロット</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#heterogeneity"><span class="header-section-number">5</span> 研究間異質性</a></li>
<li>
<a class="nav-link" href="#het-measures"><span class="header-section-number">5.1</span> 異質性の尺度</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#cochran-q"><span class="header-section-number">5.1.1</span> Cochran’s \(Q\)</a></li>
<li><a class="nav-link" href="#i-squared"><span class="header-section-number">5.1.2</span> Higgins &amp; Thompson’s \(I^2\) 統計量</a></li>
<li><a class="nav-link" href="#h2-%E7%B5%B1%E8%A8%88%E9%87%8F"><span class="header-section-number">5.1.3</span> \(H^2\) 統計量</a></li>
<li><a class="nav-link" href="#tau"><span class="header-section-number">5.1.4</span> 異質性分散 \(\tau^2\) と標準偏差 \(\tau\)</a></li>
</ul>
</li>
<li><a class="nav-link" href="#het-measure-which"><span class="header-section-number">5.2</span> どの方法を使うべきか？</a></li>
<li><a class="nav-link" href="#het-R"><span class="header-section-number">5.3</span> R での異質性評価</a></li>
<li>
<a class="nav-link" href="#outliers"><span class="header-section-number">5.4</span> 外れ値と影響力のある事例</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#basic-outlier"><span class="header-section-number">5.4.1</span> 基本的な外れ値除去</a></li>
<li><a class="nav-link" href="#influence-analysis"><span class="header-section-number">5.4.2</span> 影響力分析</a></li>
<li><a class="nav-link" href="#gosh"><span class="header-section-number">5.4.3</span> GOSH プロット解析</a></li>
</ul>
</li>
<li><a class="nav-link" href="#%E6%BC%94%E7%BF%92%E5%95%8F%E9%A1%8C-4"><span class="header-section-number">5.5</span> 演習問題</a></li>
<li><a class="nav-link" href="#%E8%A6%81%E7%B4%84-1"><span class="header-section-number">5.6</span> 要約</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Doing Meta-Analysis in R</strong>: A Hands-on Guide" was written by Mathias Harrer, Pim Cuijpers, Toshi A. Furukawa, David D. Ebert. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
