<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>9 出版バイアス | Doing Meta-Analysis in R</title>
<meta name="author" content="Mathias Harrer">
<meta name="author" content="Pim Cuijpers">
<meta name="author" content="Toshi A. Furukawa">
<meta name="author" content="David D. Ebert">
<meta name="description" content="前 章を振り返ってみると、すでにメタ分析の幅広い技術をカバーしていることがわかる。効果量をプールする方法を学んだだけでなく、発見の頑健性を評価する方法、異質性のパターンを検査する方法、効果に差がある理由についての仮説を検証する方法についても学んだ。...">
<meta name="generator" content="bookdown 0.36 with bs4_book()">
<meta property="og:title" content="9 出版バイアス | Doing Meta-Analysis in R">
<meta property="og:type" content="book">
<meta property="og:description" content="前 章を振り返ってみると、すでにメタ分析の幅広い技術をカバーしていることがわかる。効果量をプールする方法を学んだだけでなく、発見の頑健性を評価する方法、異質性のパターンを検査する方法、効果に差がある理由についての仮説を検証する方法についても学んだ。...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="9 出版バイアス | Doing Meta-Analysis in R">
<meta name="twitter:site" content="@MathiasHarrer">
<meta name="twitter:description" content="前 章を振り返ってみると、すでにメタ分析の幅広い技術をカバーしていることがわかる。効果量をプールする方法を学んだだけでなく、発見の頑健性を評価する方法、異質性のパターンを検査する方法、効果に差がある理由についての仮説を検証する方法についても学んだ。...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/Fira_Sans-0.4.7/font.css" rel="stylesheet">
<link href="libs/Roboto_Mono-0.4.7/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.5.1/transition.js"></script><script src="libs/bs3compat-0.5.1/tabs.js"></script><script src="libs/bs3compat-0.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css">
<style>

    :root {
      --background-color: #FFFEFA;
      --text-color: #000;
      --highlight-color: #277DB0;
      --border-color: #999896;
      --grey-color: #6C6C6C;
      --line-color: #eee;
      --bg-box: #f5f5f5;
      --box-border-color: #eeeeee;
      --code-bg: #f8f8f8;
      --code-chunk-bg: linear-gradient(160deg,#f8f8f8 0, #f1f1f1 100%);
      --code-text-color: #212529;
      --hr-border-top: 1px solid rgba(0,0,0,0.1);
      --table-text-color: #000;
      --toc-active: #eee;
      --form-color: #4D4C4B;
      --form-background-color: #FFFEFA;
      --form-border: 1px solid #999896;
      --aa-cursor-background-color: #B2D7FF;
    }


    [data-theme="dark"] {
      --background-color: #2b2b2b;
      --text-color: #ffffff;
      --highlight-color: #34a8ed;
      --border-color: yellow;
      --grey-color: #cfcfcf;
      --line-color: #575757;
      --bg-box: #474747;
      --box-border-color: #474747;
      --code-bg: #474747;
      --code-chunk-bg: linear-gradient(160deg,#CDCDCD 0,#f1f1f1 100%);
      --code-text-color: #ffffff;
      --hr-border-top: 1px solid #575757;
      --table-text-color: #ffffff;
      --toc-active: #474747;
      --form-color: #cfcfcf;
      --form-background-color: #474747;
      --form-border: 1px solid #575757;
      --aa-cursor-background-color: #2b2b2b;
    }

    .algolia-autocomplete .aa-dropdown-menu .aa-suggestion {
      color: var(--form-color);
      border-bottom: 1px var(--form-border) solid;
      background-color: var(--form-background-color);
    }

    .algolia-autocomplete .aa-dropdown-menu .aa-suggestion.aa-cursor {
      background-color: var(--aa-cursor-background-color);
    }

    strong {
      font-family: "Helvetica Neue",
        Arial,
        "Hiragino Kaku Gothic ProN",
        "Hiragino Sans",
        Meiryo,
        sans-serif;
      font-weight: bolder;
    }

    .form-control {
      color: var(--form-color);
      background-color: var(--form-background-color);
      border: var(--form-border);
    }

    .form-control:focus {
      color: var(--text-color);
      background-color: var(--form-background-color);
      border: var(--form-border);
    }


    nav[data-toggle="toc"] .nav a.nav-link.active, nav[data-toggle="toc"] .nav .nav-link.active > li > a {
        background-color: var(--toc-active);
    }

    .btn-circle.btn-md {
      width: 50px;
      height: 50px;
      padding: 7px 10px;
      border-radius: 25px;
      font-size: 10px;
      text-align: center;
    }


    .lightable-classic td {
      color: var(--text-color);
    }


    .table {
      color: var(--table-text-color);
    }

    hr {
      border-top: var(--hr-border-top);
    }

    code {
      background-color: var(--code-bg);
      color: var(--code-text-color);
    }

    pre {
      background-image: var(--code-chunk-bg);
    }

    body {
      background-color: var(--background-color);
      color: var(--text-color);
    }

    a {
      color: var(--highlight-color);
    }

    .header-section-number {
      color: var(--grey-color);
    }

    small.text-muted {
      color: var(--grey-color) !important;
    }


    .firstcharacter {
      color: var(--highlight-color);
    }

    p.caption {
      color: var(--grey-color);
    }

    .figure {
      border-top: 2px solid var(--line-color);
      border-bottom: 2px solid var(--line-color);
    }


    .inline-figure {
      border: 0;
      box-shadow: none;
    }

    .boxinfo {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boxinfo:before {
        content: '\f0eb';
        font-family: FontAwesome;
        left:20px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .boxempty {
      padding: 1em 1em 1em 1.1em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boxempty:before {
        content: '\f0eb';
        font-family: FontAwesome;
        left:0px;
        position:absolute;
        font-size: 30px;
        color: transparent;
     }

    .boximportant {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boximportant:before {
        content: '\f06a';
        font-family: FontAwesome;
        left:13px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .boxreport {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boxreport:before {
        content: '\f570';
        font-family: FontAwesome;
        left:15px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .boxdmetar {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .csl-entry {
      margin-bottom: 20px;
      padding-left: 1.5em;
      text-indent:-1.5em;
    }

    .boxdmetar:before {
        content: '\f4f7';
        font-family: FontAwesome;
        left:10px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .boxquestion {
      padding: 1em 1em 1em 3em;
      margin-bottom: 10px;
      background: var(--bg-box);
      position:relative;
      border-width: 3px;
      border-style: solid;
      border-color: var(--box-border-color);
      border-radius: .25rem;
    }

    .boxquestion:before {
        content: '\f059';
        font-family: FontAwesome;
        left:12px;
        position:absolute;
        font-size: 30px;
        color: var(--highlight-color);
     }

    .mode-switch {
      font-size: 0.9rem;
    }

    img {
      max-width: 100%;
      height: auto;
      border-radius: .25rem;
    }


    .firstcharacter {
      color: var(--highlight-color);
      float: left;
      font-size: 40px;
      line-height: 50px;
      padding-bottom: 2px;
      padding-right: 8px;
      padding-left: 2px;
    }


    .btn-circle.btn-sm {
        width: 30px;
        height: 30px;
        padding: 6px 0px;
        border-radius: 15px;
        font-size: 20px;
        text-align: center;
    }
    .btn-circle.btn-md {
        width: 50px;
        height: 50px;
        padding: 7px 10px;
        border-radius: 25px;
        font-size: 20px;
        text-align: center;
    }
    .btn-circle.btn-xl {
        width: 60px;
        height: 60px;
        padding: 7px 7px;
        border-radius: 35px;
        font-size: 30px;
        text-align: center;
    }

    #critical-btn.btn-secondary {
      background-color: var(--grey-color);
      border-color: var(--grey-color);
    }

    .sticky-item {
        position: fixed;
        bottom: 30px;
        right: 30px;
    }



    </style>
<link rel="shortcut icon" href="favicon.ico">
<script type="text/x-mathjax-config">
    const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
    for (let popover of popovers){
      const div = document.createElement('div');
      div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
      div.innerHTML = popover.getAttribute('data-content');

      // Will this work with TeX on its own line?
      var has_math = div.querySelector("span.math");
      if (has_math) {
        document.body.appendChild(div);
      	MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
      	MathJax.Hub.Queue(function(){
          popover.setAttribute('data-content', div.innerHTML);
      	})
      }
    }
    </script><link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script><script type="text/javascript">
      // Add switch element
      document.addEventListener('DOMContentLoaded', function(event){
        let darkSwitch = document.createElement('div');
        darkSwitch.innerHTML = "<div class='sticky-item'><button type='button' id='critical-btn' class='btn btn-dark btn-circle btn-xl'>🌓</button></div>"
        document.body.appendChild(darkSwitch);
      })

    $(document).ready(function() {

        $("#critical-btn").click(function () {

            if ($(this).hasClass('btn-dark')){
                $('#critical-btn').removeClass('btn-dark').addClass('btn-secondary');
                $(this).addClass('btn-secondary').removeClass('btn-dark');
            }

            else if ($(this).hasClass('btn-secondary')){
                $('#critical-btn').removeClass('btn-secondary').addClass('btn-dark');
                $(this).addClass('btn-dark').removeClass('btn-secondary');
            }

        })
    })
    </script><script type="text/javascript">
      // Wait for document to load
      document.addEventListener("DOMContentLoaded", function(event) {
        document.documentElement.setAttribute("data-theme", "light");

        // Get our button switcher
        var themeSwitcher = document.getElementById("critical-btn");

        // When our button gets clicked
        themeSwitcher.onclick = function() {
          // Get the current selected theme, on the first run
          // it should be `light`
          var currentTheme = document.documentElement.getAttribute("data-theme");

          // Switch between `dark` and `light`
          var switchToTheme = currentTheme === "dark" ? "light" : "dark"

          // Set our currenet theme to the new one
          document.documentElement.setAttribute("data-theme", switchToTheme);

          // Save current selection
          localStorage.setItem('themeMode', switchToTheme);

        }
      });

      // keep selection across pages
      document.addEventListener('DOMContentLoaded', function(event){
        const currentTheme = localStorage.getItem('themeMode')
        if (currentTheme === 'dark'){
        document.documentElement.setAttribute("data-theme", 'dark');
          if ($("#critical-btn").hasClass('btn-dark')) {
            $('#critical-btn').removeClass('btn-dark').addClass('btn-secondary');
            $('#critical-btn').addClass('btn-secondary').removeClass('btn-dark');
          }
        } else {
        document.documentElement.setAttribute("data-theme", 'light');
          if ($("#critical-btn").hasClass('btn-secondary')) {
            $('#critical-btn').removeClass('btn-secondary').addClass('btn-dark');
            $('#critical-btn').addClass('btn-dark').removeClass('btn-secondary');
          }
      }})
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="A Hands-on Guide">Doing Meta-Analysis in R</a>:
        <small class="text-muted">A Hands-on Guide</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">ようこそ！</a></li>
<li><a class="" href="preface.html">序章</a></li>
<li><a class="" href="about-the-authors.html">著者について</a></li>
<li class="book-part">はじめに</li>
<li><a class="" href="intro.html"><span class="header-section-number">1</span> はじめに</a></li>
<li><a class="" href="discovering-R.html"><span class="header-section-number">2</span> R の発見</a></li>
<li class="book-part">Rでメタ分析</li>
<li><a class="" href="effects.html"><span class="header-section-number">3</span> 効果量</a></li>
<li><a class="" href="pooling-es.html"><span class="header-section-number">4</span> 効果量のプール</a></li>
<li><a class="" href="heterogeneity.html"><span class="header-section-number">5</span> 研究間異質性</a></li>
<li><a class="" href="forest.html"><span class="header-section-number">6</span> フォレストプロット</a></li>
<li><a class="" href="subgroup.html"><span class="header-section-number">7</span> サブグループ解析</a></li>
<li><a class="" href="metareg.html"><span class="header-section-number">8</span> メタ回帰</a></li>
<li><a class="active" href="pub-bias.html"><span class="header-section-number">9</span> 出版バイアス</a></li>
<li class="book-part">高度な分析</li>
<li><a class="" href="multilevel-ma.html"><span class="header-section-number">10</span> 「マルチレベル」メタ分析</a></li>
<li><a class="" href="sem.html"><span class="header-section-number">11</span> 構造方程式モデリングメタ分析</a></li>
<li><a class="" href="netwma.html"><span class="header-section-number">12</span> ネットワークメタ分析</a></li>
<li><a class="" href="bayesian-ma.html"><span class="header-section-number">13</span> ベイズメタ分析</a></li>
<li class="book-part">各種ツール</li>
<li><a class="" href="power.html"><span class="header-section-number">14</span> 検出力分析</a></li>
<li><a class="" href="risk-of-bias-plots.html"><span class="header-section-number">15</span> バイアスリスクのプロット</a></li>
<li><a class="" href="reporting-reproducibility.html"><span class="header-section-number">16</span> 報告と再現性</a></li>
<li><a class="" href="es-calc.html"><span class="header-section-number">17</span> 効果量の計算と換算</a></li>
<li class="book-part">付録</li>
<li><a class="" href="qanda.html"><span class="header-section-number">A</span> Q&amp;A</a></li>
<li><a class="" href="formula.html"><span class="header-section-number">B</span> 効果量の計算式</a></li>
<li><a class="" href="symbollist.html"><span class="header-section-number">C</span> シンボルマーク一覧</a></li>
<li><a class="" href="attr.html"><span class="header-section-number">D</span> R およびパッケージ情報</a></li>
<li><a class="" href="corrections.html"><span class="header-section-number">E</span> 訂正・備考</a></li>
<li><a class="" href="citing-this-guide-1.html">本書を引用</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="pub-bias" class="section level1" number="9">
<h1>
<span class="header-section-number">9</span> 出版バイアス<a class="anchor" aria-label="anchor" href="#pub-bias"><i class="fas fa-link"></i></a>
</h1>
<hr>
<div class="inline-figure"><img src="_figs/pub_bias.jpg"></div>
<p><br></p>
<p><span class="firstcharacter">前</span>
章を振り返ってみると、すでにメタ分析の幅広い技術をカバーしていることがわかる。効果量をプールする方法を学んだだけでなく、発見の頑健性を評価する方法、異質性のパターンを検査する方法、効果に差がある理由についての仮説を検証する方法についても学んだ。</p>
<p>これらのアプローチはすべて、メタ分析から有効な結論を引き出すのに役立つ。しかし、これはデータの性質に関するある暗黙の前提の上に成り立っているが、まだそれに挑戦していない。すなわち、メタ分析を行う際、収集したデータが<strong>包括的</strong>であること、あるいは少なくとも調査中の研究分野を<strong>代表</strong>するものであることを前提としている。</p>
<p>Chapter <a href="intro.html#study-search">1.4.3</a> で、メタ分析は通常、研究分野を適切に説明する単一の効果量を導き出すために、利用可能な<strong>すべての</strong>エビデンスを含めようとすることを述べた。統計学的な観点からは、研究がいくつか欠けていても許容できるだろうが、それはこれらの研究が偶然に「省かれた」場合のみである。</p>
<p>残念ながら、多くの場合、メタ分析では既存のエビデンスをすべて網羅することはできない。さらに悪いことに、いくつかの研究は、収集したデータから完全に「ランダムに」して欠落しているわけではないと考えられる理由も十分にある。この世界は不完全であり、科学的実践を支配するインセンティブや「ルール」もまた不完全である。つまり、ある研究がメタ分析に含まれるかどうかを決定するシステム的なバイアスが存在するのである。</p>
<p>この問題の良い例が、あまり知られていない薬物療法研究の逸話にある。1990 年代には、抗うつ薬 (<strong>選択的セロトニン再取り込み阻害薬</strong>、selective serotonin re-uptake inhibitor SSRI など) がうつ病患者に有効であることは周知の事実と考えられていた。エビデンスの多くは、抗うつ薬とプラセボを比較した薬物療法の臨床試験のメタ分析によって得られている。抗うつ薬の市場は何十億ドルもの価値があり、着実に成長していることを考えると、抗うつ薬の効果に関する疑問は重要なものである。</p>
<p>このことは、Irving Kirsch et al. <span class="citation">(<a href="references.html#ref-kirsch2002emperor">2002</a>)</span> が書いた「<strong>The Emperor’s New Drugs</strong>」という論文が引き起こした論争を理解するのに役立つだろう。この論争では、結局、物事はそれほど明るくないのではないかと論じた。</p>
<p>Kirsch et al. は、「情報公開法」を利用して、製薬会社が米国食品医薬品局に提供していた未発表の抗うつ剤試験データを入手した。そして、この未発表のデータも考慮すると、プラセボと比較した抗うつ薬の効果はせいぜいわずかであり、臨床的には無視しうるものであることを発見した。Kirsch らは、企業が好ましい知見を持つ研究のみを発表し、「期待はずれ」のエビデンスを持つ研究は非公開にしたためだと主張した <span class="citation">(<a href="references.html#ref-kirschemperorbook">Kirsch 2010</a>)</span>。</p>
<p></p>
<p>その後、論争が起こり、Kirsch の主張は今日に至るまで論争の的となっている。この例を選んだのは、どちらかを選ぶためではなく、欠落した研究がメタ分析の推論の妥当性にもたらす潜在的な脅威を説明するためである。メタ分析の文献では、このような問題は通常、<strong>出版バイアス</strong> (publication bias) という用語で要約されている。</p>
<p></p>
<p>出版バイアスの問題は、メタ分析におけるすべての知見が、その根拠となるデータと同程度のものでしかないことを明確に示している。メタ分析の技術は、手元にあるデータでしか機能しない。したがって、収集したデータに歪みがあると、どんなに優れた統計モデルでも固有のバイアスを再現してしまうだけなのである。この基本的な注意点については、本書の一番最初に「ファイルの引き出し」問題 (Chapter <a href="intro.html#pitfalls">1.3</a>) を取り上げたときに、すでに取り上げていたことを思い出すだろう。実際、「ファイルの引き出し問題」と「出版バイアス」という言葉は、しばしば同義的に使われる。</p>
<p>出版バイアスや関連する問題がメタ分析の結果に及ぼす影響は甚大である。治療の効果を過大評価したり、否定的な副作用を見落としたり、実際には無効である理論の信奉を強めたりする原因となり得るのである。</p>
<p>そこで本章では、出版バイアスが知見を歪めてしまう様々な形について議論した。また、メタ分析担当者として、データにおける出版バイアスのリスクを調査するために使用できるいくつかのアプローチ、およびそもそも出版バイアスをどのように軽減できるかを見ていこう。</p>
<p><br></p>
<div id="types-of-pub-biases" class="section level2" number="9.1">
<h2>
<span class="header-section-number">9.1</span> 出版バイアスとは何か？<a class="anchor" aria-label="anchor" href="#types-of-pub-biases"><i class="fas fa-link"></i></a>
</h2>
<hr>
<p>ある研究が出版される確率がその結果に影響される場合、出版バイアスが存在する <span class="citation">(<a href="references.html#ref-duval2005publication">Rothstein, Sutton, and Borenstein 2005, chap. 2</a> と Chapter 5)</span>。研究結果が統計的に有意である場合、あるいは初期仮説を確認する場合、その研究が世に出る可能性が高いというエビデンスが広く存在する <span class="citation">(<a href="references.html#ref-schmucker2014extent">Schmucker et al. 2014</a>; <a href="references.html#ref-scherer2018full">Scherer et al. 2018</a>; <a href="references.html#ref-chan2014increasing">Chan et al. 2014</a>; <a href="references.html#ref-dechartres2018association">Dechartres et al. 2018</a>)</span>。</p>
<p>適格な研究を検索する場合、通常、何らかの形で公表されているエビデンス、例えば、査読付き論文、プレプリント、書籍、その他のアクセス可能な報告書などに制約されることになる。出版バイアスがある場合、これはデータセットに含まれていない研究があることを意味するだけでなく、含まれていない研究に好ましくない知見を持つものである可能性が高いということを意味している。</p>
<p>メタ分析の手法を用いれば、母集団における平均的な効果量の偏りのない推定値を求めることが可能である。しかし、サンプルそのものが歪んでいれば、統計学的に「正しい」効果推定値であっても、現実を代表するものではない。これは、氷山の大きさを推し量るのに、その先端しか測っていないようなもので、たとえ水面からの高さを完璧に測ることができたとしても、その結果は必然的に間違っているのである。</p>
<p>
</p>
<p>出版バイアスは、実は多くの<strong>報告バイアス</strong>のうちの1つに過ぎない。メタ分析 <span class="citation">(<a href="references.html#ref-page2020investigating">Page et al. 2020</a>)</span> で得られるエビデンスを歪める要因も、他にもいくつかある。</p>
<ul>
<li><p><strong>引用バイアス</strong> (Citation bias): たとえ出版されたとしても、否定的な結果や結論の出ていない研究は、関連する文献に引用される可能性が低くなる。そのため、例えば参考文献検索などで発見することが難しくなる。</p></li>
<li><p><strong>タイムラグバイアス</strong> (Time-lag bias): 肯定的な結果を得た研究は、好ましくない結果を得た研究よりも早く発表されることが多い。つまり、最近行われた研究で肯定的な結果を得たものはすでに入手可能であることが多いが、有意でない結果を得たものはそうでないことが多い。</p></li>
<li><p><strong>多重投稿バイアス</strong> (Multiple publication bias): 「成功した」研究の結果は、複数の論文で報告される可能性が高く、そのうちの少なくとも 1 つを見つけることが容易になる。複数の論文にまたがって研究結果を報告するやり方は、「サラミスライス」とも呼ばれる。</p></li>
<li><p><strong>言語バイアス</strong> (Language bias): ほとんどの分野で、エビデンスが発表される主な言語は英語である。他の言語による出版物は、特に研究者自身が翻訳しなければ内容を理解できない場合、発見されにくい。英語の研究が他の言語で発表されたものと系統的に異なる場合、これもまたバイアスを引き起こす可能性がある。</p></li>
<li><p><strong>アウトカムバイアス</strong> (Outcome reporting bias): 多くの研究、特に臨床試験では、関心のあるアウトカムを複数測定する。これを悪用して、肯定的な結果が得られたアウトカムだけを報告し、仮説を確認できなかったアウトカムは削除する研究者もいる。これもバイアスにつながる。厳密に言えば、研究は発表されているのに、その (好ましくない) 結果は報告されていないため、メタ分析ではまだ見落とされていることになる。</p></li>
</ul>
<p></p>
<p>非報告バイアスは、既存のエビデンスを見つけにくくするシステム的な要因として捉えることができる。しかし、たとえ関連する知見をすべて含めることができたとしても、この結果には欠陥があるだろう。また、研究者が知見を分析・報告する際に適用した<strong>疑問のある研究手法</strong> (questionable research practices, QRP) により、バイアスが存在する可能性もある <span class="citation">(<a href="references.html#ref-simonsohn2020specification">Simonsohn, Simmons, and Nelson 2020</a>)</span>。</p>
<p></p>
<p>「研究者の自由度」という概念については、以前すでに触れた (Chapter <a href="intro.html#pitfalls">1.3</a>)。QRP は、研究者がこの自由度を乱用して、結果を望ましい方向に「曲げる」行為と定義することができる。残念ながら、何が QRP を構成するのかについて明確なコンセンサスはない。しかし、一般的に提案されているいくつかの例がある。</p>
<p>最も顕著な QRP のひとつが <strong>p-hacking</strong> で、従来の有意水準である <span class="math inline">\(p&lt;\)</span> 0.05 に達するまで分析を微調整するものである。これには、外れ値の除去、サブグループの分析、欠損データの処理などが含まれる。</p>
<p></p>
<p>別の QRP は <strong>HARKing</strong> <span class="citation">(<a href="references.html#ref-kerr1998harking">Kerr 1998</a>)</span> といって、<strong>結果が判明した後に仮説を立てること</strong>である。HARKing の一つは、探索的分析における発見が、研究の a priori な仮説であったかのように装うことである。例えば、研究者が、データセットに対して様々なテストを実行し、有意であったすべてのテストについて仮説を「発明」することがある。これは重大な欠陥のあるアプローチで、研究の偽発見率を高め、偽の発見のリスクを増加させる (など、問題は他にもある)。もう一つのタイプの HARKing は、データによってサポートされなかったすべての仮説を取り下げることであり、これは最終的にアウトカム報告バイアスにつながる可能性がある。</p>
<p><br></p>
</div>
<div id="addressing-pubbias" class="section level2" number="9.2">
<h2>
<span class="header-section-number">9.2</span> メタ分析における出版バイアス<a class="anchor" aria-label="anchor" href="#addressing-pubbias"><i class="fas fa-link"></i></a>
</h2>
<hr>
<p>出版バイアス、報告バイアス、QRP がメタ分析の妥当性に強く有害な影響を与えることは明らかである。バイアスの正確な大きさ、あるいはバイアスが存在するかどうかを知ることは、通常、事実上不可能であるため、これらは大きな課題となっている。</p>
<p>
</p>
<p>メタ分析では、QRP と同様に、出版・報告バイアスによる歪みのリスクをある程度軽減する手法を適用することが可能である。そのアプローチには、研究探索に関連するものもあれば、統計的な手法もある。</p>
<ul>
<li><p><strong>研究検索</strong>: Chapter <a href="intro.html#study-search">1.4.3</a> で、適格な研究を検索するプロセスについて説明してきた。出版バイアスが存在する場合、このステップは非常に重要である。なぜなら、出版された文献を検索しても、すべてのエビデンスを完全に代表していないデータが得られる可能性があることを意味する。学位論文、プレプリント、政府報告書、会議録などを含む<strong>灰色文献</strong>も検索することで、これに対抗することが可能である。幸いなことに、事前登録も多くの分野で一般的になってきている。これにより、ICTRP や <strong>OSF Registries</strong> などの研究登録 ( Chapter <a href="intro.html#study-search">1.4.3</a> の Table <a href="intro.html#tab:bibdatabases">1.1</a> を参照) を検索して、未発表データのある研究を探し、著者に (まだ) 公開されていないデータを提供してもらえるか尋ねることが可能である<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;Mahmood and colleagues &lt;span class="citation"&gt;(&lt;a href="references.html#ref-mahood2014searching"&gt;2014&lt;/a&gt;)&lt;/span&gt; には、包括的なグレー文献検索の方法とそれに伴う課題の詳細説明が掲載されている。この論文は、オンラインでオープンにアクセスすることができる&lt;/p&gt;'><sup>34</sup></a>。灰色文献検索は退屈で嫌になるだろうが、努力する価値はある。灰色文献や未発表の文献を含めることで真の効果の過大評価を避けることができることは、大規模な研究でわかっている <span class="citation">(<a href="references.html#ref-mcauley2000does">McAuley et al. 2000</a>)</span>。</p></li>
<li><p><strong>統計的手法</strong>: 統計的手法によって出版物の有無を調べることも可能である。これらの方法はいずれも出版バイアスを直接同定することはできないが、それを示すと思われるデータのある種の特性を調べることが可能である。また、出版バイアスを補正した場合の真の全体効果を定量化するために使用できる手法もある。</p></li>
</ul>
<p></p>
<p>本章では、出版バイアスを評価・制御するための一般的な<strong>統計的</strong>手法を紹介する。まず、<strong>小規模研究効果</strong>に着目した方法から始める <span class="citation">(<a href="references.html#ref-sterne2000publication">Sterne, Gavaghan, and Egger 2000</a>; <a href="references.html#ref-schwarzer2015meta">Schwarzer, Carpenter, and Rücker 2015, chap. 5</a>; <a href="references.html#ref-duval2005publication">Rothstein, Sutton, and Borenstein 2005, chap. 5</a>)</span>。このアプローチに共通するのは、研究の精度と観察された効果量の関係を見ることで、出版バイアスの指標を見つけるという点である。</p>
<p><br></p>
<div id="small-study-effects" class="section level3" number="9.2.1">
<h3>
<span class="header-section-number">9.2.1</span> 小規模研究効果測定法<a class="anchor" aria-label="anchor" href="#small-study-effects"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p>メタ分析における出版バイアスを評価・補正する方法として、様々な小規模研究効果法がある。その多くは、長年にわたり従来からある手法である。名前にあるように、これらの手法は特に<strong>小規模研究</strong>に関係している。統計学的な観点からは、これは標準誤差が大きい研究に相当する。小規模研究効果法は、小規模な研究は出版バイアスの餌食になりやすいと仮定している。</p>
<p>この前提は、3つの核となる考えに基づいている <span class="citation">(<a href="references.html#ref-borenstein2011introduction">Borenstein et al. 2011</a>、第30章参照)</span>。</p>
<p></p>
<ol style="list-style-type: decimal">
<li><p>大規模な研究は、多くの資源と時間を投入するため、結果が有意であろうとなかろうと、出版される可能性が高い。</p></li>
<li><p>中程度の規模の研究は、発表されないリスクが高くなる。しかし、統計的検出力が中程度であっても、有意な結果を得るには十分であることが多い。つまり、「好ましくない」 (つまり有意でない) 結果を出したために、出版されない研究もあるということである。</p></li>
<li><p>小規模な研究は、発見が有意でないリスクが最も高く、そのため「ファイルの引き出し」に入ったままとなる。小規模な研究では、非常に大きな効果だけが有意となる。つまり、非常に大きな効果量を持つ小規模な研究のみが発表されることになる。</p></li>
</ol>
<p>これらの仮定の背後にあるとされるメカニズムは、非常に単純であることがわかる。本質的には、有意な効果のみが公表されるため、出版バイアスが存在するということである。サンプルサイズが大きいほど有意な結果が得られる確率が高くなるので、出版バイアスは小規模な研究であるほど均等ではない影響がある。</p>
<p><br></p>
<div id="funnel-plot" class="section level4" number="9.2.1.1">
<h4>
<span class="header-section-number">9.2.1.1</span> ファネルプロット<a class="anchor" aria-label="anchor" href="#funnel-plot"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p></p>
<p>このガイドの前半 (Chapter <a href="effects.html#what-is-es">3.1</a>) で、研究のサンプルサイズと標準誤差が密接に関係していることを学んだ。効果量の標準誤差が大きいと、信頼区間が広くなり、効果が統計的に有意でない可能性が高くなる。したがって、小さな研究の効果は、大きな標準誤差を持つ研究に大きく影響すると仮定するのは賢明なことである。</p>
<p>収集したデータが出版バイアスによって負担されたと仮定する。この場合、大きな標準誤差を持つ研究は、低い標準誤差を持つ研究よりも効果量が大きいと仮定することが可能である。これは、効果の小さい研究は有意でなく、出版の検討すらされなかった。結果として、メタ分析に含めるられることもない。</p>
<p>小規模研究の効果を調べるには、<strong>ファネルプロット</strong>が一般的である。ファンネルプロットは、x軸に観察された効果量を、y軸に標準誤差の指標をとってプロットしたものである。通常、ファンネルプロットのy軸は反転している (y軸上の「高い」値は、標準誤差が<strong>低い</strong>ことを表している)。</p>
<p>出版バイアスがない場合、このようなプロットのデータポイントは、ほぼ対称的な逆さファンネル (漏斗のこと) を形成するはずである。これがファンネルプロットと呼ばれる所以である。プロットの上部にある研究 (標準誤差が小さいもの) は、密接に並んでおり、プール効果量からそれほど離れていないはずである。プロットの下部では、標準誤差が大きくなるにつれて、漏斗が「開き」、効果量がプール効果量の左右に大きく散らばることが予想される。</p>
<p>Chapter <a href="effects.html#what-is-es">3.1</a> で効果量について学んだことや、Chapter <a href="pooling-es.html#fem">4.1.1</a> (Figure <a href="pooling-es.html#fig:funnel1">4.1</a>) で固定効果モデルについて議論したことを思い出すと、なぜ研究が漏斗を形成する必要があるのかがわかりやすくなる。標準誤差は、研究の<strong>精度</strong>を示している: 標準誤差が小さくなればなるほど、観察された効果量は、真の効果量の良い推定量になると予想される。標準誤差が大きい場合、効果量は精度が低く、したがって母集団における実際の効果から大きく外れている可能性が高くなる。</p>
<p>では、ファネルプロットを作成し、より具体的にしていこう。メタ分析オブジェクトのファネルプロットを表示すには、 <strong>{meta}</strong> パッケージの <code>funnel.meta</code> 関数を使用することが可能である。ここでは、メタ分析オブジェクト <code>m.gen</code> に対してファネルプロットを生成する。さらに2つの引数、 <code>xlim</code> と <code>studlab</code> を指定する。最初の引数はプロットにおけるX軸の限界をコントロールし、後者は研究ラベルを含めるようにこの関数に指示する。<code>funnel</code> を実行した後に <code>title</code> 関数を呼び出すと、プロットにタイトルが追加される。</p>
<p>コードは次のようになる。</p>
<div class="sourceCode" id="cb245"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 'meta' パッケージをロード</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/guido-s/meta/">meta</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># ファンネルプロットを作成</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/meta/man/funnel.meta.html">funnel.meta</a></span><span class="op">(</span><span class="va">m.gen</span>,</span>
<span>            xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.5</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>            studlab <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># タイトルを追加</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/title.html">title</a></span><span class="op">(</span><span class="st">"Funnel Plot (Third Wave Psychotherapies)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-210-1.png" width="85%" style="display: block; margin: auto;"></div>
<p>すでに説明したように、得られたファネルプロットは、x軸に各研究の効果量 (標準化平均差として表現)、y軸に標準誤差 (大から小へ) を示している。解釈を容易にするため、このプロットには、研究が従うと思われる理想的なファネルの形も含まれている。ファンネルの真ん中の縦線は、平均効果量を示している。<code>m.gen</code> を生成する際にランダム効果モデルを使用したので、ファネルプロットもランダム効果推定値を使用している。</p>
<p>少人数研究の影響がなければ、プロットに表示される漏斗で描かれる形状に沿うはずである。この例では、そうなっているだろうか？そうではない。標準誤差が小さい研究ほど、推定された真の効果の周りに集中していることがわかるが、パターンは全体的に非対称に見える。これは、プロットの右下に非常に高い効果量を持つ 3 つの小さな研究 (Shapiro、Kang、Danitz-Orsillo によるもの) があるためである。</p>
<p>しかし、これらの研究には、プロットの左下隅に相当するものがない。非常に高い効果を持つ研究と「均等になる」ような、非常に低い効果量や負の効果量を持つ小規模な研究は存在しないのである。もう一つ気になるのは、サンプルの中で最も精度の高い、de Vibe による研究が、漏斗パターンにうまく従っていないように見えることである。この効果量は、予想よりもかなり小さい。</p>
<p>全体として、このデータセットは、出版バイアスを示しそうな非対称のパターンをファネルプロットに示している。3 つの小さな研究は、運良く有意になるのに十分な効果を見出したものであり、一方、同様の標準誤差を持ちながら、小さい方、つまり有意でない効果を持つ未発表の研究が存在しても、成功には至らなかったのだろう。</p>
<p>非対称パターンと統計的有意性の関係を調べるには、<strong>等高線ファンネルプロット</strong> (contour-enhanced funnel plot) <span class="citation">(<a href="references.html#ref-peters2008contour">Peters et al. 2008</a>)</span> を作成するのが良い方法である (訳注: 「等高線ファンネルプロット」は、「輪郭強調ファンネルプロット」と訳されることもある。)。等高線ファンネルプロットは、出版バイアスと他の非対称性を区別するのに役立つように、プロット内の各研究の有意水準を示す色を含んでいる。<code>funnel.meta</code> 関数では、<code>contour</code> 引数に希望の有意閾値を与えることで等高線を追加することが可能である。通常は、<code>0.9</code>、<code>0.95</code>、<code>0.99</code> で、それぞれ <span class="math inline">\(p\)</span> &lt; 0.1、0.05、0.01 に相当する。また、<code>col.contour</code> 引数を使用すると、輪郭の色を指定することが可能である。最後に、プロットに凡例を追加するために、<code>legend</code> 関数を使用することができ、異なる色の意味を指定することができる。<code>x</code> と <code>y</code> 引数を使用してプロット上に凡例を配置し、<code>legend</code> でラベルを指定し、<code>fill</code> 引数を使用して塗りつぶしの色を追加することが可能である。</p>
<p>この結果、以下のようなコードになる。</p>
<div class="sourceCode" id="cb246"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 等高線の塗りつぶし色を定義</span></span>
<span><span class="va">col.contour</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"gray75"</span>, <span class="st">"gray85"</span>, <span class="st">"gray95"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># ファンネルプロットを生成 (研究ラベルはなし)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/meta/man/funnel.meta.html">funnel.meta</a></span><span class="op">(</span><span class="va">m.gen</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.5</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>            contour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.9</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span><span class="op">)</span>,</span>
<span>            col.contour <span class="op">=</span> <span class="va">col.contour</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 凡例を追加</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/PerformanceAnalytics/man/legend.html">legend</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1.6</span>, y <span class="op">=</span> <span class="fl">0.01</span>, </span>
<span>       legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"p &lt; 0.1"</span>, <span class="st">"p &lt; 0.05"</span>, <span class="st">"p &lt; 0.01"</span><span class="op">)</span>,</span>
<span>       fill <span class="op">=</span> <span class="va">col.contour</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># タイトルを追加</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/title.html">title</a></span><span class="op">(</span><span class="st">"Contour-Enhanced Funnel Plot (Third Wave Psychotherapies)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-212-1.png" width="75%" style="display: block; margin: auto;"></div>
<p>ファネルプロットは、3つの陰影領域を含んでいることがわかる。 <span class="math inline">\(p&lt;\)</span> 0.05 と <span class="math inline">\(p&lt;\)</span> 0.01 の領域に特に興味がある。なぜなら、この領域に入る効果量は、伝統的に有意とみなされている。</p>
<p>等高線領域を追加すると、3 つの小さな研究は、大きな標準誤差があるにもかかわらず、すべて有意な効果を示していることがわかる。同じような標準誤差を持つ研究で、有意でないものが1つだけある。対称性を高めるためにプロットの左下隅にある欠落した研究を「インプット」すると、これらの研究はプロットの非有意領域に位置することになる。</p>
<p>大規模な研究については、少しパターンが異なるようである。<span class="math inline">\(p&gt;\)</span> 0.05 の研究がいくつかあり、効果の分布はあまり偏っていないことがわかる。しかし問題なのは、厳密には有意ではないものの、1 つの研究を除くすべての研究が有意性閾値に非常に近い (すなわち、0.1 <span class="math inline">\(&gt; p &gt;\)</span> 0.05 の領域にある) ことである。これらの研究は、元の論文では単に効果量の計算が違っていて、それが有意な結果につながった可能性がある。あるいは、傾向レベルで有意な効果を見出すことが、すでに研究を発表するのに十分な説得力を持っていたのだろう。</p>
<p>まとめると、等高線ファンネルプロットによる検証では、非対称性があるのではないか、それは出版バイアスによって引き起こされたのではないかという当初の直感を裏づけるものであった。しかし、結論を急がず、ファンネルプロットを慎重に解釈することが大事である。出版バイアスは、ファネルプロットの非対称性の原因として考えられる多くの理由のうちの1つに過ぎないことを念頭に置かなければならない。</p>
<p></p>
<div class="boxinfo">
<p>
<strong>ファネルプロットの非対称性とは</strong>
</p>
<p>
出版バイアスは非対称のファネルプロットにつながるが、同様のパターンを生み出す他の、むしろ「良性」の原因もある
<span class="citation"><span class="citation">(<a href="references.html#ref-page2020investigating">Page et al. 2020</a>)</span></span> 。
</p>
<ul>
<li>
非対称性は、研究間の異質性によって引き起こされることもある。ファネルプロットは、効果量の分散が研究のサンプリング誤差によって引き起こされると仮定しているが、研究が異なる真の効果の推定者である可能性を制御することはできない。
</li>
</ul>
<ul>
<li>
小規模な研究では、研究の手順が異なり、その結果、効果が高くなった可能性がある。例えば、臨床研究では、サンプルサイズが小さいと、すべての参加者が意図したとおりに治療を受けていることを確認するのが容易である。大規模な研究ではそうではないため、<strong>治療忠実度</strong>
(treatment fidelity)
が低くなり、その結果、効果も低くなる可能性がある。このような代替説明が妥当かどうかを評価するために、対象研究の特徴を検証することは意味がある。
</li>
</ul>
<ul>
<li>
質の低い研究では、バイアスリスクが高いため、効果量が大きくなる傾向があることは一般的に知られている。大規模な研究はより多くの投資を必要とするため、方法論もより厳密なものになる可能性がある。よって、出版バイアスがない場合でも、ファネルプロットの非対称性につながる可能性がある。
</li>
</ul>
<ul>
<li>
最後に、ファネルプロットの非対称性は、単に偶然に起こる可能性も十分にある。
</li>
</ul>
</div>
<p></p>
<p>(等高線) ファンネルプロットを視覚的に検証して、結果が出版バイアスの影響を受けている可能性を示すいくつかの「レッドフラッグ」が投げ出されたことを確認した。</p>
<p>しかし、ファネルプロットをはっきり見ただけで解釈することにも限界がある。結果が「非対称すぎる」場合の明確なルールはなく、ファネルプロットからの推論は常に主観的である。したがって、定量的な方法でファネルプロットの非対称性の存在を評価することが有用である。これは通常、次に説明する <strong>Egger の回帰検定</strong>によって達成される。</p>
<p><br></p>
</div>
<div id="eggers-test" class="section level4" number="9.2.1.2">
<h4>
<span class="header-section-number">9.2.1.2</span> Egger の回帰検定<a class="anchor" aria-label="anchor" href="#eggers-test"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p>Egger の回帰検定 <span class="citation">(<a href="references.html#ref-egger1997bias">Egger et al. 1997</a>)</span> は、ファネルプロットの非対称性を検定する定量的手法としてよく利用されている。ファネルプロットの目視検証と同様に、小規模研究の効果を識別するだけで、出版バイアスが存在するかどうかを直接教えてくれるわけではない。この検定は、単純な線形回帰モデルに基づいており、その式は次のようになる。</p>
<p><span class="math display" id="eq:pub1">\[\begin{equation}
\frac{\hat\theta_k}{SE_{\hat\theta_k}} = \beta_0 + \beta_1 \frac{1}{SE_{\hat\theta_k}}
\tag{9.1}
\end{equation}\]</span></p>
<p>この式における応答変数 <span class="math inline">\(y\)</span> は、メタ分析で観測された効果量 <span class="math inline">\(\hat\theta_k\)</span> を、標準誤差で割ったものである。結果の値は、<span class="math inline">\(z\)</span> -スコアと同等である。これらのスコアは、効果量が有意であるかどうかを直接教えてくれる。<span class="math inline">\(z \geq\)</span> 1.96 または <span class="math inline">\(\leq\)</span> -1.96 のとき、その効果は有意であることがわかる ( <span class="math inline">\(p&lt;\)</span> 0.05)。この応答変数は、研究の標準誤差の逆数に回帰され、それは研究の精度に相当する。</p>
<p>しかし、Egger の検定を用いる場合、回帰重み <span class="math inline">\(\beta_1\)</span> の大きさや有意性にではなく、<strong>切片</strong> <span class="math inline">\(\beta_0\)</span> に関心がある。ファネルの非対称性を評価するためには、<span class="math inline">\(\hat\beta_0\)</span> のサイズを検査し、それがゼロから有意に異なるかどうかを調べる。この場合、Egger の検定は、ファネルプロットの非対称性を示す。</p>
<p>回帰切片の大きさが、なぜファネルプロットの非対称性について何かを伝えるのかを理解するために、少し時間をとろう。すべての線形回帰モデルにおいて、切片は他のすべての予測変数がゼロのときの <span class="math inline">\(y\)</span> の値を表している。モデルの予測変数は研究の精度なので、切片は精度がゼロの時 (すなわち、研究の標準誤差が無限に大きい時) に期待される <span class="math inline">\(z\)</span> -スコアを示す。</p>
<p>出版バイアスがない場合、期待される <span class="math inline">\(z\)</span> -スコアはゼロ付近に散らばるはずである。これは、標準誤差が極端に大きい研究は信頼区間も極端に大きくなり、<span class="math inline">\(|z| \geq\)</span> 1.96 という値になることはほぼ不可能である。しかし、出版バイアスの影響などでファンネルプロットが非対称になると、効果量が非常に大きい小規模な研究がかなり多くなり、<span class="math inline">\(z\)</span> 値が 1.96 以上の値を持つ精度の低い研究が驚くほど多くなることが予想される。この歪みにより、精度がゼロの時の <span class="math inline">\(y\)</span> の予測値はゼロより大きくなり、結果として有意な切片となる。</p>
<p>以下のプロットは、Egger の検定の基礎となる回帰の勾配と切片に対するファネルプロットの非対称性の影響を示している。</p>
<p><img src="images/eggers-1_sep.png" width="50%"><img src="images/eggers-2_sep.png" width="50%"><img src="images/eggers-3_sep.png" width="50%"><img src="images/eggers-4_sep.png" width="50%"></p>
<p></p>
<p>このような回帰モデルを <code>m.gen</code> のデータに当てはめると、どのような結果が得られるか見てみよう。 <em>R</em> を使って、<code>m.gen</code> の元データを取り出し、応答変数 <code>y</code> と予測変数 <code>x</code> を計算することが可能である。以下のコードでは、パイプ( Chapter <a href="discovering-R.html#data-transform">2.5.3</a> )と <strong>{tidyverse}</strong> の一部である <code>mutate</code> 関数を使用してこれを行う。その後、<strong>l</strong>inear <strong>m</strong>odel function <code>lm</code> を使って、<span class="math inline">\(z\)</span> のスコア <code>y</code> を精度 <code>x</code> に回帰している。パイプの最後の部分では、結果の <code>summary</code> を要求している。</p>
<div class="sourceCode" id="cb247"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># パッケージをロード</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">m.gen</span><span class="op">$</span><span class="va">data</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">TE</span><span class="op">/</span><span class="va">seTE</span>, x <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="va">seTE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [...]
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   4.1111     0.8790   4.677 0.000252 ***
## x            -0.3407     0.1837  -1.855 0.082140 .  
## ---
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## 
## [...]</code></pre>
<p>結果、この回帰モデルの切片は、<span class="math inline">\(\hat\beta_0\)</span> = 4.11 であることがわかる。これはゼロより有意に大きく ( <span class="math inline">\(t\)</span> = 4.677, <span class="math inline">\(p&lt;\)</span> 0.001)、ファネルプロットのデータが実際に非対称であることを示している。全体として、これは小規模研究の効果があるという最初の発見を裏づけるものである。しかし、繰り返しになるが、このパターンが出版バイアスに起因しているかどうかは不明である。</p>
<p>Egger の切片検定を行うより便利な方法は、<strong>{meta}</strong> にある <code>metabias</code> 関数を使用することである。この関数はメタ分析オブジェクトを入力として必要とし、<code>method.bias</code> 引数を <code>"linreg"</code> に設定する必要がある。この関数を <code>m.gen</code> に適用すると、以前と同じ結果が得られる。</p>
<div class="sourceCode" id="cb249"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/meta/man/metabias.html">metabias</a></span><span class="op">(</span><span class="va">m.gen</span>, method.bias <span class="op">=</span> <span class="st">"linreg"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Review:     Third Wave Psychotherapies
## 
## Linear regression test of funnel plot asymmetry
## 
## Test result: t = 4.68, df = 16, p-value = 0.0003
## 
## Sample estimates:
##    bias se.bias intercept se.intercept
##  4.1111  0.8790   -0.3407       0.1837
## 
## Details:
## - multiplicative residual heterogeneity variance (tau^2 = 1.2014)
## - predictor: standard error
## - weight:    inverse variance
## - reference: Egger et al. (1997), BMJ</code></pre>

<div class="boxreport">
<p><strong>Egger 検定の結果を報告</strong></p>
<p>Egger の検定では、通常、切片の値、その95%信頼区間、<span class="math inline">\(t\)</span> 値と <span class="math inline">\(p\)</span> 値を報告すれば十分である。<strong>{dmetar}</strong>パッケージでは、<code>eggers.test</code> という便利な関数が含まれている。この関数は <code>metabias</code> のラッパーであり、Eggerの検定の結果をレポートに適した形式で提供する。<strong>{dmetar}</strong> がインストールされていない場合は、この関数のソースコード <a href="https://raw.githubusercontent.com/MathiasHarrer/dmetar/master/R/eggers.test.R">online</a> を参照。以下はその例である。</p>
<p><code>eggers.test(m.gen)</code></p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="24%">
<col width="18%">
<col width="34%">
<col width="17%">
<col width="5%">
</colgroup>
<thead><tr class="header">
<th><span class="math inline">\(~\)</span></th>
<th><code>Intercept</code></th>
<th><code>ConfidenceInterval</code></th>
<th><code>t</code></th>
<th><code>p</code></th>
</tr></thead>
<tbody><tr class="odd">
<td><code>Egger's test</code></td>
<td><code>4.111</code></td>
<td><code>2.347-5.875</code></td>
<td><code>4.677</code></td>
<td><code>0.00025</code></td>
</tr></tbody>
</table></div>
</div>
<p></p>
<p><code>m.gen</code> で使われている効果量の指標は、スモールサンプルバイアス補正 SMD (Hedges’ <span class="math inline">\(g\)</span> ) である。SMD で Egger 検定を実行すると、偽陽性の結果が膨らむ可能性があると議論されている <span class="citation">(<a href="references.html#ref-pustejovsky2019testing">J. E. Pustejovsky and Rodgers 2019</a>)</span>。これは、研究の標準化平均差と標準誤差が独立していないためである。</p>
<p>このことは、群間 SMD の標準誤差を計算するための式 (式 3.18、Chapter <a href="effects.html#b-group-smd">3.3.1.2</a>) を見れば簡単にわかる。この式は SMD そのものを含んでおり、観察された効果の値が小さくても大きくても研究の標準誤差が変化することを意味している (つまり、SMD とその標準誤差の間には人為的な相関がある)。</p>
<p>Pustejovsky and Rodgers <span class="citation">(<a href="references.html#ref-pustejovsky2019testing">2019</a>)</span> は、標準化平均差のファネルプロットの非対称性を検定する際に、標準誤差の修正版を使用することを提案している。標準誤差の式の最初の部分だけが使用され、観察された効果量が式から脱落することを意味している。したがって、式は次のようになる。</p>
<p><span class="math display" id="eq:pub2">\[\begin{equation}
SE^*_{\text{SMD}_{\text{between}}}= \sqrt{\frac{n_1+n_2}{n_1n_2}}
\tag{9.2}
\end{equation}\]</span></p>
<p>ここで、<span class="math inline">\(SE^*_{\text{SMD}_{\text{between}}}\)</span> は標準誤差の修正版である。この修正版を使ったときに、Egger の検定が同じ結果を与えるかどうかを確認するのはよい考えだろう。次のコードでは、最初のデータセットに各研究の各群のサンプルサイズを追加し、適合された標準誤差を計算し、それを使って分析を再実行する。</p>
<div class="sourceCode" id="cb251"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 実験群 (n1) と対照群 (n2) のサンプルサイズを追加</span></span>
<span><span class="va">n1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">62</span>, <span class="fl">72</span>, <span class="fl">44</span>, <span class="fl">135</span>, <span class="fl">103</span>, <span class="fl">71</span>, <span class="fl">69</span>, <span class="fl">68</span>, <span class="fl">95</span>, </span>
<span>        <span class="fl">43</span>, <span class="fl">79</span>, <span class="fl">61</span>, <span class="fl">62</span>, <span class="fl">60</span>, <span class="fl">43</span>, <span class="fl">42</span>, <span class="fl">64</span>, <span class="fl">63</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">51</span>, <span class="fl">78</span>, <span class="fl">41</span>, <span class="fl">115</span>, <span class="fl">100</span>, <span class="fl">79</span>, <span class="fl">62</span>, <span class="fl">72</span>, <span class="fl">80</span>, </span>
<span>        <span class="fl">44</span>, <span class="fl">72</span>, <span class="fl">67</span>, <span class="fl">59</span>, <span class="fl">54</span>, <span class="fl">41</span>, <span class="fl">51</span>, <span class="fl">66</span>, <span class="fl">55</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 修正標準誤差を表示</span></span>
<span><span class="va">ThirdWave</span><span class="op">$</span><span class="va">seTE_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">(</span><span class="va">n1</span><span class="op">+</span><span class="va">n2</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="va">n1</span><span class="op">*</span><span class="va">n2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 修正標準誤差で 'metagen' を再実行し、メタ分析オブジェクトを取得</span></span>
<span><span class="va">m.gen.c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/meta/man/metagen.html">metagen</a></span><span class="op">(</span>TE <span class="op">=</span> <span class="va">TE</span>, seTE <span class="op">=</span> <span class="va">seTE_c</span>,</span>
<span>                   studlab <span class="op">=</span> <span class="va">Author</span>, data <span class="op">=</span> <span class="va">ThirdWave</span>, sm <span class="op">=</span> <span class="st">"SMD"</span>, </span>
<span>                   fixed <span class="op">=</span> <span class="cn">FALSE</span>, random <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>                   method.tau <span class="op">=</span> <span class="st">"REML"</span>, hakn <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>                   title <span class="op">=</span> <span class="st">"Third Wave Psychotherapies"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Egger 検定</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/meta/man/metabias.html">metabias</a></span><span class="op">(</span><span class="va">m.gen.c</span>, method <span class="op">=</span> <span class="st">"linreg"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Review:     Third Wave Psychotherapies
## 
## Linear regression test of funnel plot asymmetry
## 
## Test result: t = 4.36, df = 16, p-value = 0.0005
## 
## Sample estimates:
##     bias se.bias intercept se.intercept
##  11.1903  2.5667   -1.3535       0.4432
## 
## Details:
## - multiplicative residual heterogeneity variance (tau^2 = 2.5334)
## - predictor: standard error
## - weight:    inverse variance
## - reference: Egger et al. (1997), BMJ</code></pre>
<p>正確な数値は異なるものの、結果の解釈は同じであることがわかる。このことは、以前発見したことが確からしいことを示している。</p>

<div class="boxinfo">
<p><strong><code>metabias</code> で直接 Pustejovsky-Rodgers 法を使う</strong></p>
<p>最新の <strong>{meta}</strong> では、<code>metabias</code> 関数に、Pustejovsky and Rodgers によって提案された補正標準誤差の式で Egger の検定を行うオプションも用意されている。このオプションは <code>method.bias</code> を <code>"Pustejovsky"</code> に設定することで使用でる。</p>
<p>ただし、これは <strong>{meta}</strong> メタ分析オブジェクトが、実験グループとコントロールグループのサンプルサイズをそれぞれ <code>n.e</code> と <code>n.c</code> という要素で既に含んでいる場合にのみ可能である。<code>metagen</code> オブジェクトを使用する場合 (上記の例のように)、通常はこのようなことはないため、手動で追加する必要がある。例として、再び <code>m.gen</code> メタ分析オブジェクトを使用してみよう。</p>
<p><code>m.gen$n.e = n1; m.gen$n.c = n2</code></p>
<p><code>metabias(m.gen, method.bias = "Pustejovsky")</code></p>
<p>なお、この設定では、<code>metabias</code> は Egger の検定を行うために式 <a href="pub-bias.html#eq:pub5">(9.5)</a> を使用するが、これは先に示した式 <a href="pub-bias.html#eq:pub1">(9.1)</a> と等価である。主な違いは、<code>metabias</code> がモデルの予測因子として補正標準誤差を用い、重みとして含まれる効果量の逆分散を用いる点である。</p>
<p>しかし、今回の例では、式 <a href="pub-bias.html#eq:pub1">(9.1)</a> の両辺に補正された標準誤差を使用している。つまり、上記のようなアプローチと <code>method.bias</code> を <code>"Pustejovsky"</code> に設定した場合の結果は完全に一致するわけではない。</p>
</div>
<p><br></p>
</div>
<div id="peters-test" class="section level4" number="9.2.1.3">
<h4>
<span class="header-section-number">9.2.1.3</span> Peters の回帰検定<a class="anchor" aria-label="anchor" href="#peters-test"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p></p>
<p>効果量と標準誤差の依存性は、標準化された平均差にのみ適用されるわけではない。この数学的な関連性は、(対数) オッズ比 (Chapter <a href="effects.html#or">3.3.2.2</a>) やリスク比 (Chapter <a href="effects.html#rr">3.3.2.1</a>) などの二値アウトカムデータまたは割合 (Chapter <a href="effects.html#props">3.2.2</a>) に基づく効果量にも存在する。</p>
<p>二値効果量データを使用したときの偽陽性のリスクの増大を避けるために、Peters et al <span class="citation">(<a href="references.html#ref-peters2006comparison">Peters et al. 2006</a>)</span> が提案した別のタイプの回帰検定を使用することが可能である。Peters の検定の結果を得るために、対数変換された効果量をサンプルサイズの逆数に回帰させる。</p>
<p><span class="math display" id="eq:pub3">\[\begin{equation}
\log\psi_k =  \beta_0 + \beta_1\frac{1}{n_k}
\tag{9.3}
\end{equation}\]</span></p>
<p>この式において、<span class="math inline">\(\log\psi_k\)</span> は二値アウトカムデータに基づく任意の対数変換効果量 (例えば、オッズ比) を表し、<span class="math inline">\(n_k\)</span> は研究 <span class="math inline">\(k\)</span> の総サンプルサイズである。</p>
<p></p>
<p>重要なことは、回帰モデルを当てはめるとき、各研究 <span class="math inline">\(k\)</span> には、そのサンプルサイズとイベントカウントに応じて、異なる重み <span class="math inline">\(w_k\)</span> が付けられることである。この結果、<strong>重み付け</strong>線形回帰となり、メタ回帰モデル (Chapter <a href="metareg.html#metareg-model-fit">8.1.3</a>) と似ている (同一ではない)。重みの式 <span class="math inline">\(w_k\)</span> は次のようなものである。</p>
<p><span class="math display" id="eq:pub4">\[\begin{equation}
w_k = \frac{1}{\left(\dfrac{1}{a_k+c_k}+\dfrac{1}{b_k+d_k}\right)}
\tag{9.4}
\end{equation}\]</span></p>
<p>ここで、<span class="math inline">\(a_k\)</span> は治療群でのイベント数、<span class="math inline">\(c_k\)</span> は対照群でのイベント数である。<span class="math inline">\(b_k\)</span> と <span class="math inline">\(d_k\)</span> はそれぞれ治療群と対照群での非イベントの数である (Chapter <a href="effects.html#rr">3.3.2.1</a> を参照)。Egger の回帰検定とは対照的に、Peters の検定は、切片の代わりに <span class="math inline">\(\beta_1\)</span> を使って、ファネルプロットの非対称性を検定した。統計的検定が <span class="math inline">\(\beta_1 \neq 0\)</span> を明らかにするとき、データに非対称性が存在すると仮定することが可能である。</p>
<p><code>metabin</code> (Chapter <a href="pooling-es.html#pooling-or-rr">4.2.3.1</a>) または <code>metaprop</code> (Chapter <a href="pooling-es.html#pooling-props">4.2.6</a>) 関数を用いて二値アウトカムに基づくメタ分析を計算した場合、 <code>metabias</code> 関数を用いて Peters 検定 を実施することが可能である。適合するメタ分析オブジェクトを用意し、<code>method.bias</code> の引数に <code>"peters"</code> を指定するだけでよい。Chapter <a href="pooling-es.html#pooling-or-rr">4.2.3.1</a> で作成した <code>m.bin</code> オブジェクトで、ファネルプロットの非対称性を確認してみよう。</p>
<p>覚えているだろうが、このメタ分析ではリスク比を要約の指標として使った。</p>
<div class="sourceCode" id="cb253"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/meta/man/metabias.html">metabias</a></span><span class="op">(</span><span class="va">m.bin</span>, method.bias <span class="op">=</span> <span class="st">"peters"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Review:     Depression and Mortality
## 
## Linear regression test of funnel plot asymmetry
## 
## Test result: t = -0.08, df = 16, p-value = 0.9368
## 
## Sample estimates:
##      bias  se.bias intercept se.intercept
##  -11.1728 138.6121    0.5731       0.1076
## 
## Details:
## - multiplicative residual heterogeneity variance (tau^2 = 40.2747)
## - predictor: inverse of total sample size
## - weight:    inverse variance of average event probability
## - reference: Peters et al. (2006), JAMA</code></pre>
<p>出力の構造は、Egger の検定と同じであることがわかる。出力は、結果が <code>サンプルサイズに基づく回帰検定</code>のものであることを示しおり、これは Peters の方法が使用されたことを意味している。検定は有意ではなく (<span class="math inline">\(t\)</span> = -0.08, <span class="math inline">\(p\)</span> = 0.94)、ファンネルプロットは非対称ではないことを示している。</p>
<div class="boximportant">
<p>
<strong>ファネルプロット非対称性検定の統計的検出力</strong>
</p>
<p>
メタ分析に十分な数の研究が含まれている場合のみ、ファネルプロットの非対称性を検定することが推奨される。研究数が少ない場合、Egger
の検定や Peters
の検定の統計的検出力が、実際の非対称性を検出するのに十分でないことがある。一般に、<span class="math inline"><span class="math inline">\(K \geq 10\)</span></span>
のときだけ検定を行うことが推奨されている <span class="citation"><span class="citation">(<a href="references.html#ref-sterne2011recommendations">Sterne et al. 2011</a>)</span></span> 。
</p>
<p>
デフォルトでは、メタアナリシスの研究数がこれより少ないと
<code>metabias</code> はエラーを出す。しかし、関数内の
<code>k.min</code>
引数をより小さい数字に設定することで、これを防ぐことができる
(推奨はしない)。
</p>
</div>
<p><br></p>
</div>
<div id="duval-and-tweedie" class="section level4" number="9.2.1.4">
<h4>
<span class="header-section-number">9.2.1.4</span> Duval &amp; Tweedie トリム＆フィル方式<a class="anchor" aria-label="anchor" href="#duval-and-tweedie"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p></p>
<p>メタ分析において、小規模研究の効果を調べる (そして検定する) 方法をいくつか学んだ。データに出版バイアスが存在する可能性があることを知ることは良いことであるが、主に関心を持っているのは、そのバイアスの<strong>大きさ</strong>である。出版バイアスが推定値をわずかに歪めただけなのか、それとも知見の解釈を変えるほど大規模なものなのかを知りたい。</p>
<p>つまり、真の効果量の<strong>バイアス補正</strong>推定値を算出する方法が必要なのである。しかし、出版バイアスを直接測定することができないことをすでに学んだ。出版バイアスを<strong>指摘</strong>する可能性のある代理として、小規模研究の効果を使うことしかできない。</p>
<p>したがって、出版バイアス<strong>そのもの</strong>ではなく、補正された効果推定値を得るために小規模研究の影響を補正することができるだけである。効果量の非対称性が実際に出版バイアスによって引き起こされた場合、この不均衡を補正することで、<strong>すべての</strong>エビデンスを考慮したときに真の効果をよりよく表す推定値が得られる。</p>
<p>ファネルプロットの非対称性を調整する最も一般的な方法の1つが、<strong>Duval &amp; Tweedie トリム＆フィル法</strong> <span class="citation">(<a href="references.html#ref-duval2000trim">Duval and Tweedie 2000</a>)</span> である。この方法の背後にある考え方は単純で、ファネルプロットが対称になるまで「欠損」効果を埋め込むというものである。そして、得られた「拡張」データセットのプール効果量は、小規模研究の効果を補正する際の推定値を表した。これは、効果の「トリム」 (trim) と「フィル」 (fill) を含む簡単なアルゴリズムによって達成される <span class="citation">(<a href="references.html#ref-schwarzer2015meta">Schwarzer, Carpenter, and Rücker 2015</a>、5.3.1章)</span>。</p>
<ul>
<li><p><strong>トリム</strong>. まず、このメソッドはファネルプロット内のすべての外れ値研究を識別する。先ほどの例では、これらはプロットの右側に散在しているすべての小規模な研究である。いったん識別されると、これらの研究は <strong>トリム</strong>、つまり分析から取り除かれ、プールされた効果は、これを除いて再計算される。このステップは、通常、固定効果モデルを使用して実行される。</p></li>
<li><p><strong>フィル</strong>. 次のステップでは、再計算されたプール効果が、すべての効果量の中心と仮定される。トリムされた各研究について、漏斗の反対側でその結果を反映するように、1つの効果量が追加される。たとえば、再計算された平均効果が0.5で、トリムされた研究の効果が0.8であれば、ミラーされた研究は0.2の効果を与えられる。これをすべてのトリムされた研究で行うと、ファネルプロットはほぼ対称的に見える。トリムされた効果量と帰属された効果量を含むすべてのデータに基づいて、平均効果量が再計算される (通常、ランダム効果モデルを使用する)。その結果は、補正されたプール効果量の推定値として使用される。</p></li>
</ul>
<p>トリム＆フィル法に関する重要な注意点は、研究間の異質性が大きい場合、信頼できる結果が得られないことである <span class="citation">(<a href="references.html#ref-peters2007performance">Peters et al. 2007</a>; <a href="references.html#ref-terrin2003adjusting">Terrin et al. 2003</a>; <a href="references.html#ref-simonsohn2014p">Simonsohn, Nelson, and Simmons 2014b</a>)</span>。研究が1つの真の効果を共有していない場合、大規模な研究でも平均的な効果から大きく乖離している可能性がある。つまり、出版バイアスの影響を受けている可能性が低いにもかかわらず、そのような研究もトリムされて埋められることになる。これでは、無効な結果になることは容易に想像がつく。</p>
<p><strong>{meta}</strong> にある <code>trimfill</code> 関数を使用するとトリム＆フィルアルゴリズムをデータに適用することが可能である。この関数は非常にわかりやすいデフォルト値を持っているので、メタ分析オブジェクトと一緒に提供するだけで十分である。この例では、再び <code>m.gen</code> オブジェクトを使用する。しかし、その前に、まず、このメタ分析で観察された <span class="math inline">\(I^2\)</span> 異質性の量を確認してみよう。</p>
<div class="sourceCode" id="cb255"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m.gen</span><span class="op">$</span><span class="va">I2</span></span></code></pre></div>
<pre><code>## [1] 0.6263947</code></pre>
<p><span class="math inline">\(I^2\)</span> = 63% で、この分析における異質性はかなりのものであることがわかる。異質なデータセットにおけるトリム＆フィル法の限界を考慮すると、これは問題であることがわかる。</p>
<p>そのため、2 つのトリム＆フィル分析を行う。1 つは全研究を対象とした分析で、もう 1 つは Chapter <a href="heterogeneity.html#outliers">5.4</a> (すなわち、研究 3 と 16)。その結果を <code>tf</code> と <code>tf.no.out</code> に保存する。</p>
<div class="sourceCode" id="cb257"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 全ての研究を使用</span></span>
<span><span class="va">tf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/trimfill.html">trimfill</a></span><span class="op">(</span><span class="va">m.gen</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 外れ値を外して解析</span></span>
<span><span class="va">tf.no.out</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/trimfill.html">trimfill</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">m.gen</span>, </span>
<span>                             subset <span class="op">=</span> <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">16</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>まず、全研究を対象とした 1 つ目の分析を見てみよう。</p>
<div class="sourceCode" id="cb258"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">tf</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Review:     Third Wave Psychotherapies
##                              SMD             95%-CI %W(random)
## [...]
## Filled: Warnecke et al.   0.0520 [-0.4360;  0.5401]        3.8
## Filled: Song &amp; Lindquist  0.0395 [-0.4048;  0.4837]        4.0
## Filled: Frogeli et al.    0.0220 [-0.3621;  0.4062]        4.2
## Filled: Call et al.      -0.0571 [-0.5683;  0.4541]        3.8
## Filled: Gallego et al.   -0.0729 [-0.5132;  0.3675]        4.0
## Filled: Kang et al.      -0.6230 [-1.2839;  0.0379]        3.3
## Filled: Shapiro et al.   -0.8277 [-1.4456; -0.2098]        3.4
## Filled: DanitzOrsillo    -1.1391 [-1.8164; -0.4618]        3.3
## 
## Number of studies combined: k = 26 (with 8 added studies)
## 
##                         SMD           95%-CI    t p-value
## Random effects model 0.3428 [0.1015; 0.5841] 2.93  0.0072
## 
## Quantifying heterogeneity:
##  tau^2 = 0.2557 [0.1456; 0.6642]; tau = 0.5056 [0.3816; 0.8150];
##  I^2 = 76.2% [65.4%; 83.7%]; H = 2.05 [1.70; 2.47]
## 
## [...]
## 
## Details on meta-analytical method:
## - Inverse variance method
## - Restricted maximum-likelihood estimator for tau^2
## - Q-profile method for confidence interval of tau^2 and tau
## - Hartung-Knapp adjustment for random effects model
## - Trim-and-fill method to adjust for funnel plot asymmetry</code></pre>
<p>トリムとフィルの手順で、合計 8 件の研究が追加されたことがわかる。トリムとフィルの研究には、すでに検出した外れ値だけでなく、比較的高い効果を持つ他のいくつかの小さな研究も含まれている。移植された効果量はすべて非常に低く、大きくマイナスなものも複数あることがわかる。出力はまた、補正された効果の推定値を提供し、それは <span class="math inline">\(g=\)</span> 0.34 である。これはまだ有意であるが、最初に <code>m.gen</code> に対して計算した <span class="math inline">\(g=\)</span> 0.58という効果よりはるかに低いものである。</p>
<p>では、外れ値を取り除いた解析結果と比較してみよう。</p>
<div class="sourceCode" id="cb260"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">tf.no.out</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Review:     Third Wave Psychotherapies
## [...]     
## 
## Number of studies combined: k = 22 (with 6 added studies)
## 
##                         SMD           95%-CI    t p-value
## Random effects model 0.3391 [0.1904; 0.4878] 4.74  0.0001
## 
## Quantifying heterogeneity:
##  tau^2 = 0.0421 [0.0116; 0.2181]; tau = 0.2053 [0.1079; 0.4671];
##  I^2 = 50.5% [19.1%; 69.7%]; H = 1.42 [1.11; 1.82]
## [...]</code></pre>
<p><span class="math inline">\(g=\)</span> 0.34 では、結果はほぼ同じである。全体として、トリム＆フィル法は、このメタ分析における <span class="math inline">\(g=\)</span> 0.58 のプール効果は、小規模研究の効果により過大評価されていることを示している。実際には、効果はかなり小さいと思われる。この過大評価は出版バイアスに起因する可能性が高いが、確実ではない。他の説明も可能であり、このことはトリム＆フィル推定が無効である可能性がある。</p>
<p>最後に、インプットされた研究を含むファネルプロットを作成することも可能である。<code>funnel.meta</code> 関数を <code>trimfill</code> の出力に適用するだけである。以下のコードでは、トリム＆フィルの両方の分析 (外れ値あり、なし) に対して、等高線ファネルプロットを作成している。<code>par</code> 関数を使用すると、両方のプロットを並べて表示すことが可能である。</p>
<div class="sourceCode" id="cb262"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 等高線の塗りつぶし色を定義</span></span>
<span><span class="va">contour</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.9</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span><span class="op">)</span></span>
<span><span class="va">col.contour</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"gray75"</span>, <span class="st">"gray85"</span>, <span class="st">"gray95"</span><span class="op">)</span></span>
<span><span class="va">ld</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"p &lt; 0.1"</span>, <span class="st">"p &lt; 0.05"</span>, <span class="st">"p &lt; 0.01"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 'par' を使って１行に表示</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 等高線ファンネルプロット (全てのデータ) </span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/meta/man/funnel.meta.html">funnel.meta</a></span><span class="op">(</span><span class="va">tf</span>, </span>
<span>            xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1.5</span>, <span class="fl">2</span><span class="op">)</span>, contour <span class="op">=</span> <span class="va">contour</span>,</span>
<span>            col.contour <span class="op">=</span> <span class="va">col.contour</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/PerformanceAnalytics/man/legend.html">legend</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1.1</span>, y <span class="op">=</span> <span class="fl">0.01</span>, </span>
<span>       legend <span class="op">=</span> <span class="va">ld</span>, fill <span class="op">=</span> <span class="va">col.contour</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/title.html">title</a></span><span class="op">(</span><span class="st">"Funnel Plot (Trim &amp; Fill Method)"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 等高線ファンネルプロット (外れ値は除去) </span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/meta/man/funnel.meta.html">funnel.meta</a></span><span class="op">(</span><span class="va">tf.no.out</span>, </span>
<span>            xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1.5</span>, <span class="fl">2</span><span class="op">)</span>, contour <span class="op">=</span> <span class="va">contour</span>,</span>
<span>            col.contour <span class="op">=</span> <span class="va">col.contour</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/PerformanceAnalytics/man/legend.html">legend</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1.1</span>, y <span class="op">=</span> <span class="fl">0.01</span>, </span>
<span>       legend <span class="op">=</span> <span class="va">ld</span>, fill <span class="op">=</span> <span class="va">col.contour</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/title.html">title</a></span><span class="op">(</span><span class="st">"Funnel Plot (Trim &amp; Fill Method) - Outliers Removed"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-226-1.png" width="1152"></div>
<p>この二つのファネルプロットでは、インプットされた研究は塗りつぶしの色がない円で表されている。</p>
<p><br></p>
</div>
<div id="pet-peese" class="section level4" number="9.2.1.5">
<h4>
<span class="header-section-number">9.2.1.5</span> PET-PEESE<a class="anchor" aria-label="anchor" href="#pet-peese"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p>
</p>
<p>Duval &amp; Tweedie のトリム＆フィル法は比較的古く、間違いなく小規模研究の効果を調整する最も一般的な方法の 1 つである。しかし、前述したように完璧とは言い難いアプローチであり、プール効果のバイアス補正版を推定する唯一の方法というわけではない。近年、<strong>PET-PEESE</strong> <span class="citation">(<a href="references.html#ref-stanley2014meta">T. D. Stanley and Doucouliagos 2014</a>; <a href="references.html#ref-stanley2008meta">T. D. Stanley 2008</a>)</span> という手法が、特に SMD がアウトカムとして頻繁に使われる研究分野 (例えば、心理学や教育研究) で、ますます人気が出てきている。これまでのすべての手法と同様に、PET-PEESE は、出版バイアスの潜在的な指標とみなされる小規模研究の効果に狙いを定めている。</p>
<p>PET-PEESE は、実際には、<strong>精密効果検定</strong> (precision-effect test, PET) と<strong>標準誤差付き精密効果推定</strong> (precision-effect estimate with standard error, PEESE) の 2 つの手法を組み合わせたものである。まず、前者から説明しよう。PET 法は、研究の効果量をその標準誤差に回帰させるという単純な回帰モデルに基づいている。</p>
<p><span class="math display" id="eq:pub5">\[\begin{equation}
\theta_k =  \beta_0 + \beta_1SE_{\theta_k}
\tag{9.5}
\end{equation}\]</span></p>
<p>Peters の検定と同じように、重み付き回帰を使用する。研究の重み <span class="math inline">\(w_k\)</span> は、分散の逆数として計算される–通常の (固定効果) メタ分析と同じである。</p>
<p><span class="math display" id="eq:pub6">\[\begin{equation}
w_k = \frac{1}{s_k^2}
\tag{9.6}
\end{equation}\]</span></p>
<p>注目すべきは、PET 法で使用される回帰モデルは、Egger の検定のものと同等であることである。主な違いは、PET 式では、<span class="math inline">\(\beta_1\)</span> 係数がファネルの非対称性を定量化し、Egger の検定では、これが切片によって示されることである。</p>
<p></p>
<p>しかし、PET 法を用いる場合、<span class="math inline">\(\beta_1\)</span> で測定されるファネルの非対称性には関心がなく、切片 <span class="math inline">\(\beta_0\)</span> に関心がある。これは、上の式で、切片がいわゆる<strong>限界効果</strong> (limit effect) を表していることがある。この限界効果は、<strong>標準誤差が0</strong>の研究の期待効果量である。これは、サンプル誤差なしに測定された観察された効果量に相当する。すべてが同じであれば、サンプリング・エラーなしで測定された効果量 <span class="math inline">\(\epsilon_k\)</span> は、真の全体的な効果そのものを表すことが分かっている。</p>
<p>PET 法の背後にある考え方は、予測因子として標準誤差を含めることによって、小規模研究の効果を<strong>制御</strong>することである。理論的には、これは、すべての小規模研究の効果に対する補正後のメタ分析における真の効果を表す切片 <span class="math inline">\(\beta_0\)</span> につながるはずである。</p>
<p><span class="math display" id="eq:pub7">\[\begin{equation}
\hat\theta_{\text{PET}} = \hat\beta_{0_{\mathrm{PET}}}
\tag{9.7}
\end{equation}\]</span></p>
<p>PEESE 法の式は、非常によく似ている。唯一の違いは、<strong>二乗</strong>標準誤差を予測変数として使用することである (すなわち、効果量の分散 <span class="math inline">\(s_k^2\)</span>)。</p>
<p><span class="math display" id="eq:pub8">\[\begin{equation}
\theta_k =  \beta_0 + \beta_1SE_{\theta_k}^2
\tag{9.8}
\end{equation}\]</span></p>
<p>研究重みの計算式 <span class="math inline">\(w_k\)</span> は変わらないが。標準誤差の二乗の背後にある考え方は、小規模の研究は、特に<strong>非常に</strong>過剰に推定された効果を報告しやすいということである。この問題は、高い統計的検出力を持つ研究では、それほど顕著にはならないことが推測される。</p>
<p>PET 法は、<span class="math inline">\(\beta_0\)</span> が捉えた真の効果が<strong>ゼロ</strong>のときに最もよく機能するのに対し、PEESE は真の効果が<strong>ゼロでない</strong>ときによりよい性能を示す。Stanley and Doucouliagos <span class="citation">(<a href="references.html#ref-stanley2014meta">2014</a>)</span> は、それぞれの長所をバランスさせるために、両方の方法を結合することを提案してきた。その結果生まれたアプローチがPET-PEESE 法である。PET-PEESE は、PET または PEESE の切片 <span class="math inline">\(\beta_0\)</span> を、補正された真の効果の推定値として使用する。</p>
<p>PET と PEESE のどちらを使用するかは、PET 法で計算された切片のサイズに依存する。<span class="math inline">\(\beta_{0_{\text{PET}}}\)</span> が、<span class="math inline">\(\alpha\)</span> = 0.05 の片側検定で、ゼロより有意に大きい場合、PEESE の切片を真の効果量推定値として使用する。PET の切片が0より有意に大きくない場合、PET 推定値のままである。</p>
<p><em>R</em> で回帰モデルを実装する場合、ほとんどの場合、両側検定で係数の有意性を検定するのが通例である (つまり、<span class="math inline">\(\beta\)</span> の重みが 0 と有意に異なるかどうかを、方向に関係なく検定する)。<span class="math inline">\(\alpha\)</span> = 0.05 で片側検定を仮定すると、<span class="math inline">\(p\)</span> &lt; 0.1、および <span class="math inline">\(\beta_0\)</span> の推定値がゼロより大きいとき、すでに切片が有意であるとみなす<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;後者の条件 (&lt;span class="math inline"&gt;\(\hat\beta_0\)&lt;/span&gt; &amp;gt; 0) は、正の効果量が好ましい結果 (たとえば、正の効果量は介入が有効だったことを意味する) である場合にのみ適用される。負の効果量 (たとえば、SMD = -0.5) が有利なアウトカムを表す場合、片側検定は反対方向になるはずである。これは、PET の切片の &lt;span class="math inline"&gt;\(p\)&lt;/span&gt;-値が0.1より小さく、切片推定値が 0 より&lt;strong&gt;小さい&lt;/strong&gt;とき、PEESE が使用されることを意味する&lt;/p&gt;'><sup>35</sup></a>。</p>
<p>したがって、PET-PEESE によって推定される真の効果量を求めるルールは次のようになる。</p>
<p><span class="math display" id="eq:pub9">\[\begin{equation}
  \hat\theta_{\text{PET-PEESE}}=\begin{cases}
    \mathrm{P}(\beta_{0_{\text{PET}}} = 0) &lt;0.1~\mathrm{and}~\hat\beta_{0_{\text{PET}}} &gt; 0: &amp; \hat\beta_{0_{\text{PEESE}}}\\
    \text{else}: &amp; \hat\beta_{0_{\text{PET}}}.
  \end{cases}
  \tag{9.9}
\end{equation}\]</span></p>
<p>この if-else のロジックを理解するのはやや難しいが、実際の例で説明すると分かりやすいだろう。<code>m.gen</code> メタ分析オブジェクトを使用して、PET-PEESE の真の効果量の推定値を見てみよう。</p>
<p>現在、<strong>{meta}</strong> における PET-PEESE の素直な実装はないので、線形モデル関数 <code>lm</code> を使用して独自のコードを記述する。しかし、PET と PEESE モデルを適合させる前に、まず、データフレームに必要なすべての変数を準備する必要がある。このデータフレームを <code>dat.petpeese</code> と呼ぶ。最も重要な変数は、もちろん、標準化平均差である。最初に <code>metacont</code> または <code>metagen</code> を使用してメタ分析を実行しても、各研究の計算されたSMDは、常にメタ分析オブジェクトの <code>TE</code> の下に格納される。</p>
<div class="sourceCode" id="cb263"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Build data set, starting with the effect size</span></span>
<span><span class="va">dat.petpeese</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>TE <span class="op">=</span> <span class="va">m.gen</span><span class="op">$</span><span class="va">TE</span><span class="op">)</span></span></code></pre></div>
<p></p>
<p>次に、効果量の標準誤差が必要である。PET-PEESE では、Pustejovsky and Rodgers <span class="citation">(<a href="references.html#ref-pustejovsky2019testing">2019</a>, Chapter <a href="pub-bias.html#eggers-test">9.2.1.2</a> を参照)</span> が提案した修正標準誤差 を使用するとよい<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;James Pustejovsky もこの方法を&lt;a href="https://www.jepusto.com/pet-peese-performance/"&gt;ブログ記事&lt;/a&gt;で推奨していて、この代替方法を「SPET-SPEESE」と呼んでいる&lt;/p&gt;'><sup>36</sup></a>。</p>
<p>そこで、効果量そのものと相関がないように、修正標準誤差 <code>seTE_c</code> を算出するために適応された式を使用する。また、この変数を <code>dat.petpeese</code> に保存する。さらに、PEESE の予測因子として必要なので、<strong>二乗</strong>標準誤差を含む変数 <code>seTE_c2</code> を追加する。</p>
<div class="sourceCode" id="cb264"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 実験群ｎ (n1) と対照群 (n2) のサンプルサイズ</span></span>
<span><span class="va">n1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">62</span>, <span class="fl">72</span>, <span class="fl">44</span>, <span class="fl">135</span>, <span class="fl">103</span>, <span class="fl">71</span>, <span class="fl">69</span>, <span class="fl">68</span>, <span class="fl">95</span>, </span>
<span>        <span class="fl">43</span>, <span class="fl">79</span>, <span class="fl">61</span>, <span class="fl">62</span>, <span class="fl">60</span>, <span class="fl">43</span>, <span class="fl">42</span>, <span class="fl">64</span>, <span class="fl">63</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">51</span>, <span class="fl">78</span>, <span class="fl">41</span>, <span class="fl">115</span>, <span class="fl">100</span>, <span class="fl">79</span>, <span class="fl">62</span>, <span class="fl">72</span>, <span class="fl">80</span>, </span>
<span>        <span class="fl">44</span>, <span class="fl">72</span>, <span class="fl">67</span>, <span class="fl">59</span>, <span class="fl">54</span>, <span class="fl">41</span>, <span class="fl">51</span>, <span class="fl">66</span>, <span class="fl">55</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 修正標準誤差を計算</span></span>
<span><span class="va">dat.petpeese</span><span class="op">$</span><span class="va">seTE_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">(</span><span class="va">n1</span><span class="op">+</span><span class="va">n2</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="va">n1</span><span class="op">*</span><span class="va">n2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 修正標準誤差の二乗 (分散) を追加</span></span>
<span><span class="va">dat.petpeese</span><span class="op">$</span><span class="va">seTE_c2</span> <span class="op">&lt;-</span> <span class="va">dat.petpeese</span><span class="op">$</span><span class="va">seTE_c</span><span class="op">^</span><span class="fl">2</span></span></code></pre></div>
<p>最後に、各研究の逆分散重み付け <code>w_k</code> を計算する必要がある。ここで、分散の推定値を得るために、二乗修正標準誤差も使用する。</p>
<div class="sourceCode" id="cb265"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat.petpeese</span><span class="op">$</span><span class="va">w_k</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">/</span><span class="va">dat.petpeese</span><span class="op">$</span><span class="va">seTE_c</span><span class="op">^</span><span class="fl">2</span></span></code></pre></div>
<p>これで、 <code>dat.petpeese</code> には、PET と PEESE の重み付き線形回帰モデルを適合させるために必要なすべての変数が含まれるようになった。次のコードでは、両方のモデルを適合し、<code>summary</code> 関数を使用して推定係数を直接表示する。以下が得られた結果である。</p>
<div class="sourceCode" id="cb266"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># PET</span></span>
<span><span class="va">pet</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">TE</span> <span class="op">~</span> <span class="va">seTE_c</span>, weights <span class="op">=</span> <span class="va">w_k</span>, data <span class="op">=</span> <span class="va">dat.petpeese</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">pet</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span></span></code></pre></div>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -1.353476   0.443164 -3.054119 0.0075732464
## seTE_c      11.190288   2.566719  4.359764 0.0004862409</code></pre>
<div class="sourceCode" id="cb268"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># PEESE</span></span>
<span><span class="va">peese</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">TE</span> <span class="op">~</span> <span class="va">seTE_c2</span>, weights <span class="op">=</span> <span class="va">w_k</span>, data <span class="op">=</span> <span class="va">dat.petpeese</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">peese</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span></span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -0.4366495  0.2229352 -1.958639 0.0678222117
## seTE_c2     33.3609862  7.1784369  4.647389 0.0002683009</code></pre>
<p>PET と PEESE のどちらを使うべきかを判断するため、まず PET 法の結果を見る必要がある。限界推定値は、<span class="math inline">\(g\)</span> = -1.35 であることがわかる。この効果は有意であるが (<span class="math inline">\(p\)</span> &lt; 0.10)、ゼロよりかなり小さいので、PET 推定値を使用すべきことがわかる。</p>
<p>しかし、<span class="math inline">\(g\)</span> = -1.35 では、バイアス補正効果の PET の推定値はあまり信頼できない。これは、現実には、研究対象の介入タイプは関心のあるアウトカムに対して非常に負の効果を持つ。つまり、実際には非常に有害であることを示す。これは非常に考えにくいことである。「善意の」介入に効果がないことはありうるが、本当に危険な介入を見つけることは非常にまれである。</p>
<p>実は、この結果に見られるのは、PET-PEESE の一般的な限界である。観測された効果量はすべて正符号であるにもかかわらず、補正された効果量は大きく負になっている。出力の2番目の部分を見ると、PEESE についても同じことが言えるが、その推定値はわずかに負であることがわかる ( <span class="math inline">\(g=\)</span> -0.44)。</p>
<p>このような場合、切片を真の効果量の点推定値として解釈しないことが最善である。PET-PEESE は、スモールサンプル効果を補正した場合、研究中の介入タイプは<strong>効果なし</strong>であることを示すと簡単に言うことが可能である。これは基本的に、実際に推定された負の効果量を解釈するのではなく、<span class="math inline">\(\hat\theta_{\mathrm{PET-PEESE}}\)</span> をゼロに設定することを意味する。</p>
<div class="boximportant">
<p>
<strong>PET-PEESE の限界</strong>
</p>
<p>
PET-PEESE
は、系統的にプール効果量を過剰に修正するだけでなく、出版バイアスが全くない場合でも、真の効果を<strong>過大評価</strong>することがある。全体的に、PET-PEESE
法は、含まれる研究の数が少ない場合 (<span class="math inline"><span class="math inline">\(K\)</span></span> &lt;
20)、あるいは研究間の異質性が非常に高い場合 (<span class="math inline"><span class="math inline">\(I^2\)</span></span> &gt;
80%)、悪いパフォーマンスを示すことが分かっている <span class="citation"><span class="citation">(<a href="references.html#ref-stanley2017limitations">T. D. Stanley 2017</a>)</span></span>。
</p>
<p>
研究間の異質性が非常に高い残念ながら、研究数が少なく異質性の高いメタアナリシスはよく見られる。このため、PET-PEESE
の適用範囲は限定されており、小規模研究の影響を調整する<strong>唯一の</strong>方法として使用することは勧められない。しかし、この方法が存在し、どのように適用できるかを知っておくことは、一部の研究分野でますます一般的になってきているため、良いことである。
</p>
</div>

<div class="boxinfo">
<p><strong>PET-PEESE で、<code>lm</code> の代わりに <code>rma.uni</code> を使う</strong></p>
<p>この実践例では、PET-PEESE を実装するために、<code>lm</code> 関数と研究の重みを使用した。この方法は、頻繁に使用されているが、全く問題がないわけではない。</p>
<p><code>lm</code> によって実装された重み付き回帰モデルと、例えば <code>rma.uni</code> によって採用されたメタ回帰モデルとの間には、わずかだが決定的な違いがある。<code>lm</code> が<strong>乗法誤差モデル</strong>を使用するのに対し、メタ分析の関数は通常<strong>加法誤差モデル</strong>を使用する。この違いについての技術的な詳細はここでは触れない。このトピックについては、Wolfgang Viechtbauer が書いた素晴らしい <a href="https://www.metafor-project.org/doku.php/tips:rma_vs_lm_lme_lmer">vignette</a> に詳しい情報が載っている。</p>
<p>主なポイントは、サンプリング誤差分散に比例定数を仮定した <code>lm</code> モデルは、メタ分析データには完全に適していないことである。これは、少なくとも感度分析として、<code>lm</code> の代わりに <code>rma.uni</code> を使って PET-PEESE を実装することが示唆されている。現実的には、以下のように <code>rma.uni</code> にモデレータ変数として <span class="math inline">\(SE_{\theta_k}^{(2)}\)</span> を追加して実行することになる。</p>
<p><code>rma.uni(TE, seTE^2, mods = ~seTE, data = dat, method = "FE")</code>.</p>
</div>
<p><br></p>
</div>
<div id="rucker-ma" class="section level4" number="9.2.1.6">
<h4>
<span class="header-section-number">9.2.1.6</span> Rücker の限界メタ分析法<a class="anchor" aria-label="anchor" href="#rucker-ma"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p></p>
<p>調整効果量の推定値を算出するもう一つの方法は、Rücker らが提案した<strong>限界メタ分析</strong> (limit meta-analysis) を行うことである <span class="citation">(<a href="references.html#ref-rucker2011treatment">2011</a>)</span> (訳注: limit meta-analysis は、日本語の訳語はないようである。)。この方法は、PET-PEESE よりも高度で、より複雑な計算を必要とする。そのため、ここではこの方法の背景にある一般的な考え方を理解することに重点を置き、その後の重い作業は <em>R</em> に任せることにする。</p>
<p>Rücker の方法の背後にある考え方は、小規模研究の効果によるバイアスを明示的に考慮したメタ分析モデルを構築することである。(ランダム効果) メタ分析の式は、次のように定義可能である。</p>
<p><span class="math display" id="eq:pub10">\[\begin{equation}
\hat\theta_k = \mu + \epsilon_k+\zeta_k
\tag{9.10}
\end{equation}\]</span></p>
<p>ここで、<span class="math inline">\(\hat\theta_k\)</span> は研究 <span class="math inline">\(k\)</span> の観察された効果量、<span class="math inline">\(\mu\)</span> は真の全体効果量、<span class="math inline">\(\epsilon_k\)</span> はサンプル誤差、<span class="math inline">\(\zeta_k\)</span> は研究間異質性による偏差を定量化したものである。</p>
<p>限界メタ分析では、このモデルを拡張し、小規模研究の効果がある場合、研究の効果量と標準誤差は独立していないという事実を考慮する。これは、出版バイアスが特に小規模な研究に影響すること、そして、小規模な研究は大規模な研究よりも大きな効果量を持つことを知っているために仮定されている。Rücker 法では、このバイアスは、新しい項 (<span class="math inline">\(\theta_{\text{Bias}}\)</span>) をモデルに導入することによって追加される。これは、<span class="math inline">\(\theta_{\text {Bias}}\)</span> が <span class="math inline">\(\epsilon_k\)</span> および <span class="math inline">\(\zeta_k\)</span> と相互作用すると仮定している。そして、<span class="math inline">\(\epsilon_k\)</span> が増加するにつれて、より大きくなる。適応された式は次のようになる。</p>
<p><span class="math display" id="eq:pub11">\[\begin{equation}
\hat\theta_k = \mu_* + \theta_{\text{Bias}}(\epsilon_k+\zeta_k)
\tag{9.11}
\end{equation}\]</span></p>
<p>この式では、<span class="math inline">\(\mu_*\)</span> はもはや全体的な真の効果量を表すのではなく、「標準的な」ランダム効果メタ分析では直接的に相当するものがないグローバル平均であることに注意することが重要である (<span class="math inline">\(\theta_{\text{Bias}} =\)</span> 0 以外の場合)。</p>
<p>次のステップは、PET-PEESE (前章参照) の背後にある考え方に似ている。上の式を使って、研究の効果量の推定がだんだん正確になり、個々のサンプル誤差 <span class="math inline">\(\epsilon_k\)</span> がゼロに近づくと仮定する。これによって、最終的に <span class="math inline">\(\epsilon_k\)</span> が方程式から脱落する。</p>
<p><span class="math display" id="eq:pub12">\[\begin{equation}
\mathrm{E}(\hat\theta_k) \rightarrow \mu_{*} + \theta_{\text{Bias}}\zeta_k ~ ~ ~ ~ \text{as} ~ ~ ~ ~ \epsilon_k \rightarrow 0.
\tag{9.12}
\end{equation}\]</span></p>
<p>この式では、 <span class="math inline">\(\epsilon_k\)</span> が 0 に近づくにつれて、<span class="math inline">\(\mathrm{E}(\hat\theta_k)\)</span> は <span class="math inline">\(\hat\theta_k\)</span> の<strong>期待値</strong>を示す。ここで作った式は、「限界メタ分析」の一つであり、 大きな標準誤差を持つ研究の歪んだ影響を取り除いた、調整された効果の推定値を提供するものである。<span class="math inline">\(\zeta_k\)</span> は、通常群間異質性分散 <span class="math inline">\(\tau^2\)</span> (あるいはその平方根である標準偏差 <span class="math inline">\(\tau\)</span>) によって表されるので、これを使って式中の <span class="math inline">\(\zeta_k\)</span> を置き換えれば、この式となる。</p>
<p><span class="math display" id="eq:pub13">\[\begin{equation}
\hat\theta_{*} = \mu_* + \theta_{\mathrm{Bias}}\tau
\tag{9.13}
\end{equation}\]</span></p>
<p>ここで、<span class="math inline">\(\hat\theta_*\)</span> は、小規模研究の影響を調整した後の<strong>プールされた</strong>効果量の推定値を表している。Rücker の方法は、最尤法を用い、真の効果量の「縮約」推定値 <span class="math inline">\(\hat\theta_*\)</span> などを使い、この式のパラメータを推定することが可能である。さらに、この式を用いて、個々の研究 <span class="math inline">\(k\)</span> ごとに縮約効果量推定値 <span class="math inline">\(\hat\theta_{{*}_k}\)</span> を得ることも可能である。</p>
<p><span class="math display">\[\begin{equation}
\hat\theta_{{*}_k} =  \mu_* + \sqrt{\dfrac{\tau^2}{SE^2_k + \tau^2}}(\hat\theta_k - \mu_*)
\end{equation}\]</span></p>
<p>ここで、<span class="math inline">\(SE^2_k\)</span> は、<span class="math inline">\(k\)</span> の二乗標準誤差 (すなわち、観察された分散) を表し、<span class="math inline">\(\hat\theta_k\)</span> は、もともと観察された効果量である<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;この式は、式 9.11 のより単純化したバージョンから導き出すことができる。この方法の技術的な説明は、Rücker ら &lt;span class="citation"&gt;(&lt;a href="references.html#ref-rucker2011treatment"&gt;2011&lt;/a&gt;)&lt;/span&gt; の式2.4から式2.6にある&lt;/p&gt;'><sup>37</sup></a>。</p>
<p></p>
<p>PET-PEESE と比較した Rücker の限界メタ分析法の利点は、異質性分散 <span class="math inline">\(\tau^2\)</span> が明示的にモデルに含まれていることである。もう一つのより実用的な利点は、 <em>R</em> で <code>limitmeta</code> 関数を使用して、この方法を直接適用できることである。この関数は <strong>{metasens}</strong> パッケージに含まれている <span class="citation">(<a href="references.html#ref-metasens">Schwarzer, Carpenter, and Rücker 2020</a>)</span>。</p>
<p><strong>{metasens}</strong> と <strong>{meta}</strong> は同じ研究者グループによって開発されたので、通常は非常にシームレスに連携して動作する。例えば、 <code>m.gen</code> メタ分析のリミットメタ分析を行うには、<code>limitmeta</code> の呼び出しの最初の引数としてそれを与えるだけでよいのである。</p>
<div class="sourceCode" id="cb270"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 'metasens' をライブラリからロード</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/guido-s/metasens">metasens</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 限界メタ分析を実行</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/metasens/man/limitmeta.html">limitmeta</a></span><span class="op">(</span><span class="va">m.gen</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Results for individual studies 
## (left: original data; right: shrunken estimates)
## 
##                           SMD        95%-CI      SMD        95%-CI
## Call et al.              0.70 [ 0.19; 1.22]    -0.05 [-0.56; 0.45]
## Cavanagh et al.          0.35 [-0.03; 0.73]    -0.09 [-0.48; 0.28]
## DanitzOrsillo            1.79 [ 1.11; 2.46]     0.34 [-0.33; 1.01]
## de Vibe et al.           0.18 [-0.04; 0.41]     0.00 [-0.22; 0.23]
## Frazier et al.           0.42 [ 0.13; 0.70]     0.13 [-0.14; 0.42]
## Frogeli et al.           0.63 [ 0.24; 1.01]     0.13 [-0.25; 0.51]
## Gallego et al.           0.72 [ 0.28; 1.16]     0.09 [-0.34; 0.53]
## Hazlett-Stevens &amp; Oren   0.52 [ 0.11; 0.94]    -0.00 [-0.41; 0.40]
## Hintz et al.             0.28 [-0.04; 0.61]    -0.05 [-0.38; 0.26]
## Kang et al.              1.27 [ 0.61; 1.93]     0.04 [-0.61; 0.70]
## Kuhlmann et al.          0.10 [-0.27; 0.48]    -0.29 [-0.67; 0.08]
## Lever Taylor et al.      0.38 [-0.06; 0.84]    -0.18 [-0.64; 0.26]
## Phang et al.             0.54 [ 0.06; 1.01]    -0.11 [-0.59; 0.36]
## Rasanen et al.           0.42 [-0.07; 0.93]    -0.25 [-0.75; 0.25]
## Ratanasiripong           0.51 [-0.17; 1.20]    -0.48 [-1.17; 0.19]
## Shapiro et al.           1.47 [ 0.86; 2.09]     0.26 [-0.34; 0.88]
## Song &amp; Lindquist         0.61 [ 0.16; 1.05]     0.00 [-0.44; 0.44]
## Warnecke et al.          0.60 [ 0.11; 1.08]    -0.09 [-0.57; 0.39]
## 
## Result of limit meta-analysis:
## 
##  Random effects model     SMD            95%-CI     z     pval
##     Adjusted estimate -0.0345 [-0.3630; 0.2940] -0.21   0.8367
##   Unadjusted estimate  0.5771 [ 0.3782; 0.7760] -0.21 &lt; 0.0001
## [...]</code></pre>
<p>出力は、まず、各研究の元の推定値 (左) と縮約された推定値 (右) を示している。調整済み効果量は、観察された効果量よりもかなり小さくなっていることがわかる。現在ではマイナスになっているものも複数ある。出力の第2部では、調整されたプール効果推定値が表示されている。これは、<span class="math inline">\(g=\)</span> -0.03、小規模研究の影響を補正した場合、全体的な効果がほぼゼロであることを示している。</p>
<p>もし、小規模研究の効果が本当に出版バイアスによるものであるなら、この結果は残念である。最初の発見は完全に偽りで、選択的な出版によって治療が実際には有効でないという事実が隠されていたことを意味するからである。しかし、繰り返しになるが、出版バイアスがこのデータにおける小規模研究の効果の唯一の原動力であったと証明することは難しい。</p>
<p></p>
<p>限界メタ分析のファネルプロットを作成することも可能である。 <code>limitmeta</code> の結果を <code>funnel.limitmeta</code> 関数に渡すだけで、<code>funnel.meta</code> によって生成されたものと全く同じように見える。唯一の違いは、プロットに<strong>灰色のカーブ</strong>が追加されることである。この曲線は、Y軸の標準誤差がゼロのときの調整済み平均効果量を示しているが、標準誤差が増加するにつれて、小規模研究の効果によるバイアスが増加することを表している。</p>
<p><code>limitmeta</code> オブジェクトのファンネルプロットを生成する際に、 <code>shrunken</code> 引数を <code>TRUE</code> に設定することで、縮約した研究レベルの効果量推定値を含めることも可能である。以下は、これらのプロットを生成するコードである。</p>
<div class="sourceCode" id="cb272"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># limitmeta オブジェクトを作成</span></span>
<span><span class="va">lmeta</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/metasens/man/limitmeta.html">limitmeta</a></span><span class="op">(</span><span class="va">m.gen</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># カーブ付きファンネル</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/metasens/man/funnel.limitmeta.html">funnel.limitmeta</a></span><span class="op">(</span><span class="va">lmeta</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.5</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># カーブと縮約研究推定値のファンネル</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/metasens/man/funnel.limitmeta.html">funnel.limitmeta</a></span><span class="op">(</span><span class="va">lmeta</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.5</span>, <span class="fl">2</span><span class="op">)</span>, shrunken <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-236-1.png" width="1248"></div>
<p><code>limitmeta</code> は標準化平均差を用いたメタ分析にのみ適用できるわけではなく、 <strong>{meta}</strong> メタ分析オブジェクトであればどのようなものでも使用できる。例として、リスク比を要約指標とする <code>m.bin</code> の調整済み効果量を確認してみよう。</p>
<div class="sourceCode" id="cb273"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/metasens/man/limitmeta.html">limitmeta</a></span><span class="op">(</span><span class="va">m.bin</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Result of limit meta-analysis:
## 
##  Random effects model     RR           95%-CI    z     pval
##     Adjusted estimate 2.2604 [1.8066; 2.8282] 7.13 &lt; 0.0001
##   Unadjusted estimate 2.0217 [1.5786; 2.5892] 7.13 &lt; 0.0001</code></pre>
<p>この分析では、元の推定値と修正後の推定値はほぼ同じであることがわかる。これは、Peters の検定 (Chapter <a href="pub-bias.html#peters-test">9.2.1.3</a>) で、このメタ分析では小規模研究の効果は小さいとされていることを考えると、あまり驚くことではない。</p>
<p><br></p>
</div>
</div>
<div id="p-curve" class="section level3" number="9.2.2">
<h3>
<span class="header-section-number">9.2.2</span> P 曲線<a class="anchor" aria-label="anchor" href="#p-curve"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p></p>
<p>これまで、小規模研究の効果を見ることで出版バイアスのリスクを評価する様々なアプローチについて説明してきた。実施方法は異なるが、これらの方法はすべて、選択的な報告によって研究の効果量がそのサンプルサイズに依存するという考えに基づいている。標準誤差が大きい (つまり精度が低い) 研究は、大規模な研究よりも平均効果量が大きいと仮定する。これは、非常に高い効果量を持つ小規模な研究だけが発表され、その他の研究はファイルの引き出しに入ったままになっていることがある。</p>
<p>この「理論」は確かに直感的だが、やや的外れであるという意見もある。小規模研究法は、出版バイアスが<strong>効果量</strong>によって引き起こされると仮定したが、より現実的なスタンスは、<span class="math inline">\(p\)</span> -<strong>値</strong>によって作動すると言えるだろう。実際、研究結果は、<span class="math inline">\(p&lt;\)</span> 0.05 である場合にのみ、出版する価値があるとみなされる。</p>
<p>先に述べたように、研究は<strong>人間</strong>によって行われるため、私たちの生活の他の多くの部分と同様に、金と名声に影響される。“significant <span class="math inline">\(p\)</span>, or no PhD” という悪名高いフレーズは、この問題を非常によく捉えている。研究者は、<span class="math inline">\(p\)</span> - 0.05より小さい値を「出す」ようにという大きな外圧にさらされている。研究者は、この有意水準が、自分の研究が出版されるかどうか、また、それが「成功」したとみなされるかどうかを決定することができることを知っているのである。このようなインセンティブは、ネガティブで有意でない知見が出版された文献からますます消えていく理由を説明するだろう <span class="citation">(<a href="references.html#ref-fanelli2012negative">Fanelli 2012</a>)</span>。</p>
<p>小規模研究法は、出版バイアスの背後にあるメカニズムを<strong>間接的に</strong>捉えていると言えるだろう。確かに、報告が選択されることによって、より小さな研究がより高い効果を持つようになることがある。しかし、これは、非常に高い効果によって、<span class="math inline">\(p&lt;\)</span> 0.05の検定統計量を得る機会が増えるから正しいだけである。小規模研究の効果測定法では、<span class="math inline">\(p=\)</span> 0.049 の研究と、<span class="math inline">\(p\)</span>-値が0.051 の研究の間にはほとんど差がない。しかし、実際には、この小さな違いが、研究者にとって大きな意味を持つ。</p>
<p>
</p>
<p>以下では、出版バイアスの主な要因として <span class="math inline">\(p\)</span>-値に着目した <strong>p-曲線</strong> (p-curve) という手法を紹介する <span class="citation">(<a href="references.html#ref-simonsohn2014p">Simonsohn, Nelson, and Simmons 2014b</a>, <a href="references.html#ref-simonsohn2014es">2014a</a>; <a href="references.html#ref-simonsohn2015better">Simonsohn, Simmons, and Nelson 2015</a>)</span>。この方法の特徴は、<strong>有意な</strong>効果量と、その <span class="math inline">\(p\)</span> -値がどのように分布しているかに限定されていることである。これにより、メタ分析データの背後に真の効果があるかどうかを評価することができ、それがどの程度大きいかを推定することが可能である。重要なのは、小規模研究効果法ではできない、<span class="math inline">\(p\)</span> -hacking のような疑わしい研究手法も明示的にコントロールできることである。</p>
<p></p>
<p>P 曲線は比較的新しい手法である。これは、近年社会科学に影響を与えた「複製の危機」に対応して開発された <span class="citation">(<a href="references.html#ref-ioannidis2005most">Ioannidis 2005</a>; <a href="references.html#ref-open2015estimating">Open Science Collaboration et al. 2015</a>; <a href="references.html#ref-mcnutt2014reproducibility">McNutt 2014</a>)</span>。この危機は、一見確立されたように見える研究結果の多くが、実は系統的に再現できないという不都合なものであるという観察に端を発している。このため、出版バイアスを検出する方法に新たな関心が寄せられるようになった。メタ分析では、選択的な報告を適切にコントロールできないため、すでに出版された文献に存在するバイアスを単純に再現している可能性がある。</p>
<p>P 曲線は、標準的な出版バイアス法、特に Duval &amp; Tweedie trim-fill 法の欠点に対応して開発されたものでもある。Simonsohnら <span class="citation">(<a href="references.html#ref-simonsohn2014es">2014a</a>)</span> は、trim-and-fill 法は通常<strong>小さな</strong>下方修正をもたらすだけで、分析データの背後に真の効果が全くないという事実を見過ごすことが多いことを発見してきた。</p>
<p>P 曲線はその名の通り、<span class="math inline">\(p\)</span> -値の曲線に基づくものである。 <span class="math inline">\(p\)</span>-曲線はヒストグラムのようなもので、メタ分析において、<span class="math inline">\(p&lt;\)</span> 0.05、<span class="math inline">\(p&lt;\)</span> 0.04、<span class="math inline">\(p&lt;\)</span> 0.03 に該当する研究数を示している。p-曲線法は、この <span class="math inline">\(p\)</span> -値のヒストグラムの形状は、研究のサンプルサイズに依存するという考えに基づいており、さらに重要なことは、このデータの背後にある<strong>真の</strong>効果量に依存していることである。</p>
<p>これを説明するために、9 つのメタ分析の結果をシミュレートしてみる。パターンを明確にするために、これらの架空のメタ分析には、それぞれ膨大な数の <span class="math inline">\(K=\)</span> 10<span class="math inline">\(^{\text{5}}\)</span> 件の研究が含まれている。9 つのシミュレーションのそれぞれで、個々の研究に対して異なるサンプルサイズ (<span class="math inline">\(n =\)</span> 20から <span class="math inline">\(n =\)</span> 100 の範囲) と、異なる真の効果量 ( <span class="math inline">\(\theta=\)</span> 0から0.5の範囲) を仮定しよう。メタ分析では、すべての研究が1つの真の効果量を共有し、効果が固定効果モデルに従うと仮定する。そして、シミュレーションで有意なすべての効果量の <span class="math inline">\(p\)</span> -値を取り、ヒストグラムを作成する。その結果は、以下のプロットで見ることが可能である。</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:pcurve"></span>
<img src="Doing_Meta_Analysis_in_R_files/figure-html/pcurve-1.png" alt="異なるサンプルサイズと効果量の P-曲線。" width="80%"><p class="caption">
Figure 9.1: 異なるサンプルサイズと効果量の P-曲線。
</p>
</div>
<p>一番上の段は、真の効果がない場合の有意な <span class="math inline">\(p\)</span> -値の分布を示している。このパターンは、個々の研究のサンプルサイズがどんなに大きくても、すべてのシミュレーションで同じであることがわかる。3 つの研究の <span class="math inline">\(p\)</span> 値は、等しく分布しているように見える。<span class="math inline">\(p=\)</span> 0.04 というかろうじて有意な値は、<span class="math inline">\(p=\)</span> 0.01 と同じぐらいありそうである。このような平坦な <span class="math inline">\(p\)</span>-曲線は、このデータに基礎的な効果がないとき、すなわち、<span class="math inline">\(\theta = 0\)</span> の<strong>帰無仮説</strong>が真であるときに出現する。</p>
<p>この場合、<span class="math inline">\(p\)</span>-値は<strong>一様</strong>分布に従うと仮定される。すべての <span class="math inline">\(p\)</span>-値は他のものと同じように可能性がある。帰無仮説 (<span class="math inline">\(\theta = 0\)</span>) が真であるとき、偶然に有意な効果量を見つけることは可能である。これは、<strong>偽陽性</strong>、つまり、<span class="math inline">\(\alpha\)</span> エラーになる。しかし、これはありえないことで、私たちは<strong>どのようにありえないか</strong>を正確に知っている。効果量がゼロの時は一様に分布しているので、<span class="math inline">\(p\)</span>-値の 5% は 0.05 より小さいと予想される。これはまさに、帰無仮説を棄却するための仮説検定でよく使われる <span class="math inline">\(\alpha=\)</span> 0.05 の有意性閾値なのである。</p>
<p><span class="math inline">\(p\)</span>-曲線は、2 段目と 3 段目で全く違って見える。これらの例では、帰無仮説は否定され、データには真の効果が存在する。このため、<span class="math inline">\(p\)</span> -値の分布は<strong>右に歪んでいる</strong>状態になる。このデータが真の効果を捉えている場合、非常に有意な (例えば、<span class="math inline">\(p=\)</span> 0.01) 効果量は、ほとんど有意でない効果 (例えば、<span class="math inline">\(p=\)</span> 0.049) よりも可能性が高くなる。この右に長い状態は、真の効果量と研究サンプルサイズが大きくなるにつれて、ますます顕著になる。</p>
<p>しかし、メタ分析では、検出力が極端に低い研究 (すなわち、<span class="math inline">\(\theta=\)</span> 0.2 の小さな効果を検出することを目的としながら、<span class="math inline">\(n=\)</span> 20 人の参加者しか含まない) でも、右に歪んでいる <span class="math inline">\(p\)</span>-曲線が出現することがわかる。このことから、<span class="math inline">\(p\)</span> -曲線は、真の効果量の変化に対して非常に敏感であることが明らかになった。真の効果量が存在する場合、<span class="math inline">\(p\)</span>-値が有意である分布を見るだけで、それを検出できることがよくある。</p>
<p>さて、研究者が <span class="math inline">\(p\)</span>-ハッキングしたとき、<span class="math inline">\(p\)</span>-曲線がどのように見えるか想像してみてみよう。通常、アナリストが <span class="math inline">\(p\)</span>-ハッキング を使い始めるのは、結果が有意ではないが、それに<strong>近い</strong>と判断されたときである。そして、<span class="math inline">\(p\)</span>-値が 0.05 より小さくなるまで分析の詳細が調整される。それはすでに結果を公表するのに十分な値なので、それ以降、<span class="math inline">\(p\)</span>-ハッキングは行われない。 <span class="math inline">\(p\)</span>-ハッキングが広く行われると、<span class="math inline">\(p\)</span>-曲線が<strong>左に歪む</strong>のは想像に難くない。<span class="math inline">\(p\)</span>-値が 0.05 をわずかに下回る値が過剰に表現され、非常に有意な結果が過小に表現される。</p>
<p>まとめると、<span class="math inline">\(p\)</span>-曲線は、出版バイアスと <span class="math inline">\(p\)</span>-ハッキングの存在を評価するための診断ツールとして使用できることがわかる。次に、経験的な <span class="math inline">\(p\)</span>-曲線に基づく統計検定のコレクションである p-曲線<strong>曲線</strong>について説明する。重要なのは、これらのテストはどれも出版バイアスそのものに焦点を当てていないことである。その代わりに、この方法は、このデータに<strong>明らかな価値</strong>があるかどうかを見つけ出そうとするものである。これは間違いなく、メタ分析で最も関心のあることである。推定した効果が偽りのものでなく、選択的な報告によって引き起こされた人工物であることを確認したいのである。P-曲線は、まさにこの懸念に対応するものである。P-曲線は、発見が現実に存在する効果によってもたらされているのか、あるいは、大げさに言えば、「音と怒りの物語、何の意味もない」のかをチェックすることを可能にした。</p>
<p><br></p>
<div id="証拠能力の検定" class="section level4" number="9.2.2.1">
<h4>
<span class="header-section-number">9.2.2.1</span> 証拠能力の検定<a class="anchor" aria-label="anchor" href="#%E8%A8%BC%E6%8B%A0%E8%83%BD%E5%8A%9B%E3%81%AE%E6%A4%9C%E5%AE%9A"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p></p>
<p>証拠能力の有無を評価するために、p-曲線は 2 種類の検定を用いる: <strong>右歪度の検定</strong>と <strong>33% 検出力の検定</strong>である (後者は <span class="math inline">\(p\)</span> -曲線の平坦性の検定と見なすことができる)。まず、右歪度の検定から始める。すでに学んだように、<span class="math inline">\(p\)</span>-曲線の右歪度は、研究のサンプルサイズとその真の根本的な効果の関数である。したがって、メタ分析の <span class="math inline">\(p\)</span> -曲線が有意に右に長いことを確認できるテストは非常に有用である。有意な <span class="math inline">\(p\)</span> -値の分布に有意な右に歪んでいる場合、これは結果が本当に真の効果によって引き起こされていることを示すだろう。</p>
<p><br></p>
<div id="右歪度の検定" class="section level5" number="9.2.2.1.1">
<h5>
<span class="header-section-number">9.2.2.1.1</span> 右歪度の検定<a class="anchor" aria-label="anchor" href="#%E5%8F%B3%E6%AD%AA%E5%BA%A6%E3%81%AE%E6%A4%9C%E5%AE%9A"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p></p>
<p>右歪度を検定するために、p-曲線法ではまず<strong>二項検定</strong>を用いる。この検定は、二項分布に従うデータに対して使用することが可能である。二項分布は、2 つのカテゴリに分けられるデータ (例: 成功/失敗、表/裏、イエス/ノー) に対して仮定することができ、<span class="math inline">\(p\)</span> は結果の 1 つの確率を示し、<span class="math inline">\(q = 1-p\)</span> は他の結果の確率を示す。</p>
<p>二項検定を使用するために、<span class="math inline">\(p\)</span> -曲線を 2 つのセクションに分割しなければならない。これは、&lt;0.025 である <span class="math inline">\(p\)</span> -値の数と、次に &gt;0.025 である有意な <span class="math inline">\(p\)</span> -値の数をカウントすることによって行う。 <span class="math inline">\(p\)</span> -曲線の値は 0 から 0.05 の範囲にあるので、基本的には<strong>x</strong>-軸の中央をカットオフとして使用する。 <span class="math inline">\(p\)</span> -曲線が確かに右に歪んでいる場合、2 つのグループの <span class="math inline">\(p\)</span> -値の数が異なることが予想される。これは、0.025 より小さい結果を得る確率 <span class="math inline">\(p\)</span> は、0.025 より大きい値を得る確率 <span class="math inline">\(q\)</span> よりもかなり高いからである。</p>
<p><span class="math inline">\(p\)</span> -曲線に8つの値があり、そのうちの7つが0.025以下であると想像してみよう。 <em>R</em> の <code>binom.test</code> 関数を使って、<span class="math inline">\(p\)</span> -値の小ささと高さが等しく起こりうるという帰無仮説のもとで、そのようなデータを見つけることがどの程度可能かをテストすることが可能である<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;帰無仮説のもとでは、&amp;lt; 0.025 という結果を得る真の確率 &lt;span class="math inline"&gt;\(p\)&lt;/span&gt; は &lt;span class="math inline"&gt;\(\pi=\)&lt;/span&gt; 0.5 だと仮定している。私たちの目標は、&lt;span class="math inline"&gt;\(k=\)&lt;/span&gt; 8 件の有意な研究があるときに、&lt;span class="math inline"&gt;\(n=\)&lt;/span&gt; 7 件以上の高い有意な研究が得られる確率を計算することである。この確率、片側二項検定の &lt;span class="math inline"&gt;\(p\)&lt;/span&gt; -値は、この公式を使って求めることが可能である。&lt;span class="math display"&gt;\[\text{P}(X\geq k) = \sum_{k=7}^{8}\frac{n!}{k!(n-k)!}p^k(1-p)^{n-k}\]&lt;/span&gt; ここで &lt;span class="math inline"&gt;\(p=\)&lt;/span&gt; 0.5、エクスクラメーション記号 (!) は階乗であることを示す。 シグマ記号 (Σ) は全て足すことを表す。つまり &lt;span class="math inline"&gt;\(k=\)&lt;/span&gt; 7 から順に &lt;span class="math inline"&gt;\(k=n\)&lt;/span&gt; まで足す。&lt;/p&gt;'><sup>38</sup></a>。</p>
<p>小さい <span class="math inline">\(p\)</span> -値は大きい <span class="math inline">\(p\)</span> -値よりも頻度が高いと仮定しているので、 <code>alternative</code> 引数を <code>"greater"</code> に設定することで、片側検定を使用することが可能である。</p>
<div class="sourceCode" id="cb275"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">k</span> <span class="op">&lt;-</span> <span class="fl">7</span>   <span class="co"># p&lt;0.025 である研究数</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">8</span>   <span class="co"># 有意な研究数</span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fl">0.5</span> <span class="co"># k (ヌル仮説) の推定確率</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/binom.test.html">binom.test</a></span><span class="op">(</span><span class="va">k</span>, <span class="va">n</span>, <span class="va">p</span>, alternative <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span><span class="op">$</span><span class="va">p.value</span></span></code></pre></div>
<pre><code>## [1] 0.03515625</code></pre>
<p>二項検定が有意であることがわかる (<span class="math inline">\(p&lt;\)</span> 0.05)。この例では、<span class="math inline">\(p\)</span>-値 が、低い値より高い値の方が有意に多いことを意味する。全体として、これは <span class="math inline">\(p\)</span> -曲線が右に歪んでおり、真の効果があることを示している。</p>
<p>二項検定の欠点は、<span class="math inline">\(p\)</span> -値が実際には連続的であるにもかかわらず、二項化することを要求することである。情報の損失を避けるために、データを二項に変換することを必要としない検定が必要である。</p>
<p>P-曲線は、各 <span class="math inline">\(p\)</span> -値に対して <span class="math inline">\(p\)</span> -値を計算することによってこれを実現し、各研究のいわゆる <span class="math inline">\(pp\)</span>-値が得られる。<span class="math inline">\(pp\)</span> -値は、<span class="math inline">\(p\)</span> -曲線が平坦なとき (すなわち、真の効果がないとき)、<span class="math inline">\(p\)</span> と少なくとも同じ高さの値を得る可能性を示している。これは、有意な値のみを考慮した場合の <span class="math inline">\(p\)</span> の値の確率を示す。<span class="math inline">\(p\)</span> -値は一様分布に従うので、<span class="math inline">\(\theta = 0\)</span>、<span class="math inline">\(pp\)</span>-値は、<span class="math inline">\([0,1]\)</span> の範囲に投影する有意な <span class="math inline">\(p\)</span> -値にほかならない。連続アウトカム尺度の場合、これは <span class="math inline">\(p\)</span>-値に 20 を乗じることで達成される。例えば、<span class="math inline">\(p = 0.023\times20 = 0.46 \rightarrow pp\)</span> 。</p>
<p>
</p>
<p>メタ分析で有意な各研究の <span class="math inline">\(pp_k\)</span>-値を用いて、<strong>Fisher の方法</strong>で右歪度を検定することが可能である。この方法は、20 世紀初頭に R. A. Fisher によって開発されたメタ分析の「古風な」タイプである (Chapter <a href="intro.html#history">1.2</a> を参照)。Fisherの方法は、いくつかの研究からの <span class="math inline">\(p\)</span> -値を集約し、少なくとも 1 つが真の効果を測定しているかどうかを検定することが可能である (すなわち、提出された <span class="math inline">\(p\)</span> -値の分布が右に歪んでいるかどうかを検定する)。これは、<span class="math inline">\(pp\)</span>-値を対数変換し、すべての研究 <span class="math inline">\(k\)</span> の結果を合計し、-2 を掛ける。</p>
<p>結果として得られる値は、<span class="math inline">\(2 \times K\)</span> の自由度を持つ <span class="math inline">\(\chi^2\)</span> 分布 (Chapter <a href="heterogeneity.html#cochran-q">5.1.1</a> 参照) に従う検定統計量となる ( <span class="math inline">\(K\)</span> は <span class="math inline">\(pp\)</span>-値の総数)<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;新しいバージョンの p-曲線では、右歪度の検定に Fisher 法 &lt;span class="citation"&gt;(&lt;a href="references.html#ref-simonsohn2015better"&gt;Simonsohn, Simmons, and Nelson 2015&lt;/a&gt;)&lt;/span&gt; の代わりに &lt;strong&gt;Stouffer’ 法&lt;/strong&gt; が使われている。両方の方法は密接に関連しているが、Stouffer 法は &lt;span class="math inline"&gt;\(p\)&lt;/span&gt;-値の代わりに &lt;span class="math inline"&gt;\(z\)&lt;/span&gt;-score に基づいている。&lt;/p&gt;'><sup>39</sup></a>。</p>
<p><span class="math display" id="eq:pub14">\[\begin{equation}
\chi^2_{2K} = -2 \sum^K_{k=1} \log(pp_k)
\tag{9.14}
\end{equation}\]</span></p>
<p>Fisher の方法を簡単な例で試してみよう。<span class="math inline">\(p\)</span>-曲線が 5 つの <span class="math inline">\(p\)</span>-値を含んでいると想像してみよう。<span class="math inline">\(p=\)</span> 0.001, 0.002, 0.003, 0.004 および 0.03 とする。右歪度を検定するために、まず、これらの <span class="math inline">\(p\)</span>-値を <span class="math inline">\(pp\)</span>-値に変換しなければならない。</p>
<div class="sourceCode" id="cb277"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.001</span>, <span class="fl">0.002</span>, <span class="fl">0.003</span>, <span class="fl">0.004</span>, <span class="fl">0.03</span><span class="op">)</span></span>
<span><span class="va">pp</span> <span class="op">&lt;-</span> <span class="va">p</span><span class="op">*</span><span class="fl">20</span></span>
<span></span>
<span><span class="co"># pp 値を表示</span></span>
<span><span class="va">pp</span></span></code></pre></div>
<pre><code>## [1] 0.02 0.04 0.06 0.08 0.60</code></pre>
<p>式9.15を用いると、このコードで <span class="math inline">\(\chi^2\)</span> の値を算出することができる。</p>
<div class="sourceCode" id="cb279"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">chi2</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">2</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">pp</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">chi2</span></span></code></pre></div>
<pre><code>## [1] 25.96173</code></pre>
<p>この結果、<span class="math inline">\(\chi^2=\)</span> 25.96 となる。5 件の研究が含まれているので、自由度は <span class="math inline">\(\text{d.f.} =2\times5=10\)</span> となる。この情報を使って、効果がない/右に歪んでいないという帰無仮説のもとで、このデータがどれだけの確率で成り立っているかをチェックすることが可能である。これは <em>R</em> で <code>pchisq</code> 関数を用いて行うことが可能である。<span class="math inline">\(\chi^2\)</span> の値と d.f. の数を指定する必要がある。</p>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="fl">26.96</span>, df <span class="op">=</span> <span class="fl">10</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.002642556</code></pre>
<p>これは、<span class="math inline">\(p\)</span>-値が 0.0026 であることを意味する。これは、帰無仮説が非常にありそうにないことを意味し、したがって棄却される。 <span class="math inline">\(\chi^2\)</span> 検定の有意な値は、この例では、<span class="math inline">\(p\)</span> -値が実際に右に歪んでいることを教えてくれる。これは、このデータの背後に証拠能力があるという仮定の証拠と見ることが可能である。</p>
<p><br></p>
</div>
<div id="平坦度テスト" class="section level5" number="9.2.2.1.2">
<h5>
<span class="header-section-number">9.2.2.1.2</span> 平坦度テスト<a class="anchor" aria-label="anchor" href="#%E5%B9%B3%E5%9D%A6%E5%BA%A6%E3%83%86%E3%82%B9%E3%83%88"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p></p>
<p>右歪度の検定が、有意な <span class="math inline">\(p\)</span> -値の分布が真の全体効果を表しているかどうかを決定するために使用できることを確認する。問題は、この検定がデータの<strong>統計的検出力</strong>に依存することである。したがって、右歪度検定が<strong>有意でない</strong>とき、これは自動的に証拠能力がないことを意味するわけではない。本当に効果がないのか、あるいは、たとえデータが実際に右に歪んでいても <span class="math inline">\(p\)</span>-曲線における値の数が <span class="math inline">\(\chi^2\)</span> 検定を有意にするには少なすぎるのか、という2つのことが考えられる。</p>
<p>したがって、右歪度の検定が有意でないことの説明として、検出力の欠如を除外しなければならない。右歪度の検定の帰無仮説は、「証拠能力がない」というものである。検定では、基本的に、経験的な <span class="math inline">\(p\)</span>-曲線が平坦で<strong>ない</strong>ことを示すことによって、この帰無仮説を棄却しよう。</p>
<p>ここで、この論理を逆転させて、<span class="math inline">\(p\)</span>-曲線が平坦で<strong>ある</strong> ことを示さなければならない。これは帰無仮説を変更することで可能である。効果がないのではなく、新しい帰無仮説は、<span class="math inline">\(p\)</span>-曲線は<strong>小さい</strong>効果を含み、結果として<strong>わずかに</strong>右に歪んでいると仮定する。平坦性の検定では、<span class="math inline">\(p\)</span>-曲線が<strong>わずかに</strong>右に歪んでいないことを示すことが目標になる。あるいは、別の言い方をすれば、<span class="math inline">\(p\)</span>-曲線が、非常に、非常に小さな効果に対して私たちが期待するものよりも、著しく平坦であることを確認したい。このような場合、手元のデータでは非常に小さな効果さえも否定され、証拠能力が全くない可能性が高いと言える。</p>
<p></p>
<p>P曲線解析は、33%の検出力の検定を通してこれを達成する。このアイデアは、真の効果が非常に小さい場合の各有意な研究 <span class="math inline">\(k\)</span> の<strong>期待</strong> <span class="math inline">\(pp\)</span> -値 (すなわち、<span class="math inline">\(p\)</span> の確率) を構築することである。非常に小さいというのは、研究のサンプルサイズを用いて、33%の検出力で検出できる効果量という意味である。</p>
<p>この 33％という閾値はある程度恣意的なもので、p-曲線の発明者が実質的に無視できる程度の効果を示す大まかな指標として選んだものである。33% 検出力 <span class="math inline">\(pp\)</span> -値がどのように決定されるかの統計的な詳細は割愛するが、アウトカム尺度によって非中心分布 <span class="math inline">\(F\)</span> , <span class="math inline">\(t\)</span> , <span class="math inline">\(\chi^2\)</span> などの<strong>非中心</strong>分布の使用を伴うことは知っておく必要がある<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;本書で使用する &lt;em&gt;R&lt;/em&gt; のp-曲線関数では、効果量はまず &lt;span class="math inline"&gt;\(z\)&lt;/span&gt; スコアに変換される (式 &lt;span class="math inline"&gt;\(z = \frac{\hat\theta}{SE_{\hat\theta}}\)&lt;/span&gt; を使用する)。33% の検出力検定の期待値 &lt;span class="math inline"&gt;\(pp\)&lt;/span&gt; -値を計算するために、 d.f. = 1 の非心分布 &lt;span class="math inline"&gt;\(\chi^2\)&lt;/span&gt; が使用される。これは、&lt;span class="math inline"&gt;\(\chi^2_1\)&lt;/span&gt; と &lt;span class="math inline"&gt;\(z\)&lt;/span&gt; (より正確には: &lt;span class="math inline"&gt;\(z^2\)&lt;/span&gt; ) の分布が等しいので可能である。&lt;/p&gt;'><sup>40</sup></a>。</p>
<p>以下、p曲線 (Chapter <a href="pub-bias.html#p-curve-es">9.2.2.2</a>) を用いた効果量推定について、非心分布の概念をより詳細に説明する。</p>
<p>要約すると、平坦性検定では、まず、有意な <span class="math inline">\(p\)</span> -値ごとに、33% の検出力で検出できる効果に基づく <span class="math inline">\(pp\)</span> -値を計算する。もし、33% 検出力の推定値が私たちの <span class="math inline">\(p\)</span> -値の分布によく合うなら、33%検出力の <span class="math inline">\(pp\)</span>-値は一様分布になる。ちょうど、<span class="math inline">\(p\)</span>-値が、データが帰無仮説 <span class="math inline">\(\theta = 0\)</span> によく合うとき、一様分布に従うのと同じである。したがって、右歪度検定で使ったのと同じ方法を適用できるが、今回は、計算に 33% の検出力 <span class="math inline">\(pp\)</span>-値を使用する。</p>
<p>唯一の違いは、帰無仮説を棄却することに特に注目しないことである。これは、少なくとも小さな効果がデータに存在するという概念を否定している。無視できるほど小さな効果があるか、あるいは全く効果がないかのいずれかである。</p>
<p><br></p>
</div>
<div id="interpretation-p-curve-results" class="section level5" number="9.2.2.1.3">
<h5>
<span class="header-section-number">9.2.2.1.3</span> P-曲線の結果の解釈<a class="anchor" aria-label="anchor" href="#interpretation-p-curve-results"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p>ここまで、経験的に <span class="math inline">\(p\)</span> -曲線を分析することができるいくつかの検定を取り上げた。統計的な概念のいくつかが理解しにくいと感じても、あまり心配しないでみよう。p-曲線の背後にある方法論を把握するのに時間がかかるが、次の実践的な例はこの点で必ず役に立つ。最も重要なのは、p-曲線検定の背後にある<strong>アイデア</strong>と、その結果がどのように解釈されるかを理解することである。このセクションでは、後者に焦点を当てる。</p>
<p>p-曲線を解釈するとき、私たちは 4 つの検定結果を意味づけしなければならない。二項右歪度検定と平坦度検定、および <span class="math inline">\(pp\)</span> -値に基づく右歪度検定と平坦度検定のものである。さらに悪いことに、p-曲線解析は、まだカバーしていない 2 つの追加検定を含んでいる。 <strong>half</strong> <span class="math inline">\(p\)</span> <em>curve</em> に基づく右歪度検定と平坦度検定である。これらの検定は、前にカバーした <span class="math inline">\(pp\)</span> -値に基づく検定と同じであるが、高い <span class="math inline">\(p\)</span>-値 (すなわち、<span class="math inline">\(p&lt;\)</span> 0.025) にのみ適用されている。</p>
<p></p>
<p>half <span class="math inline">\(p\)</span>-curve 検定は、<strong>ambitious</strong> <span class="math inline">\(p\)</span> <strong>-hacking</strong> <span class="citation">(<a href="references.html#ref-simonsohn2015better">Simonsohn, Simmons, and Nelson 2015</a>)</span> に対するセーフガードとして導入されたものである。可能性は低いが、研究者が <span class="math inline">\(p\)</span> -有意性が高くなるまで結果をハッキングしている可能性がある。しかし、この場合、<span class="math inline">\(p\)</span> -曲線の形状が歪む可能性がある。つまり、真の効果がない場合でも、左ではなく、わずかに右に歪んで見えるだろう。half <span class="math inline">\(p\)</span> -curve に基づく検定は、これを制御することが可能である。かなり大胆に <span class="math inline">\(p\)</span>-ハッキングを行う場合でも、真の効果がない限り、<strong>非常に</strong>高い <span class="math inline">\(p\)</span>-値 (たとえば <span class="math inline">\(p&lt;\)</span> 0.01) を得ることはますます困難になることがある。定義上、半分の <span class="math inline">\(p\)</span> -曲線は 0.025 より小さい値しか含まないので、二項検定は実行されない。</p>
<p>p-曲線の結果を解釈するとき、私たちは本質的に 2 つの質問に答えようとする。1つ目は、<span class="math inline">\(p\)</span> -曲線は、証拠能力の存在を示しているか？これは、右歪度の検定を使用して評価することが可能である。証拠能力の存在を確認できない場合、2 番目の質問に移る。これは、平坦度検定で評価することができる。具体的には、以下のガイドラインを用いることができる <span class="citation">(<a href="references.html#ref-simonsohn2015better">Simonsohn, Simmons, and Nelson 2015</a>)</span>。</p>
<ul>
<li><p><strong>固有値の存在</strong>: 右歪度検定が半分の <span class="math inline">\(p\)</span>-曲線で有意である (<span class="math inline">\(p&lt;\)</span> 0.05) <strong>または</strong>右歪度検定の <span class="math inline">\(p\)</span> -値が半分と完全な曲線の<strong>両方</strong>で &lt;0.1&gt; である。</p></li>
<li><p><strong>証拠となる値がない、または不十分である</strong>: 完全曲線に対する平坦度検定は <span class="math inline">\(p&lt;\)</span> 0.05 で有意である <strong>または</strong> 半曲線に対する平坦度検定 <strong>および</strong> 二項検定は <span class="math inline">\(p&lt;\)</span> 0.1 で有意である。</p></li>
</ul>
<div class="boxinfo">
<p>
<strong>「ノーノー」ケースの解釈</strong>
</p>
<p>
どの P
曲線分析も、最終的には3つの結果のいずれかに帰結する。右歪度検定が有意であるとき、我々は証拠能力があると結論づける。右歪度検定が有意でなく、平坦度検定が有意なとき、これは証拠能力がない
(または効果がとてもとても小さい) ことを示す。
</p>
<p>
最後の3つ目の結果は、最も厄介である。適切な表現がないので、「ノーノー」ケースと呼んでいる。これは、証拠能力があることも、ないことも確認できない場合である
(つまり、右歪度の検定も、平坦度の検定も有意ではない)。
</p>
<p>
解釈としては、「ノーノー」の場合、真の効果があることを確認できないが、比較的小さな効果も否定できないことを意味している。
</p>
<p>
この3つ目の結果は、<span class="math inline"><span class="math inline">\(p\)</span></span>
曲線に含まれる研究数が少ない場合によく起こり、確かにやや期待はずれである。この結果は、<span class="math inline"><span class="math inline">\(p\)</span></span>-曲線を見ただけでは真の効果が存在するかどうかわからない、物事を明確にするためにもっと証拠が必要であることを伝えることが多い。
</p>
</div>
<p><br></p>
</div>
<div id="r-のp曲線解析" class="section level5" number="9.2.2.1.4">
<h5>
<span class="header-section-number">9.2.2.1.4</span> <em>R</em> のP曲線解析<a class="anchor" aria-label="anchor" href="#r-%E3%81%AEp%E6%9B%B2%E7%B7%9A%E8%A7%A3%E6%9E%90"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p>ここまでで、p-曲線分析の背後にある理論について多くを学んだので、そろそろ実世界の例でこの技術を適用し始める時期が来ている。幸運なことに、p-曲線の発明者である Simonsohn、Simmons、Nelson は、以前に説明したすべてのテストを自動的に行い、関連する結果を返すアプリケーションを開発してきた。この <strong>p-曲線アプリ</strong>は、<a href="http://p-curve.com/">オンライン</a> でも見ることが可能である。
<em>R</em> で p-曲線を使用するには、<code>pcurve</code> 関数に頼ることが可能である。この関数はアプリの動作をエミュレートするもので、特に <strong>{meta}</strong> パッケージで作成されたメタ分析オブジェクトのために設計されている。</p>
<div class="boxdmetar">
<p>
<strong>“pcurve” 関数</strong>
</p>
<p>
</p>
<p>
<code>pcurve</code> 関数は、<strong>{dmetar}</strong>
パッケージに含まれている。<strong>{dmetar}</strong>
がインストールされ、コンピュータに読み込まれると、この関数を使用できるようになる。もし、<strong>{dmetar}</strong>
をインストールして<strong>いない</strong>場合は、以下の手順でインストールできる。
</p>
<ol style="list-style-type: decimal">
<li>
関数のソースコードに <a href="https://raw.githubusercontent.com/MathiasHarrer/dmetar/master/R/power.analysis.subgroup.R">オンライン</a>
でアクセスする。
</li>
<li>
ソースコード全体をコンソール (R Studio の左下ペイン)
にコピー＆ペーストし、Enterキーを押して、 <em>R</em>
に関数を「学習」させる。
</li>
<li>
<strong>{stringr}</strong> と <strong>{poibin}</strong>
パッケージがインストールされ、ロードされていることを確認する。
</li>
</ol>
</div>
<p></p>
<p>関数 <code>pcurve</code> の使い方は簡単である。この関数に、以前に作成した <strong>{meta}</strong> メタ分析オブジェクトを渡すだけでよい。この例では、 <code>metagen</code> 関数 (Chapter <a href="pooling-es.html#pre-calculated-es">4.2.1</a>) で作成した <code>m.gen</code> メタ分析オブジェクトを再び使用する。</p>
<p>しかし、分析を実行する前に、以前に特定した2つの外れ研究 (研究3と研究16、Chapter <a href="heterogeneity.html#outliers">5.4</a> 参照) を削除している。これがなぜ良いアイデアなのかは後で説明する。</p>
<div class="sourceCode" id="cb283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dmetar.protectlab.org">dmetar</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/guido-s/meta/">meta</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># m.gen から外れ値を外して update</span></span>
<span><span class="va">m.gen_update</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/meta/man/update.meta.html">update.meta</a></span><span class="op">(</span><span class="va">m.gen</span>, subset <span class="op">=</span> <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">16</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># p-曲線解析を実行</span></span>
<span><span class="fu"><a href="http://dmetar.protectlab.org/reference/pcurve.html">pcurve</a></span><span class="op">(</span><span class="va">m.gen_update</span><span class="op">)</span></span></code></pre></div>
<pre><code>## P-curve analysis 
##  ----------------------- 
## - Total number of provided studies: k = 16 
## - Total number of p&lt;0.05 studies included into the 
##   analysis: k = 9 (56.25%) 
## - Total number of studies with p&lt;0.025: k = 8 (50%) 
##    
## Results 
##  ----------------------- 
##                     pBinomial  zFull pFull  zHalf pHalf
## Right-skewness test     0.020 -3.797 0.000 -2.743 0.003
## Flatness test           0.952  1.540 0.938  3.422 1.000
## Note: p-values of 0 or 1 correspond to p&lt;0.001 and p&gt;0.999, 
## respectively.   
##
## Power Estimate: 66% (31.1%-87.8%)
##    
## Evidential value 
##  ----------------------- 
## - Evidential value present: yes 
## - Evidential value absent/inadequate: no</code></pre>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-245-1.png" width="68%" style="display: block; margin: auto;"></div>
<p>p曲線解析の結果と、観測された <span class="math inline">\(p\)</span>-曲線のプロットの 2 つが出力される。</p>
<p>出力は、メタ分析が <span class="math inline">\(k=\)</span> 9 件の有意な効果を含み、それが <span class="math inline">\(p\)</span> -曲線に含まれることを教えてくれる。研究 ( <span class="math inline">\(k=\)</span> 8) のほとんどは、非常に有意な結果 (すなわち、<span class="math inline">\(p&lt;\)</span> 0.025) であった。<code>Results</code> セクションには、分析の主なアウトカムが記載されている。3つの右歪度検定すべてが有意であることがわかる: 二項検定 ( <code>pBinom</code> ; <span class="math inline">\(p=\)</span> 0.02), 完全な <span class="math inline">\(p\)</span>-曲線 <span class="math inline">\(pp\)</span>-値の検定 ( <code>pFull</code> ; <span class="math inline">\(p&lt;\)</span> 0.001) と half <span class="math inline">\(p\)</span>-曲線に基づく検定 ( <code>pHalf</code> ; <span class="math inline">\(p=\)</span> 0.003)<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;出力から、完全および half &lt;span class="math inline"&gt;\(p\)&lt;/span&gt; の統計出力は、 &lt;span class="math inline"&gt;\(z\)&lt;/span&gt; スコアと関係があることがわかる。出力では、完全および半分の の曲線に基づく検定統計量も有意であることがわかる。これは、 &lt;code&gt;pcurve&lt;/code&gt; 関数が Fisher 法ではなく Stouffer 法を用いて結果を集計しているためである。この章の脚注6で述べたように、両手法は密接に関連している。&lt;/p&gt;'><sup>41</sup></a>。</p>
<p>Chapter <a href="pub-bias.html#interpretation-p-curve-results">9.2.2.1.3</a> で設定した基準を適用すると、このデータには証拠能力があることがわかる。次の行では、<span class="math inline">\(p\)</span> が 0.938 から 1 までで、3 つの平坦性検定が<strong>有意でない</strong>ことがわかる。これは、非常に論理的に、証拠能力がないわけでも不十分なわけでもないことを教えてくれる。同じ解釈は、出力の <code>Evidential value</code> セクションでも提供されている。</p>
<p>この関数による <span class="math inline">\(p\)</span>-曲線は、3 種類の線を描く。 実線は、データに基づく経験的な <span class="math inline">\(p\)</span> -曲線。破線は、33% の検出力を仮定して期待される <span class="math inline">\(p\)</span> -値の分布。点線は、効果がないときに期待される一様な分布を表している。実線は目に見えて右に歪んでおり、ちょうど研究が真の効果を測定しているときに期待されるようなものである。</p>
<p>全体として、これらの結果は、証拠能力の存在を示し、真の非ゼロ効果があることを示している。出版バイアスがメタ分析の結果に影響を及ぼしていることは、まだ否定できない。しかし、p-曲線の結果に基づいて、私たちが見つけたプール効果は完全に偽りのものではなく、選択的な報告によって生み出された単なる「蜃気楼」でもないと結論づけることができる。</p>
<p>興味深いことに、この知見は、いくつかの少量調査効果法を用いて得られた結果とあまり一致していない。PET-PEESE (Chapter <a href="pub-bias.html#pet-peese">9.2.1.5</a>) と限界メタ分析法 (Chapter <a href="pub-bias.html#rucker-ma">9.2.1.6</a>) はともに、補正平均効果を約0と推定してきた<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;注意深く見ると、小規模試験効果法では外れ値が除去されておらず、これが異なる結果の原因となっている可能性があることを認識されただろう。この可能性を確認するために、統計的外れ値を除いた PET-PEESE と限界メタ分析を再実行したところ、以前とほぼ同じ結果になる。 &lt;em&gt;R&lt;/em&gt; で検証されたい。&lt;/p&gt;"><sup>42</sup></a>。</p>
<p><br></p>
</div>
</div>
<div id="p-curve-es" class="section level4" number="9.2.2.2">
<h4>
<span class="header-section-number">9.2.2.2</span> P 曲線効果量推定値<a class="anchor" aria-label="anchor" href="#p-curve-es"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p>メタ分析に証拠能力があるかどうかを判断するために、経験則に基づく <span class="math inline">\(p\)</span> -曲線の分析がどのように利用できるかを学習してきた。しかし、この方法を用いて決定的な結果を得ても、私たちの洞察はやや限定的なものにとどまるだろう。データに真の効果があることを知ることは非常に有用であるが、この真の効果がどの程度大きいかを知ることができれば、さらによいだろう。幸いなことに、p-曲線はこの問題にも役立ってくれる。研究のサンプルサイズがわかっていれば、<span class="math inline">\(p\)</span> -曲線の形状に最も合う真の効果量を探すことが可能である。</p>
<p></p>
<p>これがどのように実現可能なのかを理解するために、まず、<strong>非心分布</strong> (non-central distribution) の概念と、それが効果量にどのように関係するかを議論する必要がある。非心分布とは何かを例証するために、間違いなく最も一般的な統計的検定である2標本 <span class="math inline">\(t\)</span>-検定から始める。<span class="math inline">\(t\)</span>-検定は、2 つのグループの平均が異なるかどうかを調べるためによく使われる。</p>
<p><span class="math inline">\(t\)</span>-検定における帰無仮説は、両平均値 <span class="math inline">\(\mu_1\)</span> と <span class="math inline">\(\mu_2\)</span> は同一であり、したがって、それらの差はゼロであるということである。帰無仮説が真であるとき、<span class="math inline">\(t\)</span> 統計量は、<strong>中心</strong> <span class="math inline">\(t\)</span>-分布に従うと仮定する。中心 <span class="math inline">\(t\)</span>-分布は、標準正規分布に似ている。帰無仮説は差がないと仮定しているので、<span class="math inline">\(t\)</span>-分布はゼロを中心とする。</p>
<p></p>
<p>帰無仮説が正しくないとき、この中心 <span class="math inline">\(t\)</span> -分布は、現実をよく表していないことになる。平均値の間に真の差があるとき、<span class="math inline">\(t\)</span>-値がゼロの周りに中心を持つことは期待できない。その代わりに、<span class="math inline">\(t\)</span> 統計は、<strong>非心</strong> <span class="math inline">\(t\)</span>-分布に従う。この非心分布は通常非対称であり、より広い広がりを持つ傾向がある。</p>
<p>しかし、最も重要なことは、その中心がゼロから「シフト」していることである。このシフトの大きさは、<strong>非心パラメータ</strong> <span class="math inline">\(\delta\)</span> によって制御される。 <span class="math inline">\(\delta\)</span> が高いほど、非中心分布のピークがゼロから離れることになる。</p>
<p>下のグラフはこの挙動を表している。左側には、<span class="math inline">\(t\)</span> -分布の中心、<span class="math inline">\(\delta=\)</span> 0 が表示されている。右側には、<span class="math inline">\(t\)</span> -分布の非心、<span class="math inline">\(\delta=\)</span> 5が表示されている。右の曲線は対称性が低く、5 付近でピークになることがわかるが、対称的で中心的な <span class="math inline">\(t\)</span> -分布の中心は 0 になっている。</p>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-246-1.png" width="70%" style="display: block; margin: auto;"></div>
<p>左の中心分布は帰無仮説が正しい場合の期待値 <span class="math inline">\(t\)</span> -値を示しているのに対し、右は <strong>対立仮説</strong> が正しい場合の期待値 <span class="math inline">\(t\)</span>-値を示している。</p>
<p>別の考え方として、左の曲線は効果が<strong>ない</strong>ときの <span class="math inline">\(t\)</span> -分布を、右の曲線は効果が<strong>ある</strong>ときの分布を表していると言うことが可能である。中央の分布は、たとえば SMD が 0 であることを表し、中央でない分布は、SMD = 1.3 の効果に対する期待値 <span class="math inline">\(t\)</span>-値の分布を表す (この値は仮のもの)。効果量が大きいと (つまり、2 つのサンプル間の差が大きいと)、非心パラメータ <span class="math inline">\(\delta\)</span> は高くなり、非心分布は 0 からますます離れていくだろう。</p>
<p>先ほど述べたように、非心 <span class="math inline">\(t\)</span>-分布は、<span class="math inline">\(t\)</span> -検定において対立仮説をモデル化するために用いることが可能である。しかし、統計の教科書に非心分布が載っているのは珍しいことで、それは通常、非心分布は<strong>必要</strong>ないためである。統計的仮説検定では、通常、対立仮説は<strong>非特異的</strong>である。2 サンプル <span class="math inline">\(t\)</span>-検定を計算するとき、帰無仮説 (「群間に差がない」) にしか興味がない。データが帰無仮説にうまく当てはまらないとき、これを棄却し、<strong>何らかの</strong>効果が存在すると結論づける。</p>
<p>このような検定における対立仮説は、帰無仮説の反対で、2つのサンプル間の平均差が<strong>ゼロではない</strong>ことであり、効果がこのサイズまたはこのサイズであることではないのである。</p>
<p></p>
<p>具体的な対立仮説が必要になるのは、通常、統計的検定の<strong>検出力</strong>を計算するときだけである。実験を行う場合、<strong>偽陰性</strong>の確率が20％以下になるように十分なサンプルサイズを計画するのが通例である。適切なサンプルサイズを用いることで、真の効果が存在する場合に、それを確実に検出できるようにしたいのである。このように、統計的検定が真の効果を発見する確率が、その統計的検出力である。これは、1マイナス偽陽性の確率と定義され、<span class="math inline">\(\beta\)</span> としても知られている。</p>
<p><span class="math inline">\(t\)</span> -検定に必要なサンプルサイズを計算するために、非心 <span class="math inline">\(t\)</span>-分布が必要である。なぜなら、それは効果があるときの <span class="math inline">\(t\)</span> -値の期待される振る舞いを示すからである。サンプルサイズを計算するために、また真の効果量について値を仮定する必要がある。なぜなら、それは非心パラメータ <span class="math inline">\(\delta\)</span> に影響し、したがって非心分布の形状に影響を与えるからである。</p>
<p>これらの断片をまとめると、非心 <span class="math inline">\(t\)</span>-分布の形状、したがって統計的検出力は、2つのものだけで制御されることがわかる: サンプルサイズと、真の根本的な効果である。同じことが、<span class="math inline">\(p\)</span> -曲線の形状にも当てはまる。その右歪度は、サンプルサイズとデータの真の効果に依存する。これは重要な観察で、<span class="math inline">\(p\)</span> -曲線内の研究のサンプルサイズがわかれば、その真の効果量も推定できることを意味する。</p>
<p>p-曲線がどのようにこれを実現するかを見るために、小さな例を見てみよう。独立2サンプル <span class="math inline">\(t\)</span> -検定 (両群の分散が等しいと仮定) の場合、<span class="math inline">\(t\)</span> の値は、群間平均差 <span class="math inline">\(\text{MD}_{\text{between}}\)</span> をその標準誤差 <span class="math inline">\(SE_{\text{MD}_{\text{between}}}\)</span> で割ったものに等しくなる。</p>
<p><span class="math display" id="eq:pub15">\[\begin{equation}
t_{\text{d.f.}}= \frac{\text{MD}_{\text{between}}}{SE_{\text{MD}_{\text{between}}}}
\tag{9.15}
\end{equation}\]</span></p>
<p>群間平均差と標準誤差の式 (Chapter <a href="effects.html#b-group-md">3.3.1.1</a> の式 3.14 と式 3.15 参照) を入れると、次の式になる。</p>
<p><span class="math display" id="eq:pub16">\[\begin{equation}
t_{n_{1}+n_{2}-2} = \frac{\hat\mu_{1}-\hat\mu_{2}}{s_{\text{pooled}}\sqrt{\dfrac{1}{n_1}+\dfrac{1}{n_2}}}
\tag{9.16}
\end{equation}\]</span></p>
<p>この式から、<span class="math inline">\(t\)</span> の自由度は、両群のサンプルサイズを合わせたもの (<span class="math inline">\(n_1+n_2\)</span>) から2を引いたものと定義されることがわかる。</p>
<p>この式を使って、一次研究で報告されたデータから <span class="math inline">\(t\)</span>-値を計算することが可能である。ある研究で、実験群に <span class="math inline">\(n_1=\)</span> 30人、対照群に <span class="math inline">\(n_2 =\)</span> 20 人の参加者がいたとする。この研究では、第 1 群と第 2 群の平均がそれぞれ 13 と 10 で、両群の標準偏差が 5 であったと報告されている。このデータに基づいて、次のコードを使って <span class="math inline">\(t\)</span> を計算することができる。</p>
<div class="sourceCode" id="cb285"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 平均差を計算</span></span>
<span><span class="va">md</span> <span class="op">&lt;-</span> <span class="fl">13</span><span class="op">-</span><span class="fl">10</span></span>
<span></span>
<span><span class="co"># 平均差の標準誤差を計算</span></span>
<span><span class="va">n1</span> <span class="op">&lt;-</span> <span class="fl">30</span></span>
<span><span class="va">n2</span> <span class="op">&lt;-</span> <span class="fl">20</span></span>
<span><span class="va">s1</span> <span class="op">&lt;-</span> <span class="va">s2</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span><span class="va">s_pooled</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">(</span><span class="op">(</span><span class="op">(</span><span class="va">n1</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">*</span><span class="va">s1</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="op">(</span><span class="va">n2</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">*</span><span class="va">s2</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">/</span></span>
<span>                   <span class="op">(</span><span class="op">(</span><span class="va">n1</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">+</span><span class="op">(</span><span class="va">n2</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">se</span> <span class="op">&lt;-</span> <span class="va">s_pooled</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">(</span><span class="va">n1</span><span class="op">+</span><span class="va">n2</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="va">n1</span><span class="op">*</span><span class="va">n2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># t-値を計算 (分散の等しい２ーサンプル t 検定と同じ) </span></span>
<span><span class="va">md</span><span class="op">/</span><span class="va">se</span></span></code></pre></div>
<pre><code>## [1] 2.078461</code></pre>
<p>結果は、<span class="math inline">\(t_{48} =\)</span> 2.078 である。この結果は、両者の平均が同一であり、影響がないという帰無仮説を支持するか？</p>
<p>この質問に答えるには、<code>pt</code> 関数を使用することができる。この関数は、d.f. = 48 <strong>かつ</strong>帰無仮説が真であると仮定するとき、<span class="math inline">\(t\)</span>-値 が 2.078 より大きいことを発見する確率を与える。この確率は、片側 <span class="math inline">\(t\)</span>-検定の <span class="math inline">\(p\)</span>-値に等しい。</p>
<div class="sourceCode" id="cb287"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span><span class="fl">2.078</span>, df <span class="op">=</span> <span class="fl">48</span>, lower.tail <span class="op">=</span> <span class="cn">F</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.0215403</code></pre>
<p>結果は、<span class="math inline">\(p=\)</span> 0.02 で、検定が有意であることを意味する。したがって、実験群の効果がゼロ (または負) であるという帰無仮説を棄却する。その結果、対立仮説を受け入れる: 実験群に有利な正の効果がある (より高いスコアがより良いアウトカムを表すと仮定)。</p>
<p><span class="math inline">\(t\)</span> 検定の帰無仮説の基礎となる中心 <span class="math inline">\(t\)</span> -分布は、私たちの経験的データにはあまり合わないことがわかっている。また、非心 <span class="math inline">\(t\)</span> -分布が私たちのデータによく合うことも分かっている。しかし、どちらなのかは分からない。今のところ、どの真の効果量、したがって、どの非心パラメータ <span class="math inline">\(\delta\)</span> が、経験的な <span class="math inline">\(t\)</span> -値が引き出された母集団を本当に表しているかを推測することができるだけである。</p>
<p>最初の推測として、発見の背後にある真の効果量は、標準化平均差 <span class="math inline">\(\theta=\)</span> 0.6であると仮定することが可能である。これは、中〜大の効果があったために、<span class="math inline">\(t=\)</span> 2.078 となったことを意味する。この <span class="math inline">\(\theta\)</span> の値に基づいて、非心性パラメータは次の式で計算される。</p>
<p><span class="math display" id="eq:pub15">\[\begin{equation}
\delta = \frac{\theta}{\sqrt{\dfrac{n_{1}+n_{2}}{n_{1}n_{2}}}}
\tag{9.15}
\end{equation}\]</span></p>
<p>ここで、<span class="math inline">\(n_1\)</span> と <span class="math inline">\(n_2\)</span> は両グループのサンプルサイズである。この例では、非心性パラメータ <span class="math inline">\(\delta\)</span> を次のコードで計算することができる。</p>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">theta</span> <span class="op">&lt;-</span> <span class="fl">0.6</span></span>
<span><span class="va">delta</span> <span class="op">&lt;-</span> <span class="va">theta</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">(</span><span class="va">n1</span><span class="op">+</span><span class="va">n2</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="va">n1</span><span class="op">*</span><span class="va">n2</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Show delta</span></span>
<span><span class="va">delta</span></span></code></pre></div>
<pre><code>## [1] 2.078461</code></pre>
<p><span class="math inline">\(\delta=\)</span> 2.078 の時の非心分布 <span class="math inline">\(t\)</span> -分布がどのように見えるかを見るために、少しシミュレーションをしてみよう。<code>rt</code> 関数を用いて、自由度 48 の 100 万個のランダムな <span class="math inline">\(t\)</span> -値を 2 回描く。1 回は非心パラメータを 0 と仮定したとき (これは効果がないというヌル値に等しい)、もう 1 回は先ほど計算した <span class="math inline">\(\delta\)</span> の値 (つまり、真の効果は SMD = 0.6) を用いて描く。</p>
<p>次に、パイプと <code>hist</code> 関数を使って、 <em>R</em> に両シミュレーションのヒストグラムを描かせる。</p>
<div class="sourceCode" id="cb291"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># '1 のあとに 0 が 6 つ' は、R では '1e6' と書くこともできる</span></span>
<span><span class="co"># "tidyverse" パッケージがロードされていること (パイプ用) </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">rt</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">1e6</span>, df <span class="op">=</span> <span class="fl">48</span>, ncp <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fl">100</span>, </span>
<span>       col <span class="op">=</span> <span class="st">"gray50"</span>,</span>
<span>       xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>,<span class="fl">8</span><span class="op">)</span>, </span>
<span>       ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">40000</span><span class="op">)</span>,</span>
<span>       xlab <span class="op">=</span> <span class="st">"t-value"</span>,</span>
<span>       main <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">rt</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">1e6</span>, df <span class="op">=</span> <span class="fl">48</span>, ncp <span class="op">=</span> <span class="va">delta</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fl">100</span>, </span>
<span>       col <span class="op">=</span> <span class="st">"gray95"</span>,</span>
<span>       xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>,<span class="fl">8</span><span class="op">)</span>, </span>
<span>       ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">40000</span><span class="op">)</span>, </span>
<span>       add <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></span></code></pre></div>
<p>これが結果のプロットである。</p>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-251-1.png" width="75%" style="display: block; margin: auto;"></div>
<p>その中で、左側に中心の <span class="math inline">\(t\)</span>-分布 (効果なし)、右側に非心分布 (<span class="math inline">\(\theta=\)</span> 0.6) を見ている。すでに適度な大きさのサンプル (<span class="math inline">\(N =\)</span> 50) があるので、非心分布は、前の図よりも右に歪んでいないように見える。それでも、私たちの仮定した対立仮説の分布は右にシフトし、<span class="math inline">\(\delta\)</span> の値でピークになることがはっきりわかる。</p>
<p>もちろん、中心的な疑問は、この代替分布が本当に正しい分布であり、真の効果が実際には <span class="math inline">\(\theta=\)</span> 0.6 であるとき、<span class="math inline">\(t_{48} =\)</span> 2.078 より大きい値を得る可能性はどの程度あるのだろうかということである。この質問を検証するために、再び <code>pt</code> 関数を使用することができるが、今回は想定した非心性パラメータ <span class="math inline">\(\delta\)</span> も提供する。この情報は <code>ncp</code> 引数を用いて追加することが可能である。どのような結果が得られるか、確認してみよう。</p>
<div class="sourceCode" id="cb292"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># t=2.078 を使用</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span><span class="fl">2.078</span>, df <span class="op">=</span> <span class="fl">48</span>, ncp <span class="op">=</span> <span class="va">delta</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.5044537</code></pre>
<p>指定された対立仮説のもとで、私たちの結果より大きな値を得る確率は、およそ50％であることがわかる。これは、約半分の値が、私たちが見つけた <span class="math inline">\(t\)</span>-値より高く、残りの半分は低いと予想されることを意味する。全体として、これは自由度 48 と真の効果 0.6 を仮定した非心 <span class="math inline">\(t\)</span>-分布が、私たちの発見を非常によく近似していることを示している。この研究の真の母集団効果は、SMD = 0.6 である可能性が非常に高いと思われる。</p>
<p>今行ったステップは、本質的に、p-curve が真の効果量を決定するために使用するものでもある。 <span class="math inline">\(p\)</span> -曲線におけるすべての有意な <span class="math inline">\(p\)</span> -値について、<span class="math inline">\(t\)</span> より大きい値を得る確率を計算する。ただし、</p>
<ol style="list-style-type: decimal">
<li><p>ある効果量／非中心性パラメータ。</p></li>
<li><p><span class="math inline">\(p\)</span>-値は、自由度 <span class="math inline">\(x\)</span> (これは研究のサンプルサイズから導き出せる) に基づくこと。</p></li>
<li><p>有意な値 (<span class="math inline">\(p&lt;\)</span> 0.05) のみが <span class="math inline">\(p\)</span>-曲線に含まれることを知ること。</p></li>
</ol>
<p>この結果、重要な研究 <span class="math inline">\(k\)</span> ごとに <span class="math inline">\(pp\)</span>-値が設定されることになる。先ほど説明したことに基づいて、研究 <span class="math inline">\(k\)</span> の <span class="math inline">\(pp\)</span>-値の式は次のように表すことが可能である。</p>
<p><span class="math display" id="eq:pub16">\[\begin{equation}
pp(t_k) = \mathrm{P}(t&gt;t_k~\vert~\delta,~\text{d.f.},~p&lt;0.05)
\tag{9.16}
\end{equation}\]</span></p>
<p></p>
<p>研究の自由度は通常知られているので、式中の唯一の未知数は、<span class="math inline">\(\delta\)</span> 、したがって真の効果量 <span class="math inline">\(\theta\)</span> である。しかし、正しい真の効果量/ <span class="math inline">\(\delta\)</span> -値を仮定すると、<span class="math inline">\(pp\)</span> -値の分布が<strong>一様</strong>になることが分かっているので、この真の効果量を<strong>見つけることが可能である</strong>。私たちの知見が帰無仮説に合致するとき <span class="math inline">\(p\)</span> -値が一様分布に従うように、結果が<strong>正しい</strong>非心分布 (すなわち、点対立仮説) に合致するとき <span class="math inline">\(pp\)</span> -値は一様に分布するのである。</p>
<p>したがって、私たちは、たくさんの可能な<strong>効果量の候補</strong>を試し、得られた <span class="math inline">\(\delta\)</span> -値を上記の式に差し込み、得られた <span class="math inline">\(pp\)</span> -値の歪度を評価すればよいのである。そして、<span class="math inline">\(pp\)</span>-値の一様分布に最も近い効果量候補が、真の効果の推定値を表す。P-curve は、いわゆる Kolmogorov-Smirnov (KS) 検定の <span class="math inline">\(D\)</span> 距離メトリックを使用して、<span class="math inline">\(pp\)</span> 分布が一様分布からどのくらい逸脱しているかを把握する。</p>
<p></p>
<p>P-曲線の効果推定法は <code>pcurve</code> 関数にも実装されている。これを利用するには、 <code>effect.estimation</code> 引数を <code>TRUE</code> に設定する必要がある。また、各研究のサンプルサイズである <code>N</code> を指定する必要がある。最後に、効果量の候補の探索空間を <code>dmax</code> と <code>dmin</code> を用いて制御することが可能である。ここでは、Cohen’s <span class="math inline">\(d=\)</span> 0 と 1 の間の効果量を検索するように <code>pcurve</code> に指示する。<code>dmin</code> は常に 0 以上でなければならないことに注意してみよう–p-曲線が検出できる最小値は効果なしである。</p>
<div class="sourceCode" id="cb294"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 実験群(n1) と対照群 (n2) のサンプルサイズを追加</span></span>
<span><span class="co"># 研究３と６のサンプルサイズを削除</span></span>
<span><span class="va">n1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">62</span>, <span class="fl">72</span>, <span class="fl">135</span>, <span class="fl">103</span>, <span class="fl">71</span>, <span class="fl">69</span>, <span class="fl">68</span>, <span class="fl">95</span>, </span>
<span>        <span class="fl">43</span>, <span class="fl">79</span>, <span class="fl">61</span>, <span class="fl">62</span>, <span class="fl">60</span>, <span class="fl">43</span>, <span class="fl">64</span>, <span class="fl">63</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">51</span>, <span class="fl">78</span>, <span class="fl">115</span>, <span class="fl">100</span>, <span class="fl">79</span>, <span class="fl">62</span>, <span class="fl">72</span>, <span class="fl">80</span>, </span>
<span>        <span class="fl">44</span>, <span class="fl">72</span>, <span class="fl">67</span>, <span class="fl">59</span>, <span class="fl">54</span>, <span class="fl">41</span>, <span class="fl">66</span>, <span class="fl">55</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 効果推定ありで P 曲線分析を実行</span></span>
<span><span class="fu"><a href="http://dmetar.protectlab.org/reference/pcurve.html">pcurve</a></span><span class="op">(</span><span class="va">m.gen_update</span>, </span>
<span>       effect.estimation <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>       N <span class="op">=</span> <span class="va">n1</span><span class="op">+</span><span class="va">n2</span>, </span>
<span>       dmin <span class="op">=</span> <span class="fl">0</span>,</span>
<span>       dmax <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## P-curve analysis 
##  ----------------------- 
## [...]
##    
## P-curve's estimate of the true effect size: d=0.389  </code></pre>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-254-1.png" width="45%" style="display: block; margin: auto;"></div>
<p>出力には、真の効果量の推定値と効果量探索の結果を示すプロットという2つの新しい要素が含まれる。プロットでは、効果量の候補が滑らかな V 字型の勾配を形成し、それは効果量 <span class="math inline">\(d=\)</span> 0.389 でピークに達した。この時点で、計算された <span class="math inline">\(pp\)</span> 分布と一様分布 (Y 軸の <span class="math inline">\(D\)</span> の値で表される) との差は最小であり、これは真の効果の最良推定値を表していることを意味する。</p>
<p>重要なことは、p-曲線の効果量の推定は、このプロットのようなV字型のときだけ信頼できるということであ。他の不規則な形状は、p-curveが最小値を発見していない可能性を示している。滑らかな下降線を持つプロットは、探索空間が単に狭すぎることを示すだろう。この場合、より高い <code>dmax</code> 値で分析を再実行することは理にかなっている。</p>
<p>全体として、p-曲線の推定値 <span class="math inline">\(d=\)</span> 0.389 は、メタ分析で見つけたプール効果 (外れ値を除くと <span class="math inline">\(g=\)</span> 0.45) よりもいくらか低い。しかし、それでも十分に大きく、前回の発見、すなわち、研究には証拠能力があるということと一致する。</p>
<div class="boxreport">
<p>
<strong>P-曲線解析結果の報告</strong>
</p>
<p>
p
曲線解析の結果を報告する際には、少なくとも3つの右歪度検定と平坦性の検定の<span class="math inline"><span class="math inline">\(p\)</span></span>値、およびこれらの結果をどのように解釈したかを記載するとよい。真の効果の大きさが推定されたときは、これも含めるべきである。結果は、次のような表にまとめることができる。
</p>
</div>
<div class="inline-table"><table class="table table-condensed table" style="margin-left: auto; margin-right: auto; font-size: 14px; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Full Curve
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Half Curve
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Evidential Value
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
<span class="math inline">\(p_{\text{Binomial}}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(z_{\text{Full}}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(p_{\text{Full}}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(z_{\text{Half}}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(p_{\text{Half}}\)</span>
</th>
<th style="text-align:left;">
present
</th>
<th style="text-align:left;">
absent
</th>
<th style="text-align:right;">
<span class="math inline">\(\hat{d}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Right-Skewness Test
</td>
<td style="text-align:left;">
0.020
</td>
<td style="text-align:right;">
-3.80
</td>
<td style="text-align:left;">
&lt;0.001
</td>
<td style="text-align:right;">
-2.74
</td>
<td style="text-align:left;">
0.003
</td>
<td style="text-align:left;">
yes
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
0.39
</td>
</tr>
<tr>
<td style="text-align:left;">
Flatness Test
</td>
<td style="text-align:left;">
0.952
</td>
<td style="text-align:right;">
1.54
</td>
<td style="text-align:left;">
0.938
</td>
<td style="text-align:right;">
3.42
</td>
<td style="text-align:left;">
&gt;0.999
</td>
<td style="text-align:left;">
yes
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
0.39
</td>
</tr>
</tbody>
</table></div>
<div class="boxempty">
<p>
p-曲線の開発者は、各解析について、結果が論文のどの部分から抽出され、どのように報告されたかを記述した<strong>開示表</strong>を作成することを強く推奨している。このような開示表の例は、他のいくつかの実用的なガイドラインと一緒に、Simonsohn
ら <span class="citation"><span class="citation">(<a href="references.html#ref-simonsohn2014p">2014b</a>)</span></span>
に記載されている。
</p>
</div>
<div class="boximportant">
<p>
<strong>P-曲線と群間異質性</strong>
</p>
<p>
P-曲線解析から外れ値の研究を除外した理由については、まだ説明する義務がある。外れ値も含めたメタ分析では、研究間の異質性が
<span class="math inline"><span class="math inline">\(I^2=\)</span></span> 63%
となり、非常に大きな値となった。これは、研究間の異質性が高い場合、p曲線は真の効果量を推定するのに頑健な方法ではないことが分かっているので問題である。
</p>
<p>
そこで Van Aert ら <span class="citation"><span class="citation">(<a href="references.html#ref-aert2016conducting">2016</a>)</span></span>
は、異質性が小から中程度の場合にのみ
p-曲線を使用することを提案している。彼らは p
曲線が適用できるかどうかを判断する経験則として、<span class="math inline"><span class="math inline">\(I^2=\)</span></span>
50%という閾値を提案した。メタ分析における研究間の異質性がこれよりも高い場合の回避策の一つは、例で行ったように、外れ値を含まない効果量をp曲線で表す。さらに良い解決策は、意味のある研究のサブグループが存在する場合、そのサブグループで別の分析を行うことである。
</p>
</div>
<p><br></p>
</div>
</div>
<div id="selection-models" class="section level3" number="9.2.3">
<h3>
<span class="header-section-number">9.2.3</span> 選択モデル<a class="anchor" aria-label="anchor" href="#selection-models"><i class="fas fa-link"></i></a>
</h3>
<hr>
<p></p>
<p>最後に取り上げるのは、いわゆる<strong>選択モデル</strong>と呼ばれる出版バイアスの手法である。選択モデルは以前から選択的出版の影響を調べるために提案されていたが <span class="citation">(<a href="references.html#ref-hedges1992modeling">L. V. Hedges 1992</a>, <a href="references.html#ref-hedges1984estimation">1984</a>; <a href="references.html#ref-iyengar1988selection">Iyengar and Greenhouse 1988</a>; <a href="references.html#ref-hedges1996estimating">L. V. Hedges and Vevea 1996</a>)</span> 、特にここ数年でその適用への関心が高まっている <span class="citation">(<a href="references.html#ref-mcshane2016adjusting">McShane, Böckenholt, and Hansen 2016</a>; <a href="references.html#ref-carter2019correcting">Carter et al. 2019</a>)</span> 。</p>
<p>上で取り上げた出版バイアス法は、すべて何らかの「理論」に基づいており、選択的出版がメタ分析の結果になぜ、どのように影響するかを説明するために使用される。例えば、Small-study Effect 法は、研究の非出版リスクはサンプルサイズと効果量に比例すると仮定した。P 曲線は、<span class="math inline">\(p\)</span>-値 0.05 が「魔法の閾値」として機能するという考えに基づいている。<span class="math inline">\(p \geq\)</span> 0.05 の結果は、一般的に統計的に有意な発見よりも、このデータで見つからない可能性がはるかに高いのである。</p>
<p>選択モデルは、これらの方法を一般化したものと見ることが可能である。このモデルは、出版バイアスが結果に影響を与えたと考えられるあらゆる種類のプロセスをモデル化することが可能である。つまり、選択モデルは、出版バイアスの発生に関する非常に単純な仮説、または非常に洗練された仮説に基づいてデータをモデル化するために使用することができるのである。</p>
<p>すべての選択モデルの背後にある考え方は、ある研究がその結果に応じて出版 (すなわち「選択」) される確率を、多くの場合非常に理想化された方法で予測する分布を指定することである。通常、この結果は研究の <span class="math inline">\(p\)</span> -値で、選択モデルは、<span class="math inline">\(p\)</span> の値を変化させたときの出版確率を返す関数のように見ることが可能である。いったんこのような選択関数が定義されると、選択的出版による想定バイアスを「除去」して、真の効果量の補正推定値を導き出すために使用することが可能である。</p>
<p>しかし、この補正された効果は、私たちが定義した選択モデルが本当に正しい場合にのみ、適切なものとなる。私たちは常に、私たちのモデルがデータにうまく適合しているように見えても、選択過程を説明する多くの方法のうちの一つに過ぎないことを心に留めておかなければならない。出版バイアスがどのような過程を経て私たちの結果を形成したかは、必然的に未知のままである。しかし、選択モデルは、出版がデータに影響を与えたかどうか、そしてより重要なことに、出版がどのようにデータに影響を与えたかを広く評価するために非常に役立つ。</p>
<p></p>
<p>この章では、<strong>ステップ関数</strong>に基づく2種類の (かなり単純な) 選択モデルを取り上げる。そこで、まずステップ関数とは何かを明らかにする。</p>
<p><br></p>
<div id="step-function-selmodels" class="section level4" number="9.2.3.1">
<h4>
<span class="header-section-number">9.2.3.1</span> ステップ関数選択モデル<a class="anchor" aria-label="anchor" href="#step-function-selmodels"><i class="fas fa-link"></i></a>
</h4>
<hr>
<p>選択モデル分析を行うには、<strong>効果量モデル</strong>と<strong>選択モデル</strong>の2つの要素が必要である。この2つのモデルは、ある入力値 <span class="math inline">\(x\)</span> を使って、その値の確率を返す <strong>関数</strong> と考えることができる。</p>
<p>式 <span class="math inline">\(f(x_k)\)</span> で示される効果量モデルは、ランダム効果モデルに等しい。漢族された効果量 <span class="math inline">\(\hat\theta_k\)</span> は、平均効果 <span class="math inline">\(\mu\)</span> の周りを、サンプリング誤差と群間異質性 <span class="math inline">\(\tau^2\)</span> から偏差した正規分布に従う。<span class="math inline">\(\mu\)</span> と研究の標準誤差 <span class="math inline">\(\tau^2\)</span> と効果量が正規分布に従うことを知っていれば、出版バイアスがないと仮定して、効果量の値 <span class="math inline">\(x_k\)</span> をどの程度かを <span class="math inline">\(f(x_k)\)</span> は予測する。</p>
<p>しかし、出版バイアスがあるとき、効果量分布と、<span class="math inline">\(f(x)\)</span> 自体が現実をうまく現さなくなっている。出版の選択により、いくつかの研究はデータの中で過剰に代表されている。おそらく、驚くほど効果量が高く、サンプルサイズは小さい。このため、知らずして、プールモデルに高い重みを与えてしまっている。よって、いくつかの研究は他の研究よりも高い確率で入っていること、そしてその研究には高い「重み」が与えられていることを考慮した、より現実的な <span class="math inline">\(f(x)\)</span> を導き出す必要がある。</p>
<p></p>
<p>これを、<strong>重み関数</strong> (weight function) <span class="math inline">\(w(p_k)\)</span> で行う。重み関数は、ある研究 <span class="math inline">\(k\)</span> の <span class="math inline">\(p\)</span> 値から選択確率を与える。これを使って、出版バイアスメカニズムを組み込んだ修正版の <span class="math inline">\(f(x_k)\)</span> を定義する。<span class="math inline">\(f^*(x_k)\)</span> は、以下の式で表される <span class="citation">(<a href="references.html#ref-vevea2005publication">Vevea and Woods 2005</a>)</span>。</p>
<p><span class="math display" id="eq:pub17">\[\begin{equation}
f^*(x_k) = \frac{w(p_k)f(x_k)}{\int w(p_k) f(x_k) dx_k}
\tag{9.17}
\end{equation}\]</span></p>
<p>ここで、分数の分母は <span class="math inline">\(w(p_k) f(x_k)\)</span> の積分である。式中の重み関数 <span class="math inline">\(w(p_k)\)</span> は、仮定選択モデルを表す。</p>
<p></p>
<p><span class="math inline">\(w(p_k)\)</span> は、技術的にはどのような形式にもなるが、よく現されるのは<strong>ステップ関数</strong>である <span class="citation">(<a href="references.html#ref-hedges1996estimating">L. V. Hedges and Vevea 1996</a>)</span>。<span class="math inline">\(w(p_k)\)</span> をステップ関数とすると、同じセグメントに入る <span class="math inline">\(p_k\)</span> 値 (例えば 0.05 未満の全ての <span class="math inline">\(p\)</span> 値) は、等しい確率で選択される。この区間別選択確率は <span class="math inline">\(\omega_i\)</span> と現され、区間ごとに変わる。<span class="math inline">\(p\)</span> 値が取りうる値をいくつかのセグメントに分け、それぞれの選択確率を <span class="math inline">\(\omega_1\)</span>, <span class="math inline">\(\omega_2\)</span>, …, <span class="math inline">\(\omega_c\)</span> とする。</p>
<p>セグメントの幅は、<strong>カットポイント</strong> (ここでは <span class="math inline">\(a_i\)</span> で示す) によって決まる。カットポイントの数と正確な値は、自由に選ぶことが可能である。例えば、<span class="math inline">\(w(p_k)\)</span> が4つのセグメント(従って4つのカットポイント)を含むとき、その内部構造を次のように定義することができる。</p>
<p><span class="math display" id="eq:pub18">\[\begin{equation}
  w(p_k) =\begin{cases}
    \omega_1~~~\text{if}~~~0 \leq p_k \leq a_1 \\
    \omega_2~~~\text{if}~~~a_1 \leq p_k \leq a_2 \\
    \omega_3~~~\text{if}~~~a_2 \leq p_k \leq a_3 \\
    \omega_4~~~\text{if}~~~a_3 \leq p_k \leq a_4~~~(\text{where}~~~a_4=1).
  \end{cases}
  \tag{9.18}
\end{equation}\]</span></p>
<p>任意の <span class="math inline">\(p\)</span> 値に対して、上記の関数は、私たちの値が入る <span class="math inline">\(p\)</span> -値の区間に基づいて、特定の選択確率 <span class="math inline">\(\omega\)</span> (訳注: <span class="math inline">\(\omega\)</span> は、「オメガ」と読み、<span class="math inline">\(w\)</span> と似ているが異なる文字である。) を返すことがわかる。これをより具体的にするために、カットポイント <span class="math inline">\(a_i\)</span> と選択確率 <span class="math inline">\(\omega_i\)</span> に実際の値を記入した選択モデルを定義してみる。</p>
<p>例えば、メタ分析における出版バイアスのメカニズムは、3つのカットポイントで記述できると仮定可能である。まず、<span class="math inline">\(a_1=\)</span> 0.025がある。この値は、片側 <span class="math inline">\(p\)</span>-値が 0.025、両側 <span class="math inline">\(p\)</span>-値が 0.05 に相当する。 <span class="math inline">\(\omega_1\)</span> これはほとんどの研究で使われている従来の有意水準なので、<span class="math inline">\(p\)</span>-値 のより小さい <span class="math inline">\(a_1=\)</span> 0.025 の選択確率はすべて100％であると仮定するのは理にかなっている。結局のところ、結果が陽性だった研究をファイルの引き出しに入れる理由はないのである。次に定義するカットポイントは、<span class="math inline">\(a_2=\)</span> 0.05である。この範囲の結果については、選択確率を80%とする。それでもまだ高いが、明らかに有意な結果と比べると低くなる。次に、<span class="math inline">\(a_2=\)</span> 0.05 から <span class="math inline">\(a_3=\)</span> 0.5 までの大きな区間を指定し、この区間では選択確率が60%になるようにする。最後に、非常に高い <span class="math inline">\(\geq\)</span> 0.5 の <span class="math inline">\(p\)</span>-値の研究については、<span class="math inline">\(\omega_4=\)</span> 35% とさらに低い確率を定義する。</p>
<p>その結果、以下の Figure <a href="pub-bias.html#fig:stepcurve">9.2</a> に描かれているような選択モデルが生まれる。</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:stepcurve"></span>
<img src="Doing_Meta_Analysis_in_R_files/figure-html/stepcurve-1.png" alt="ステップ関数に基づいた選択モデル。" width="56%"><p class="caption">
Figure 9.2: ステップ関数に基づいた選択モデル。
</p>
</div>
<p>ステップ関数に基づく選択モデルを定義する場合、通常、カットポイント <span class="math inline">\(a_i\)</span> のみを指定する。これがこのモデルにおける唯一の固定パラメータで、選択確率 <span class="math inline">\(\omega = \omega_1, \omega_2, \dots, \omega_c\)</span> はデータから推定する。そして、式 9.20 の式に基づいて、選択モデルをデータに当てはめることが可能である。このとき、最尤法を使って、<span class="math inline">\(\omega\)</span> を共同で推定し、さらに、<span class="math inline">\(\mu\)</span> と <span class="math inline">\(\tau^2\)</span> の補正推定値 (異なる選択確率を考慮したもの) <span class="math inline">\(\omega\)</span> を推定する。その結果、<span class="math inline">\(\mu\)</span> の補正された推定値は、想定される出版バイアスのメカニズムを制御した場合の真の平均効果量を表している。</p>
<p>以前は、選択確率 <span class="math inline">\(\omega\)</span> を0%から100%までのパーセンテージで表現していた。しかし、選択モデルをあてはめるときには、<span class="math inline">\(\omega_i\)</span> は絶対的な選択確率としてではなく、選択の<strong>相対的な尤度</strong> という観点から推定される。これは、ステップ関数の最初の区間に基準値1を与えて、<span class="math inline">\(\omega\)</span> の他のすべての値は、この基準群との<strong>関係で</strong>選択の尤度を表すということである。たとえば、2 番目の区間で <span class="math inline">\(\omega_2\)</span> = 0.5 と推定すると、この区間の研究は、最初の区間 (<span class="math inline">\(\omega_1 = 1\)</span>) と比較して、選択される可能性が半分しかなかったことを意味する。</p>
<p>もちろん、真の平均効果 <span class="math inline">\(\mu\)</span> の補正された推定値は、選択モデル自体が適切である場合にのみ正確となる。その目安は、選択モデル・パラメーターの尤度比検定 (LRT) が有意であることである。この検定は、選択がなく、相対選択尤度がすべての区間で同一である (すなわち、<span class="math inline">\(\omega_1 = \omega_2 = \dots = \omega_c\)</span> ) という帰無仮説に基づく。しかし、この有意性検定は、しばしば反保守的な結果を出すことが分かっている<span class="citation">(<a href="references.html#ref-hedges1996estimating">L. V. Hedges and Vevea 1996</a>)</span>ことに注意しなければならない。つまり、その結果は慎重に解釈されるべきである。</p>
<p>理論的には、選択モデルで使用するカットポイント <span class="math inline">\(a_i\)</span> の数は <strong>ad libitum</strong> (自由) に選択することが可能である。しかし、カットポイントを追加するごとに、<span class="math inline">\(\omega_i\)</span> の値を追加で推定しなければならない。メタ分析の規模にもよるが、これはすぐに、各区間で利用可能な研究がわずかである、という問題につながる。これは、各 <span class="math inline">\(\omega_i\)</span> を適切に推定することをますます困難にしている。したがって、多くのカットポイントを持つ複雑な選択モデルは、研究の数が多いときにのみ適用できる (つまり、<span class="math inline">\(K \geq\)</span> 100)。</p>
<p></p>
<p>残念ながら、ほとんどのメタ分析では、少数の研究しか含まれていない。これは、非常に少ないカットポイントを持つ単純な選択モデルしか適用できないことを意味する。このような単純なモデルの1つの変形が、次に説明する<strong>3パラメータ選択モデル</strong>である。このモデルは、含まれる研究の数が少ない場合にも適用できるという利点がある (例: <span class="math inline">\(K=\)</span> 15–20)。</p>
<p><br></p>
<div id="three-param-selmodel" class="section level5" number="9.2.3.1.1">
<h5>
<span class="header-section-number">9.2.3.1.1</span> ３パラメータ選択モデル<a class="anchor" aria-label="anchor" href="#three-param-selmodel"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p>3 パラメータモデルは、カットポイントが1つしかない選択モデルである<span class="citation">(<a href="references.html#ref-mcshane2016adjusting">McShane, Böckenholt, and Hansen 2016</a>)</span>。真の効果 <span class="math inline">\(\mu\)</span> 、研究間異質性分散 <span class="math inline">\(\tau^2\)</span> 、第 2 区間の相対尤度 <span class="math inline">\(\omega_2\)</span> の 3 パラメータだけを推定する必要があるので、<strong>3 パラメータ</strong> モデルと呼ばれている<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;この区間は、選択尤度を 1 に固定した参照区分として機能するので、&lt;span class="math inline"&gt;\(\omega_1\)&lt;/span&gt; を推定する必要はない。&lt;/p&gt;'><sup>43</sup></a>。</p>
<p>3 パラメータ選択モデルにおいて、単一のカットポイント <span class="math inline">\(a_1\)</span> は 0.025 に設定され、これは片側 <span class="math inline">\(p\)</span>-値が 0.05 であることと等しくなっている。これは、<span class="math inline">\(p\)</span> -値の範囲を、統計的に有意とみなせるものと、有意でないものの 2 つのビンに分割するものである。したがって、<span class="math inline">\(\omega_2\)</span> は、有意でない結果が出版用に選択される確率を表している<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;P 曲線 (Chapter &lt;a href="pub-bias.html#p-curve"&gt;9.2.2&lt;/a&gt;) は、特殊なタイプの 3 パラメータ選択モデルとして見ることが可能である。これも &lt;span class="math inline"&gt;\(p\)&lt;/span&gt;-値 0.05 を選択のカットポイントとして使用したが、有意な結果 (選択確率が100％と仮定される) にのみ焦点を当てる。また、&lt;span class="math inline"&gt;\(\tau^2\)&lt;/span&gt; はゼロであると仮定される。これは、p-曲線では、データから実際に推定されるパラメータは 1 つだけ、すなわち真の効果量 &lt;span class="math inline"&gt;\(\mu\)&lt;/span&gt; であることを意味する。&lt;/p&gt;'><sup>44</sup></a>。</p>
<p></p>
<p><strong>{metafor}</strong> パッケージの <code>selmodel</code> 関数を使うと、 <em>R</em> に様々な種類の選択モデルを当てはめることが可能である<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;この文章を書いている時点では、&lt;code&gt;selmodel&lt;/code&gt; 関数は &lt;strong&gt;{metafor}&lt;/strong&gt; の &lt;strong&gt;開発版&lt;/strong&gt; からしか利用することができない。開発版の &lt;strong&gt;{metafor}&lt;/strong&gt; は、まず &lt;strong&gt;{remotes}&lt;/strong&gt; パッケージをインストールし、次のコードを実行することでダウンロード可能である。&lt;code&gt;remotes::install_github("wviechtb/metafor")&lt;/code&gt;。その後、ライブラリから &lt;strong&gt;{metafor}&lt;/strong&gt; を呼び出すと、&lt;code&gt;selmodel&lt;/code&gt; 関数が使用できるようになる。なお、これを読んでいる頃には、すでに &lt;code&gt;selmodel&lt;/code&gt; 関数は &lt;strong&gt;{metafor}&lt;/strong&gt; の標準バージョンに統合されている可能性が高いので、開発版のインストールは必要ない&lt;/p&gt;'><sup>45</sup></a>。また、3 パラメータの選択モデルにも使用することが可能であるので、これから試してみよう。前回と同様に、例として <code>ThirdWave</code> データセットを使用する。</p>
<p><code>selmodel</code> 関数は <strong>{metafor}</strong> の <code>rma</code> 関数によって作成されたメタ分析オブジェクトのみを受け取る (Chapter <a href="metareg.html#multiple-metareg-R">8.3.3</a> を参照)。したがって、まずオブジェクトを作成する必要がある。<code>rma</code> の呼び出しでは、 <strong>{meta}</strong> の <code>metagen</code> 関数 ( Chapter <a href="pooling-es.html#pre-calculated-es">4.2.1</a> ) で使用したものと同じ設定を使用する。</p>
<div class="sourceCode" id="cb296"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.metafor-project.org">metafor</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 新しいオブジェクトの名前を 'm.rma' に設定</span></span>
<span><span class="va">m.rma</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">TE</span>,        </span>
<span>             sei <span class="op">=</span> <span class="va">seTE</span>,</span>
<span>             data <span class="op">=</span> <span class="va">ThirdWave</span>,</span>
<span>             slab <span class="op">=</span> <span class="va">Author</span>,</span>
<span>             method <span class="op">=</span> <span class="st">"REML"</span>,</span>
<span>             test <span class="op">=</span> <span class="st">"knha"</span><span class="op">)</span></span></code></pre></div>
<p><code>m.rma</code> オブジェクトを使用して、<code>selmodel</code> を使用して 3 パラメータの選択モデルを適合させることが可能である。関数にステップ関数を適用することを伝えるために、<code>type</code> 引数を <code>"stepfun"</code> に設定する必要がある。引数 <code>steps</code> にはカットポイントを指定する。このモデルでは <span class="math inline">\(a_1\)</span> =0.025 となる。結果を見てみよう。</p>
<div class="sourceCode" id="cb297"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/selmodel.html">selmodel</a></span><span class="op">(</span><span class="va">m.rma</span>,</span>
<span>         type <span class="op">=</span> <span class="st">"stepfun"</span>,</span>
<span>         steps <span class="op">=</span> <span class="fl">0.025</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [...]
## 
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   0.5893  0.1274  4.6260  &lt;.0001  0.3396  0.8390  *** 
## 
## Test for Selection Model Parameters:
## LRT(df = 1) = 0.0337, p-val = 0.8544
## 
## Selection Model Results:
## 
##                      k  estimate      se    pval   ci.lb   ci.ub 
## 0     &lt; p &lt;= 0.025  11    1.0000     ---     ---     ---     ---    
## 0.025 &lt; p &lt;= 1       7    1.1500  0.8755  0.8639  0.0000  2.8660    
## 
## ---
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p><code>Model Results</code> の下で、選択モデルの真の平均効果量の推定値が <span class="math inline">\(g=\)</span> 0.59 (95%CI: 0.34-0.84) であることを見ることが可能である。興味深いことに、この推定値は、以前に得たプール効果量 (<span class="math inline">\(g=\)</span> 0.58) とほぼ同じである。</p>
<p>全体として、これはメタ分析が有意でない結果の低い選択確率によって実質的にバイアスされたことを<strong>示さない</strong>ことを示している。この結果は、<code>Test of Selection Model Parameters</code> によって裏付けられ、有意ではない (<span class="math inline">\(\chi^2_1=\)</span> 0.034, <span class="math inline">\(p=\)</span> 0.85) ことから、<span class="math inline">\(\omega_1\)</span> と <span class="math inline">\(\omega_2\)</span> は互いに有意な差がないことを物語っている。</p>
<p><code>Selection Model Results</code>の下に、両方のビンにおける相対的な選択尤度の推定値が表示されている。 <span class="math inline">\(\omega_2=\)</span> 1.15 で、2 番目のセグメントの選択確率が1番目のセグメントよりわずかに高いことがわかる。実質的な出版バイアスがある場合は、その逆で、有意でない結果の相対選択尤度は、有意な発見と比較してかなり<strong>低く</strong>なることが予想される。</p>
<p>感度分析として、<span class="math inline">\(a_1\)</span> を 0.025 から 0.05 に変更し、分析を再実行することが可能である。カットポイントを0.05に設定するということは、0.05 と 0.10 の間の両側 <span class="math inline">\(p\)</span>-値は、0.05 以下の値と同様に「出版可能」であると仮定することである。例えば、「傾向レベル」で有意な結果が選ばれる可能性がある、あるいは、元の研究の中には、研究グループの違いを評価するために片側検定を使っているものがある、などの可能性がある。このカットポイントの変更で結果が変わるかどうか見てみよう。</p>
<div class="sourceCode" id="cb299"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/selmodel.html">selmodel</a></span><span class="op">(</span><span class="va">m.rma</span>,</span>
<span>         type <span class="op">=</span> <span class="st">"stepfun"</span>,</span>
<span>         steps <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [...]
## 
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   0.3661  0.1755  2.0863  0.0370  0.0222  0.7100  * 
## 
## Test for Selection Model Parameters:
## LRT(df = 1) = 3.9970, p-val = 0.0456
## 
## Selection Model Results:
## 
##                    k  estimate     se   pval   ci.lb   ci.ub 
## 0    &lt; p &lt;= 0.05  15    1.0000    ---    ---     ---     ---      
## 0.05 &lt; p &lt;= 1      3    0.1786 0.1665 &lt;.0001  0.0000  0.5050  *** 
## 
## ---
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>興味深いことに、異なるパターンが見られる。新しい平均効果量推定値は、<span class="math inline">\(g=\)</span> 0.37 で、以前より小さくなっている。さらに、尤度検定は有意で、区間が異なることを示している。<span class="math inline">\(\omega_2=\)</span> 0.18 で、選択尤度 (両側) <span class="math inline">\(p&gt;\)</span> 0.1 は、(僅かに) 有意な <span class="math inline">\(p\)</span>-値のものよりもずっと低いと見ることが可能である。</p>
<p>このことは、プール効果が選択的な報告によってわずかに歪められている可能性を示している。特に、<strong>明らかに</strong>有意でない結果を示した研究がファイル引き出しに収められたためである。</p>
<p><br></p>
</div>
<div id="fixed-weights-selmodel" class="section level5" number="9.2.3.1.2">
<h5>
<span class="header-section-number">9.2.3.1.2</span> 固定重み選択モデル<a class="anchor" aria-label="anchor" href="#fixed-weights-selmodel"><i class="fas fa-link"></i></a>
</h5>
<hr>
<p>先ほど説明した3パラメータ選択モデルでは、カットポイント <span class="math inline">\(a_1\)</span> を 1 つだけ指定し、選択尤度はモデルによって自由に推定することが可能である。前述したように、3 パラメータ・モデルが 1 つのカットポイントしか使わないということは、比較的少ない研究のメタ分析にも適用可能である。これは、モデルがいくつかのビンにおいて「研究を使い果たす」可能性が低いことがある。</p>
<p>しかし、選択尤度 <span class="math inline">\(\omega_i\)</span> をデータから推定する必要がなければ、選択モデルの大きなサンプルサイズの必要性を回避することができる。単に各区間の固定値 <span class="math inline">\(\omega_i\)</span> を与えて、課されたモデルのもとで <span class="math inline">\(\mu\)</span> の推定値がどうなるかをチェックすればよい。このアプローチは、より複雑な選択モデル (つまり、より多くのカットポイントを持つモデル) を適合させることができる一方で、欠点もある。</p>
<p>このような<strong>固定重み選択モデル</strong>を課す場合、あらかじめ指定された <span class="math inline">\(\omega_i\)</span> の値がすべて正しいと単純に仮定することになる。しかし、モデルが適切でない場合、平均効果の推定値が信用できなくなることを意味する。したがって、固定ウェイトモデルは、想定した選択プロセスが適用された場合、真の効果量がどのように見えるか**を確認する方法と見なすべきである。</p>
<p>Vevea and Woods <span class="citation">(<a href="references.html#ref-vevea2005publication">2005</a>)</span> は、このようなマルチカットポイント、固定重みの選択モデルがどのように見えるかの例をいくつか示している。下のプロットは、中程度の選択と厳しい選択を表すステップ関数の2つの例を示している。</p>
<div class="inline-figure"><img src="Doing_Meta_Analysis_in_R_files/figure-html/unnamed-chunk-262-1.png" width="55%" style="display: block; margin: auto;"></div>
<p>感度分析として、これらの選択モデルがメタ分析に適切であると仮定したときに、<span class="math inline">\(\mu\)</span> の推定値がどのように変化するかを確認することが可能である。これを行うには、上に表示されたモデルで使われたすべてのカットポイント、および各区間に与えられた尤度 <span class="math inline">\(\omega_i\)</span> を定義する必要がある。</p>
<div class="sourceCode" id="cb301"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># カットポイントを定義</span></span>
<span><span class="va">a</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.005</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.10</span>, <span class="fl">0.25</span>, <span class="fl">0.35</span>, <span class="fl">0.50</span>, </span>
<span>       <span class="fl">0.65</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span>, <span class="fl">0.995</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># それぞれの信頼区間の選択尤度を定義</span></span>
<span><span class="co"># (moderate/severe selection)</span></span>
<span><span class="va">w.moderate</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0.99</span>, <span class="fl">0.95</span>, <span class="fl">0.80</span>, <span class="fl">0.75</span>, <span class="fl">0.65</span>, <span class="fl">0.60</span>, </span>
<span>                <span class="fl">0.55</span>, <span class="fl">0.50</span>, <span class="fl">0.50</span>, <span class="fl">0.50</span>, <span class="fl">0.50</span>, <span class="fl">0.50</span>, <span class="fl">0.50</span><span class="op">)</span></span>
<span><span class="va">w.severe</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0.99</span>, <span class="fl">0.90</span>, <span class="fl">0.75</span>, <span class="fl">0.60</span>, <span class="fl">0.50</span>, <span class="fl">0.40</span>, <span class="fl">0.35</span>, </span>
<span>              <span class="fl">0.30</span>, <span class="fl">0.25</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span>, <span class="fl">0.10</span><span class="op">)</span></span></code></pre></div>
<p>これらのパラメータが定義されると、<code>selmodel</code> を呼び出す際に使用することが可能である。新しいカットポイントは <code>steps</code> 引数に、固定尤度は <code>delta</code> に与える必要がある。</p>
<div class="sourceCode" id="cb302"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 中程度の選択を仮定し、モデルを適合</span></span>
<span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/selmodel.html">selmodel</a></span><span class="op">(</span><span class="va">m.rma</span>, type <span class="op">=</span> <span class="st">"stepfun"</span>, steps <span class="op">=</span> <span class="va">a</span>, delta <span class="op">=</span> <span class="va">w.moderate</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [...]
## 
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   0.5212  0.0935  5.5741  &lt;.0001  0.3380  0.7045  *** 
##
## [...]</code></pre>
<div class="sourceCode" id="cb304"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># 高度の選択を仮定し、モデルを適合</span></span>
<span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/selmodel.html">selmodel</a></span><span class="op">(</span><span class="va">m.rma</span>, type <span class="op">=</span> <span class="st">"stepfun"</span>, steps <span class="op">=</span> <span class="va">a</span>, delta <span class="op">=</span> <span class="va">w.severe</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [...]
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   0.4601  0.1211  3.8009  0.0001  0.2229  0.6974  *** 
## [...]</code></pre>
<p>中程度の選択を代表する選択モデルを課した場合、プール効果量の推定値は <span class="math inline">\(g=\)</span> 0.52 であることがわかる。厳しい選択過程を仮定すると、<span class="math inline">\(g=\)</span> 0.46 という少し低い効果が得られる。</p>
<p>これらの結果は、選択的出版をコントロールした場合でも、観察された効果がかなり頑健であることを示している。しかし、重要なのは、これらの推定値が有効なのは、私たちが規定した選択モデルが現実を代表している場合のみであるということである。</p>
<div class="boxinfo">
<p>
<strong>その他の選択モデル関数</strong>
</p>
<p>
この例では、選択モデルの基礎となるステップ関数のみを取り上げた。しかし、選択過程をモデル化するために使える関数はこれだけではないことに注意する必要がある。<code>selmodel</code>
関数には、例えば、半正規分布、ロジスティック分布、負指数分布など、
<strong>連続</strong>
分布に基づいた関数もいくつか含まれている。これらのモデルは、
<code>type</code> 引数の仕様を変更することで選択することができる。
</p>
<p>
使用できるモデルについてすべて説明することはこのガイドの範囲外だが、
<code>selmodel</code>
関数のドキュメントが素晴らしいイントロダクションを提供している。このドキュメントには、
<strong>{metafor}</strong> がロードされた後に、 <em>R</em> で
<code><a href="https://wviechtb.github.io/metafor/reference/selmodel.html">?selmodel</a></code> を実行することでアクセスすることができる。
</p>
</div>
<p><br></p>
</div>
</div>
</div>
</div>
<div id="pub-bias-which-method" class="section level2" number="9.3">
<h2>
<span class="header-section-number">9.3</span> どの方法を使うべきか？<a class="anchor" aria-label="anchor" href="#pub-bias-which-method"><i class="fas fa-link"></i></a>
</h2>
<hr>
<p>以上で、出版バイアスの統計的手法に関する考察を終えたい。この章はかなり長くなってしまったが、なぜこれほど多くの異なるアプローチについて議論したのかと聞きたいのではないだろうか。1つの方法を選び、その方法で出版バイアスのリスクを評価し、次に進むだけでは十分ではないのだろうか？</p>
<p>短い答えは「ノー」である。出版バイアスの手法は依然として非常に活発な研究テーマであり、多くの研究が長年にわたってさまざまなアプローチの性能を評価してきました <span class="citation">(例: <a href="references.html#ref-simonsohn2014es">Simonsohn, Nelson, and Simmons 2014a</a>; <a href="references.html#ref-stanley2017limitations">T. D. Stanley 2017</a>; <a href="references.html#ref-aert2016conducting">Aert, Wicherts, and Assen 2016</a>; <a href="references.html#ref-mcshane2016adjusting">McShane, Böckenholt, and Hansen 2016</a>; <a href="references.html#ref-rucker2011treatment">Rücker et al. 2011</a>; <a href="references.html#ref-terrin2003adjusting">Terrin et al. 2003</a>; <a href="references.html#ref-peters2007performance">Peters et al. 2007</a>)</span>。残念なことに、まだ明確な勝者は現れていない。それどころか、どの出版バイアス法も他のすべての方法を一貫して凌駕しているというエビデンスもある <span class="citation">(<a href="references.html#ref-carter2019correcting">Carter et al. 2019</a>)</span>。</p>
<p>出版バイアスの方法が異なると、結果が大きく異なることはよくあることで、実際によくあることである。この章の実践的な演習は、その好例である。毎回同じデータセットを使用してきたが、真のバイアス補正効果の推定値は、実質的にゼロから <span class="math inline">\(g=\)</span> 0.59まで幅があった。このことは、手法の選択が結果、ひいては結論に大きな影響を与える可能性があることを強調している。いくつかの方法は、小規模研究の影響をコントロールするとプール効果が完全に消失することを示したが、他の方法は、最初の発見をほぼ裏付けるものであった。</p>
<p>この問題に対処するため、出版バイアスを評価する際には、常に<strong>複数の</strong>手法を用いることを勧める。どの方法がこのデータに最も適しているか、その結果が信頼に足るかどうかを知ることは、不可能ではないにしても、しばしば困難なことである。前述したように、選択的な報告がどの程度結果に影響を及ぼしているのか、正確なところは常に不明である。しかし、いくつかの出版バイアスの手法を適用することで、信頼できる真の効果の<strong>範囲</strong>に近いものを作り出すことが可能である。</p>
<p>
</p>
<p>この範囲の大きさは、私たちの解釈を導くために使用することが可能である。例えば、PET-PEESE、p-曲線、3 パラメータ選択モデルの両方が、最初のプール効果に近い推定値を得た場合、発見の頑健性に対する信頼性が高まる。しかし、各手法が一致しないことが判明した場合は、そうではない。これは、出版バイアスや小規模研究の影響がより不確実であることを意味し、プールされた効果の信頼性も同様に不確実である。</p>
<p>いずれにせよ、出版バイアス法の結果は、常に慎重に解釈されるべきである。出版バイアス分析の結果が論争に発展した例もある–たとえば、文献 “ego-depletion” <span class="citation">(<a href="references.html#ref-friese2019ego">Friese et al. 2019</a>)</span> 。出版バイアスをコントロールする最善の方法は、未出版のエビデンスを適切に検索し、出版方法を全面的に変更することであることを心に留めておくことが重要である。私たちメタ分析者が思いつく出版バイアスの統計的「証明」は、どれもせいぜい弱いものである。</p>
<p>どの方式を適用するかを決定しやすくするために、各方式の長所と短所の簡単な概要を作成した ( Table <a href="pub-bias.html#tab:pubtab">9.1</a> 参照)。</p>
<div class="inline-table"><table class="table table-condensed table-striped" style="font-size: 15px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:pubtab">Table 9.1: </span>出版バイアスを補正し真の効果量を推定する方法。長所と短所の概要。
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;">
</th>
<th style="text-align:left;font-weight: bold;">
長所
</th>
<th style="text-align:left;font-weight: bold;">
短所
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;width: 2cm; font-weight: bold;">
Duval &amp; Tweedie トリム＆フィル
</td>
<td style="text-align:left;width: 4cm; ">
実務で非常に多用されている。多くの研究者が解釈できる。
</td>
<td style="text-align:left;width: 5cm; ">
真の効果がゼロの場合など、効果量を十分に補正できないことが多い。不均一性が非常に大きい場合、ロバストでなく、他の手法に劣る。
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; font-weight: bold;">
PET-PEESE
</td>
<td style="text-align:left;width: 4cm; ">
シンプルで直感的なモデルに基づく。実装と解釈が容易。 BREA
</td>
<td style="text-align:left;width: 5cm; ">
効果を過大評価または過小評価することがある。研究数が少ない、サンプルサイズが小さい、異質性が高いなどのメタアナリシスでは、性能が弱い。
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; font-weight: bold;">
限界メタ分析
</td>
<td style="text-align:left;width: 4cm; ">
PET-PEESEと同様のアプローチだが、試験間の不均一性を明示的にモデル化したもの。
</td>
<td style="text-align:left;width: 5cm; ">
効果を過大評価または過小評価することがある。研究数が少なく、サンプルサイズが小さい、そして高いメタアナリシスでは性能が低い 他の手法に比べて性能はあまり研究されていない。研究数が非常に少なく(&lt;10)、異質性が非常に高い場合、失敗する可能性がある。
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; font-weight: bold;">
P-曲線
</td>
<td style="text-align:left;width: 4cm; ">
前提条件を満たせば、他の手法（特にトリム＆フィル）よりも優れていることが示されている。
</td>
<td style="text-align:left;width: 5cm; ">
実際にはありえないが、不均一性がないという仮定のもとで機能する。最小限の有意な効果量を必要とする。解釈と伝達が容易でない。
</td>
</tr>
<tr>
<td style="text-align:left;width: 2cm; font-weight: bold;">
選択モデル
</td>
<td style="text-align:left;width: 4cm; ">
想定されるあらゆる種類の選択過程を潜在的にモデル化できる。３パラメータ選択モデルは、シミュレーション研究において良好な性能を示している。
</td>
<td style="text-align:left;width: 5cm; ">
選択モデルが出版バイアスのプロセスを適切に記述している場合にのみ有効。他の小規模研究の効果は関係ないと仮定する。解釈が難しい場合があり、背景知識が必要。
</td>
</tr>
</tbody>
</table></div>
<p>この表には統計的な考察と実際的な考察の両方が含まれており、包括的でも最終的でもないと見るべきだろう。出版バイアスの方法は現在進行中の研究分野であり、より多くのエビデンスが確立されれば、状況は違ってくる可能性がある。</p>
<p>
</p>
<p>最後に、研究間異質性が高い場合に許容できる結果を提供する方法は、現在のところ存在しないことに留意が必要である <span class="citation">(<a href="references.html#ref-aert2016conducting">Aert, Wicherts, and Assen 2016</a>、すなわち <span class="math inline">\(I^2 \approx\)</span> 75%)</span>。つまり、異質性が非常に高いメタ分析の出版バイアス分析は、完全に避けるのが最善である。外れ値を含まない解析やより均質なサブグループでの解析は、しばしば実用的な回避策として使用できるが、一般的な問題を解決するものではない。</p>
<p><span class="math display">\[\tag*{$\blacksquare$}\]</span></p>
<p><br></p>
</div>
<div id="演習問題-8" class="section level2" number="9.4">
<h2>
<span class="header-section-number">9.4</span> 演習問題<a class="anchor" aria-label="anchor" href="#%E6%BC%94%E7%BF%92%E5%95%8F%E9%A1%8C-8"><i class="fas fa-link"></i></a>
</h2>
<div class="boxquestion">
<p>
<strong>知識を試そう！</strong>
</p>
<ol style="list-style-type: decimal">
<li>
「出版バイアス」という言葉はどのように定義できるか？なぜメタ分析で問題になるのか？
</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>
他にどのような報告バイアスがあるか？少なくとも3つ挙げて説明しなさい。
</li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li>
疑わしい研究慣行 (QRP)
を2つ挙げ、どのようにメタ分析の妥当性を脅かすかを説明しなさい。
</li>
</ol>
<ol start="4" style="list-style-type: decimal">
<li>
小規模研究効果法の基本的な前提を説明しなさい。
</li>
</ol>
<ol start="5" style="list-style-type: decimal">
<li>
データが小規模研究の効果を示すことがわかったとき、自動的に出版バイアスがあることを意味するか？
</li>
</ol>
<ol start="6" style="list-style-type: decimal">
<li>
p-曲線は、メタ分析に含まれるすべての研究の真の効果を推定するのか、それとも「有意な」効果量を持つすべての研究の真の効果だけを推定するのか、どちらか？
</li>
</ol>
<ol start="7" style="list-style-type: decimal">
<li>
どの出版バイアス法が一番性能が良いか。
</li>
</ol>
<p>
<strong>問題の解答は、本書の巻末 <a href="https://bookdown.org/baba_yoshihiko/Doing_Meta_Analysis_in_R/qanda.html#qanda9">Appendix
A</a> にある。</strong>
</p>
</div>
<p><br></p>
</div>
<div id="要約-5" class="section level2" number="9.5">
<h2>
<span class="header-section-number">9.5</span> 要約<a class="anchor" aria-label="anchor" href="#%E8%A6%81%E7%B4%84-5"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li><p>出版バイアスは、ある研究が出版された文献の中で体系的に欠落している場合に発生し、その結果、私たちのメタ分析においても発生した。厳密には、出版バイアスは、ある研究が出版される確率がその結果に依存する場合に発生した。しかし、その他にも様々な<strong>報告バイアス</strong>が存在した。これらの報告バイアスも、ある知見がメタ分析に採用される可能性に影響を及ぼした。例えば、引用バイアス、言語バイアス、アウトカムバイアスなどである。</p></li>
<li><p>また、例えば疑わしい研究の実施 (QRP) などにより、<strong>発表</strong>されたエビデンスに偏りがある可能性もある。よくあるQRPは、<span class="math inline">\(p\)</span> -hackingとHARKingの2つで、どちらもメタ分析で効果を過大評価するリスクを高める可能性がある。</p></li>
<li><p>多くの出版バイアス法は、<strong>小規模研究効果</strong>という考えに基づいている。これらのアプローチは、驚くほど高い効果量を持つ小規模な研究だけが有意な結果を得て、それゆえ出版用に選択されると仮定している。これは、非対称のファンネルプロットをもたらし、出版バイアスの徴候となり得る。しかし、そうである必要はない。小規模研究の効果には、さまざまな「良性」の原因が考えられる。</p></li>
<li><p>比較的新しい手法である <strong>p-曲線</strong>は、データ中の有意な効果 (<span class="math inline">\(p&lt;\)</span> 0.05 )のパターンを見るだけで、証拠能力をコントロールできるという考えに基づいている。これは、真の効果の有無の検定に使用でき、その大きさを推定することができる。</p></li>
<li><p><strong>選択モデル</strong>は非常に汎用性の高い手法で、様々な出版バイアスのプロセスをモデル化するために使用することが可能である。しかし、想定したモデルが適切である場合にのみ有効な結果が得られ、しばしば非常に多くの研究を必要とした。非常にシンプルな選択モデルである3パラメータモデルも、小規模なデータセットに使用することが可能である。</p></li>
<li><p>出版バイアスの手法は、他の手法を常に凌駕するものではない。したがって、常に<strong>複数の</strong>手法を適用し、補正後の効果量を慎重に解釈することが推奨される。未発表のエビデンスの徹底的な検索は、現在の統計的アプローチよりもはるかに優れた方法で出版バイアスのリスクを軽減する。</p></li>
</ul>
</div>
</div>




  <div class="chapter-nav">
<div class="prev"><a href="metareg.html"><span class="header-section-number">8</span> メタ回帰</a></div>
<div class="next"><a href="multilevel-ma.html"><span class="header-section-number">10</span> 「マルチレベル」メタ分析</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#pub-bias"><span class="header-section-number">9</span> 出版バイアス</a></li>
<li><a class="nav-link" href="#types-of-pub-biases"><span class="header-section-number">9.1</span> 出版バイアスとは何か？</a></li>
<li>
<a class="nav-link" href="#addressing-pubbias"><span class="header-section-number">9.2</span> メタ分析における出版バイアス</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#small-study-effects"><span class="header-section-number">9.2.1</span> 小規模研究効果測定法</a></li>
<li><a class="nav-link" href="#p-curve"><span class="header-section-number">9.2.2</span> P 曲線</a></li>
<li><a class="nav-link" href="#selection-models"><span class="header-section-number">9.2.3</span> 選択モデル</a></li>
</ul>
</li>
<li><a class="nav-link" href="#pub-bias-which-method"><span class="header-section-number">9.3</span> どの方法を使うべきか？</a></li>
<li><a class="nav-link" href="#%E6%BC%94%E7%BF%92%E5%95%8F%E9%A1%8C-8"><span class="header-section-number">9.4</span> 演習問題</a></li>
<li><a class="nav-link" href="#%E8%A6%81%E7%B4%84-5"><span class="header-section-number">9.5</span> 要約</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Doing Meta-Analysis in R</strong>: A Hands-on Guide" was written by Mathias Harrer, Pim Cuijpers, Toshi A. Furukawa, David D. Ebert. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
